// Code generated by MockGen. DO NOT EDIT.
// Source: querier.go
//
// Generated by this command:
//
//	mockgen -source=querier.go -package=mock -destination=mock/querier.go Querier
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/JRAdams472/LENA2/internal/inventory/sqlc"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CountBrandsVisible mocks base method.
func (m *MockQuerier) CountBrandsVisible(ctx context.Context, submittedByUserID pgtype.Int8) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBrandsVisible", ctx, submittedByUserID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBrandsVisible indicates an expected call of CountBrandsVisible.
func (mr *MockQuerierMockRecorder) CountBrandsVisible(ctx, submittedByUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBrandsVisible", reflect.TypeOf((*MockQuerier)(nil).CountBrandsVisible), ctx, submittedByUserID)
}

// CountIngredients mocks base method.
func (m *MockQuerier) CountIngredients(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountIngredients", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountIngredients indicates an expected call of CountIngredients.
func (mr *MockQuerierMockRecorder) CountIngredients(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountIngredients", reflect.TypeOf((*MockQuerier)(nil).CountIngredients), ctx)
}

// CountItems mocks base method.
func (m *MockQuerier) CountItems(ctx context.Context, submittedByUserID pgtype.Int8) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountItems", ctx, submittedByUserID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountItems indicates an expected call of CountItems.
func (mr *MockQuerierMockRecorder) CountItems(ctx, submittedByUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountItems", reflect.TypeOf((*MockQuerier)(nil).CountItems), ctx, submittedByUserID)
}

// CountPendingBrands mocks base method.
func (m *MockQuerier) CountPendingBrands(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPendingBrands", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPendingBrands indicates an expected call of CountPendingBrands.
func (mr *MockQuerierMockRecorder) CountPendingBrands(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPendingBrands", reflect.TypeOf((*MockQuerier)(nil).CountPendingBrands), ctx)
}

// CountPendingItems mocks base method.
func (m *MockQuerier) CountPendingItems(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPendingItems", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPendingItems indicates an expected call of CountPendingItems.
func (mr *MockQuerierMockRecorder) CountPendingItems(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPendingItems", reflect.TypeOf((*MockQuerier)(nil).CountPendingItems), ctx)
}

// CountSearchIngredients mocks base method.
func (m *MockQuerier) CountSearchIngredients(ctx context.Context, search pgtype.Text) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSearchIngredients", ctx, search)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSearchIngredients indicates an expected call of CountSearchIngredients.
func (mr *MockQuerierMockRecorder) CountSearchIngredients(ctx, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSearchIngredients", reflect.TypeOf((*MockQuerier)(nil).CountSearchIngredients), ctx, search)
}

// CountSearchItems mocks base method.
func (m *MockQuerier) CountSearchItems(ctx context.Context, arg sqlc.CountSearchItemsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSearchItems", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSearchItems indicates an expected call of CountSearchItems.
func (mr *MockQuerierMockRecorder) CountSearchItems(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSearchItems", reflect.TypeOf((*MockQuerier)(nil).CountSearchItems), ctx, arg)
}

// CreateAllergen mocks base method.
func (m *MockQuerier) CreateAllergen(ctx context.Context, arg sqlc.CreateAllergenParams) (sqlc.InventoryAllergen, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAllergen", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryAllergen)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAllergen indicates an expected call of CreateAllergen.
func (mr *MockQuerierMockRecorder) CreateAllergen(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAllergen", reflect.TypeOf((*MockQuerier)(nil).CreateAllergen), ctx, arg)
}

// CreateAllergenSuggestion mocks base method.
func (m *MockQuerier) CreateAllergenSuggestion(ctx context.Context, arg sqlc.CreateAllergenSuggestionParams) (sqlc.InventoryAllergenSuggestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAllergenSuggestion", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryAllergenSuggestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAllergenSuggestion indicates an expected call of CreateAllergenSuggestion.
func (mr *MockQuerierMockRecorder) CreateAllergenSuggestion(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAllergenSuggestion", reflect.TypeOf((*MockQuerier)(nil).CreateAllergenSuggestion), ctx, arg)
}

// CreateBrand mocks base method.
func (m *MockQuerier) CreateBrand(ctx context.Context, arg sqlc.CreateBrandParams) (sqlc.InventoryBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBrand", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBrand indicates an expected call of CreateBrand.
func (mr *MockQuerierMockRecorder) CreateBrand(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBrand", reflect.TypeOf((*MockQuerier)(nil).CreateBrand), ctx, arg)
}

// CreateBrandPending mocks base method.
func (m *MockQuerier) CreateBrandPending(ctx context.Context, arg sqlc.CreateBrandPendingParams) (sqlc.InventoryBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBrandPending", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBrandPending indicates an expected call of CreateBrandPending.
func (mr *MockQuerierMockRecorder) CreateBrandPending(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBrandPending", reflect.TypeOf((*MockQuerier)(nil).CreateBrandPending), ctx, arg)
}

// CreateCategory mocks base method.
func (m *MockQuerier) CreateCategory(ctx context.Context, arg sqlc.CreateCategoryParams) (sqlc.InventoryCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockQuerierMockRecorder) CreateCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockQuerier)(nil).CreateCategory), ctx, arg)
}

// CreateFlavorProfile mocks base method.
func (m *MockQuerier) CreateFlavorProfile(ctx context.Context, arg sqlc.CreateFlavorProfileParams) (sqlc.InventoryFlavorProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFlavorProfile", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryFlavorProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFlavorProfile indicates an expected call of CreateFlavorProfile.
func (mr *MockQuerierMockRecorder) CreateFlavorProfile(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFlavorProfile", reflect.TypeOf((*MockQuerier)(nil).CreateFlavorProfile), ctx, arg)
}

// CreateFoodFlavor mocks base method.
func (m *MockQuerier) CreateFoodFlavor(ctx context.Context, arg sqlc.CreateFoodFlavorParams) (sqlc.CreateFoodFlavorRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFoodFlavor", ctx, arg)
	ret0, _ := ret[0].(sqlc.CreateFoodFlavorRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFoodFlavor indicates an expected call of CreateFoodFlavor.
func (mr *MockQuerierMockRecorder) CreateFoodFlavor(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFoodFlavor", reflect.TypeOf((*MockQuerier)(nil).CreateFoodFlavor), ctx, arg)
}

// CreateFoodNutrient mocks base method.
func (m *MockQuerier) CreateFoodNutrient(ctx context.Context, arg sqlc.CreateFoodNutrientParams) (sqlc.CreateFoodNutrientRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFoodNutrient", ctx, arg)
	ret0, _ := ret[0].(sqlc.CreateFoodNutrientRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFoodNutrient indicates an expected call of CreateFoodNutrient.
func (mr *MockQuerierMockRecorder) CreateFoodNutrient(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFoodNutrient", reflect.TypeOf((*MockQuerier)(nil).CreateFoodNutrient), ctx, arg)
}

// CreateIngredient mocks base method.
func (m *MockQuerier) CreateIngredient(ctx context.Context, arg sqlc.CreateIngredientParams) (sqlc.InventoryIngredient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIngredient", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryIngredient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIngredient indicates an expected call of CreateIngredient.
func (mr *MockQuerierMockRecorder) CreateIngredient(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIngredient", reflect.TypeOf((*MockQuerier)(nil).CreateIngredient), ctx, arg)
}

// CreateItem mocks base method.
func (m *MockQuerier) CreateItem(ctx context.Context, arg sqlc.CreateItemParams) (sqlc.InventoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateItem", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateItem indicates an expected call of CreateItem.
func (mr *MockQuerierMockRecorder) CreateItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateItem", reflect.TypeOf((*MockQuerier)(nil).CreateItem), ctx, arg)
}

// CreateNutrientType mocks base method.
func (m *MockQuerier) CreateNutrientType(ctx context.Context, arg sqlc.CreateNutrientTypeParams) (sqlc.InventoryNutrientType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNutrientType", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryNutrientType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNutrientType indicates an expected call of CreateNutrientType.
func (mr *MockQuerierMockRecorder) CreateNutrientType(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNutrientType", reflect.TypeOf((*MockQuerier)(nil).CreateNutrientType), ctx, arg)
}

// CreateUnit mocks base method.
func (m *MockQuerier) CreateUnit(ctx context.Context, arg sqlc.CreateUnitParams) (sqlc.InventoryUnit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUnit", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryUnit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUnit indicates an expected call of CreateUnit.
func (mr *MockQuerierMockRecorder) CreateUnit(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUnit", reflect.TypeOf((*MockQuerier)(nil).CreateUnit), ctx, arg)
}

// DeleteBrand mocks base method.
func (m *MockQuerier) DeleteBrand(ctx context.Context, brandID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBrand", ctx, brandID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBrand indicates an expected call of DeleteBrand.
func (mr *MockQuerierMockRecorder) DeleteBrand(ctx, brandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBrand", reflect.TypeOf((*MockQuerier)(nil).DeleteBrand), ctx, brandID)
}

// DeleteCategory mocks base method.
func (m *MockQuerier) DeleteCategory(ctx context.Context, categoryID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, categoryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockQuerierMockRecorder) DeleteCategory(ctx, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockQuerier)(nil).DeleteCategory), ctx, categoryID)
}

// DeleteFlavorProfile mocks base method.
func (m *MockQuerier) DeleteFlavorProfile(ctx context.Context, flavorID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFlavorProfile", ctx, flavorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFlavorProfile indicates an expected call of DeleteFlavorProfile.
func (mr *MockQuerierMockRecorder) DeleteFlavorProfile(ctx, flavorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFlavorProfile", reflect.TypeOf((*MockQuerier)(nil).DeleteFlavorProfile), ctx, flavorID)
}

// DeleteFoodFlavor mocks base method.
func (m *MockQuerier) DeleteFoodFlavor(ctx context.Context, arg sqlc.DeleteFoodFlavorParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFoodFlavor", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFoodFlavor indicates an expected call of DeleteFoodFlavor.
func (mr *MockQuerierMockRecorder) DeleteFoodFlavor(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFoodFlavor", reflect.TypeOf((*MockQuerier)(nil).DeleteFoodFlavor), ctx, arg)
}

// DeleteFoodNutrient mocks base method.
func (m *MockQuerier) DeleteFoodNutrient(ctx context.Context, arg sqlc.DeleteFoodNutrientParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFoodNutrient", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFoodNutrient indicates an expected call of DeleteFoodNutrient.
func (mr *MockQuerierMockRecorder) DeleteFoodNutrient(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFoodNutrient", reflect.TypeOf((*MockQuerier)(nil).DeleteFoodNutrient), ctx, arg)
}

// DeleteFoodNutrientsByItem mocks base method.
func (m *MockQuerier) DeleteFoodNutrientsByItem(ctx context.Context, foodID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFoodNutrientsByItem", ctx, foodID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFoodNutrientsByItem indicates an expected call of DeleteFoodNutrientsByItem.
func (mr *MockQuerierMockRecorder) DeleteFoodNutrientsByItem(ctx, foodID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFoodNutrientsByItem", reflect.TypeOf((*MockQuerier)(nil).DeleteFoodNutrientsByItem), ctx, foodID)
}

// DeleteIngredient mocks base method.
func (m *MockQuerier) DeleteIngredient(ctx context.Context, ingredientID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIngredient", ctx, ingredientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIngredient indicates an expected call of DeleteIngredient.
func (mr *MockQuerierMockRecorder) DeleteIngredient(ctx, ingredientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIngredient", reflect.TypeOf((*MockQuerier)(nil).DeleteIngredient), ctx, ingredientID)
}

// DeleteIngredientAllergen mocks base method.
func (m *MockQuerier) DeleteIngredientAllergen(ctx context.Context, arg sqlc.DeleteIngredientAllergenParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIngredientAllergen", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteIngredientAllergen indicates an expected call of DeleteIngredientAllergen.
func (mr *MockQuerierMockRecorder) DeleteIngredientAllergen(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIngredientAllergen", reflect.TypeOf((*MockQuerier)(nil).DeleteIngredientAllergen), ctx, arg)
}

// DeleteIngredientRefsAisle mocks base method.
func (m *MockQuerier) DeleteIngredientRefsAisle(ctx context.Context, ingredientID pgtype.Int8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIngredientRefsAisle", ctx, ingredientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIngredientRefsAisle indicates an expected call of DeleteIngredientRefsAisle.
func (mr *MockQuerierMockRecorder) DeleteIngredientRefsAisle(ctx, ingredientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIngredientRefsAisle", reflect.TypeOf((*MockQuerier)(nil).DeleteIngredientRefsAisle), ctx, ingredientID)
}

// DeleteIngredientRefsEventRecipeItem mocks base method.
func (m *MockQuerier) DeleteIngredientRefsEventRecipeItem(ctx context.Context, ingredientID pgtype.Int8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIngredientRefsEventRecipeItem", ctx, ingredientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIngredientRefsEventRecipeItem indicates an expected call of DeleteIngredientRefsEventRecipeItem.
func (mr *MockQuerierMockRecorder) DeleteIngredientRefsEventRecipeItem(ctx, ingredientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIngredientRefsEventRecipeItem", reflect.TypeOf((*MockQuerier)(nil).DeleteIngredientRefsEventRecipeItem), ctx, ingredientID)
}

// DeleteIngredientRefsGroceryLine mocks base method.
func (m *MockQuerier) DeleteIngredientRefsGroceryLine(ctx context.Context, ingredientID pgtype.Int8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIngredientRefsGroceryLine", ctx, ingredientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIngredientRefsGroceryLine indicates an expected call of DeleteIngredientRefsGroceryLine.
func (mr *MockQuerierMockRecorder) DeleteIngredientRefsGroceryLine(ctx, ingredientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIngredientRefsGroceryLine", reflect.TypeOf((*MockQuerier)(nil).DeleteIngredientRefsGroceryLine), ctx, ingredientID)
}

// DeleteIngredientRefsMealSlot mocks base method.
func (m *MockQuerier) DeleteIngredientRefsMealSlot(ctx context.Context, ingredientID pgtype.Int8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIngredientRefsMealSlot", ctx, ingredientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIngredientRefsMealSlot indicates an expected call of DeleteIngredientRefsMealSlot.
func (mr *MockQuerierMockRecorder) DeleteIngredientRefsMealSlot(ctx, ingredientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIngredientRefsMealSlot", reflect.TypeOf((*MockQuerier)(nil).DeleteIngredientRefsMealSlot), ctx, ingredientID)
}

// DeleteIngredientRefsRecipeItem mocks base method.
func (m *MockQuerier) DeleteIngredientRefsRecipeItem(ctx context.Context, ingredientID pgtype.Int8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIngredientRefsRecipeItem", ctx, ingredientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIngredientRefsRecipeItem indicates an expected call of DeleteIngredientRefsRecipeItem.
func (mr *MockQuerierMockRecorder) DeleteIngredientRefsRecipeItem(ctx, ingredientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIngredientRefsRecipeItem", reflect.TypeOf((*MockQuerier)(nil).DeleteIngredientRefsRecipeItem), ctx, ingredientID)
}

// DeleteIngredientRefsRoute mocks base method.
func (m *MockQuerier) DeleteIngredientRefsRoute(ctx context.Context, ingredientID pgtype.Int8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIngredientRefsRoute", ctx, ingredientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIngredientRefsRoute indicates an expected call of DeleteIngredientRefsRoute.
func (mr *MockQuerierMockRecorder) DeleteIngredientRefsRoute(ctx, ingredientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIngredientRefsRoute", reflect.TypeOf((*MockQuerier)(nil).DeleteIngredientRefsRoute), ctx, ingredientID)
}

// DeleteIngredientRefsUsual mocks base method.
func (m *MockQuerier) DeleteIngredientRefsUsual(ctx context.Context, ingredientID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIngredientRefsUsual", ctx, ingredientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIngredientRefsUsual indicates an expected call of DeleteIngredientRefsUsual.
func (mr *MockQuerierMockRecorder) DeleteIngredientRefsUsual(ctx, ingredientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIngredientRefsUsual", reflect.TypeOf((*MockQuerier)(nil).DeleteIngredientRefsUsual), ctx, ingredientID)
}

// DeleteItem mocks base method.
func (m *MockQuerier) DeleteItem(ctx context.Context, itemID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockQuerierMockRecorder) DeleteItem(ctx, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockQuerier)(nil).DeleteItem), ctx, itemID)
}

// DeleteItemAllergen mocks base method.
func (m *MockQuerier) DeleteItemAllergen(ctx context.Context, arg sqlc.DeleteItemAllergenParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItemAllergen", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteItemAllergen indicates an expected call of DeleteItemAllergen.
func (mr *MockQuerierMockRecorder) DeleteItemAllergen(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItemAllergen", reflect.TypeOf((*MockQuerier)(nil).DeleteItemAllergen), ctx, arg)
}

// DeleteItemIngredientOverride mocks base method.
func (m *MockQuerier) DeleteItemIngredientOverride(ctx context.Context, arg sqlc.DeleteItemIngredientOverrideParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItemIngredientOverride", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteItemIngredientOverride indicates an expected call of DeleteItemIngredientOverride.
func (mr *MockQuerierMockRecorder) DeleteItemIngredientOverride(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItemIngredientOverride", reflect.TypeOf((*MockQuerier)(nil).DeleteItemIngredientOverride), ctx, arg)
}

// DeleteNutrientType mocks base method.
func (m *MockQuerier) DeleteNutrientType(ctx context.Context, nutrientID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNutrientType", ctx, nutrientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNutrientType indicates an expected call of DeleteNutrientType.
func (mr *MockQuerierMockRecorder) DeleteNutrientType(ctx, nutrientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNutrientType", reflect.TypeOf((*MockQuerier)(nil).DeleteNutrientType), ctx, nutrientID)
}

// DemoteIngredientRefsEventRecipeItem mocks base method.
func (m *MockQuerier) DemoteIngredientRefsEventRecipeItem(ctx context.Context, ingredientID pgtype.Int8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DemoteIngredientRefsEventRecipeItem", ctx, ingredientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DemoteIngredientRefsEventRecipeItem indicates an expected call of DemoteIngredientRefsEventRecipeItem.
func (mr *MockQuerierMockRecorder) DemoteIngredientRefsEventRecipeItem(ctx, ingredientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DemoteIngredientRefsEventRecipeItem", reflect.TypeOf((*MockQuerier)(nil).DemoteIngredientRefsEventRecipeItem), ctx, ingredientID)
}

// DemoteIngredientRefsGroceryLine mocks base method.
func (m *MockQuerier) DemoteIngredientRefsGroceryLine(ctx context.Context, ingredientID pgtype.Int8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DemoteIngredientRefsGroceryLine", ctx, ingredientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DemoteIngredientRefsGroceryLine indicates an expected call of DemoteIngredientRefsGroceryLine.
func (mr *MockQuerierMockRecorder) DemoteIngredientRefsGroceryLine(ctx, ingredientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DemoteIngredientRefsGroceryLine", reflect.TypeOf((*MockQuerier)(nil).DemoteIngredientRefsGroceryLine), ctx, ingredientID)
}

// DemoteIngredientRefsMealSlot mocks base method.
func (m *MockQuerier) DemoteIngredientRefsMealSlot(ctx context.Context, ingredientID pgtype.Int8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DemoteIngredientRefsMealSlot", ctx, ingredientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DemoteIngredientRefsMealSlot indicates an expected call of DemoteIngredientRefsMealSlot.
func (mr *MockQuerierMockRecorder) DemoteIngredientRefsMealSlot(ctx, ingredientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DemoteIngredientRefsMealSlot", reflect.TypeOf((*MockQuerier)(nil).DemoteIngredientRefsMealSlot), ctx, ingredientID)
}

// DemoteIngredientRefsRecipeItem mocks base method.
func (m *MockQuerier) DemoteIngredientRefsRecipeItem(ctx context.Context, ingredientID pgtype.Int8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DemoteIngredientRefsRecipeItem", ctx, ingredientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DemoteIngredientRefsRecipeItem indicates an expected call of DemoteIngredientRefsRecipeItem.
func (mr *MockQuerierMockRecorder) DemoteIngredientRefsRecipeItem(ctx, ingredientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DemoteIngredientRefsRecipeItem", reflect.TypeOf((*MockQuerier)(nil).DemoteIngredientRefsRecipeItem), ctx, ingredientID)
}

// FindBrandByNormalizedName mocks base method.
func (m *MockQuerier) FindBrandByNormalizedName(ctx context.Context, regexpReplace string) (sqlc.InventoryBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBrandByNormalizedName", ctx, regexpReplace)
	ret0, _ := ret[0].(sqlc.InventoryBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBrandByNormalizedName indicates an expected call of FindBrandByNormalizedName.
func (mr *MockQuerierMockRecorder) FindBrandByNormalizedName(ctx, regexpReplace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBrandByNormalizedName", reflect.TypeOf((*MockQuerier)(nil).FindBrandByNormalizedName), ctx, regexpReplace)
}

// FindIngredientByNormalizedName mocks base method.
func (m *MockQuerier) FindIngredientByNormalizedName(ctx context.Context, regexpReplace string) (sqlc.InventoryIngredient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindIngredientByNormalizedName", ctx, regexpReplace)
	ret0, _ := ret[0].(sqlc.InventoryIngredient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindIngredientByNormalizedName indicates an expected call of FindIngredientByNormalizedName.
func (mr *MockQuerierMockRecorder) FindIngredientByNormalizedName(ctx, regexpReplace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindIngredientByNormalizedName", reflect.TypeOf((*MockQuerier)(nil).FindIngredientByNormalizedName), ctx, regexpReplace)
}

// GetAllergenByID mocks base method.
func (m *MockQuerier) GetAllergenByID(ctx context.Context, allergenID int64) (sqlc.InventoryAllergen, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllergenByID", ctx, allergenID)
	ret0, _ := ret[0].(sqlc.InventoryAllergen)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllergenByID indicates an expected call of GetAllergenByID.
func (mr *MockQuerierMockRecorder) GetAllergenByID(ctx, allergenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllergenByID", reflect.TypeOf((*MockQuerier)(nil).GetAllergenByID), ctx, allergenID)
}

// GetAllergenSuggestion mocks base method.
func (m *MockQuerier) GetAllergenSuggestion(ctx context.Context, allergenSuggestionID int64) (sqlc.GetAllergenSuggestionRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllergenSuggestion", ctx, allergenSuggestionID)
	ret0, _ := ret[0].(sqlc.GetAllergenSuggestionRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllergenSuggestion indicates an expected call of GetAllergenSuggestion.
func (mr *MockQuerierMockRecorder) GetAllergenSuggestion(ctx, allergenSuggestionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllergenSuggestion", reflect.TypeOf((*MockQuerier)(nil).GetAllergenSuggestion), ctx, allergenSuggestionID)
}

// GetAllergensByIDs mocks base method.
func (m *MockQuerier) GetAllergensByIDs(ctx context.Context, allergenIds []int64) ([]sqlc.InventoryAllergen, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllergensByIDs", ctx, allergenIds)
	ret0, _ := ret[0].([]sqlc.InventoryAllergen)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllergensByIDs indicates an expected call of GetAllergensByIDs.
func (mr *MockQuerierMockRecorder) GetAllergensByIDs(ctx, allergenIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllergensByIDs", reflect.TypeOf((*MockQuerier)(nil).GetAllergensByIDs), ctx, allergenIds)
}

// GetBrandByID mocks base method.
func (m *MockQuerier) GetBrandByID(ctx context.Context, brandID int64) (sqlc.InventoryBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBrandByID", ctx, brandID)
	ret0, _ := ret[0].(sqlc.InventoryBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBrandByID indicates an expected call of GetBrandByID.
func (mr *MockQuerierMockRecorder) GetBrandByID(ctx, brandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBrandByID", reflect.TypeOf((*MockQuerier)(nil).GetBrandByID), ctx, brandID)
}

// GetBrandsByIDs mocks base method.
func (m *MockQuerier) GetBrandsByIDs(ctx context.Context, brandIds []int64) ([]sqlc.InventoryBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBrandsByIDs", ctx, brandIds)
	ret0, _ := ret[0].([]sqlc.InventoryBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBrandsByIDs indicates an expected call of GetBrandsByIDs.
func (mr *MockQuerierMockRecorder) GetBrandsByIDs(ctx, brandIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBrandsByIDs", reflect.TypeOf((*MockQuerier)(nil).GetBrandsByIDs), ctx, brandIds)
}

// GetCategoriesByIDs mocks base method.
func (m *MockQuerier) GetCategoriesByIDs(ctx context.Context, categoryIds []int64) ([]sqlc.InventoryCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoriesByIDs", ctx, categoryIds)
	ret0, _ := ret[0].([]sqlc.InventoryCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoriesByIDs indicates an expected call of GetCategoriesByIDs.
func (mr *MockQuerierMockRecorder) GetCategoriesByIDs(ctx, categoryIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoriesByIDs", reflect.TypeOf((*MockQuerier)(nil).GetCategoriesByIDs), ctx, categoryIds)
}

// GetCategoryByID mocks base method.
func (m *MockQuerier) GetCategoryByID(ctx context.Context, categoryID int64) (sqlc.InventoryCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryByID", ctx, categoryID)
	ret0, _ := ret[0].(sqlc.InventoryCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryByID indicates an expected call of GetCategoryByID.
func (mr *MockQuerierMockRecorder) GetCategoryByID(ctx, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryByID", reflect.TypeOf((*MockQuerier)(nil).GetCategoryByID), ctx, categoryID)
}

// GetFlavorProfileByID mocks base method.
func (m *MockQuerier) GetFlavorProfileByID(ctx context.Context, flavorID int64) (sqlc.InventoryFlavorProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlavorProfileByID", ctx, flavorID)
	ret0, _ := ret[0].(sqlc.InventoryFlavorProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlavorProfileByID indicates an expected call of GetFlavorProfileByID.
func (mr *MockQuerierMockRecorder) GetFlavorProfileByID(ctx, flavorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlavorProfileByID", reflect.TypeOf((*MockQuerier)(nil).GetFlavorProfileByID), ctx, flavorID)
}

// GetIngredientByID mocks base method.
func (m *MockQuerier) GetIngredientByID(ctx context.Context, ingredientID int64) (sqlc.InventoryIngredient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIngredientByID", ctx, ingredientID)
	ret0, _ := ret[0].(sqlc.InventoryIngredient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIngredientByID indicates an expected call of GetIngredientByID.
func (mr *MockQuerierMockRecorder) GetIngredientByID(ctx, ingredientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIngredientByID", reflect.TypeOf((*MockQuerier)(nil).GetIngredientByID), ctx, ingredientID)
}

// GetIngredientsByIDs mocks base method.
func (m *MockQuerier) GetIngredientsByIDs(ctx context.Context, ingredientIds []int64) ([]sqlc.InventoryIngredient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIngredientsByIDs", ctx, ingredientIds)
	ret0, _ := ret[0].([]sqlc.InventoryIngredient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIngredientsByIDs indicates an expected call of GetIngredientsByIDs.
func (mr *MockQuerierMockRecorder) GetIngredientsByIDs(ctx, ingredientIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIngredientsByIDs", reflect.TypeOf((*MockQuerier)(nil).GetIngredientsByIDs), ctx, ingredientIds)
}

// GetItemByID mocks base method.
func (m *MockQuerier) GetItemByID(ctx context.Context, itemID int64) (sqlc.InventoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemByID", ctx, itemID)
	ret0, _ := ret[0].(sqlc.InventoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemByID indicates an expected call of GetItemByID.
func (mr *MockQuerierMockRecorder) GetItemByID(ctx, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByID", reflect.TypeOf((*MockQuerier)(nil).GetItemByID), ctx, itemID)
}

// GetItemByUpc mocks base method.
func (m *MockQuerier) GetItemByUpc(ctx context.Context, arg sqlc.GetItemByUpcParams) (sqlc.InventoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemByUpc", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemByUpc indicates an expected call of GetItemByUpc.
func (mr *MockQuerierMockRecorder) GetItemByUpc(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByUpc", reflect.TypeOf((*MockQuerier)(nil).GetItemByUpc), ctx, arg)
}

// GetItemIngredient mocks base method.
func (m *MockQuerier) GetItemIngredient(ctx context.Context, arg sqlc.GetItemIngredientParams) (sqlc.GetItemIngredientRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemIngredient", ctx, arg)
	ret0, _ := ret[0].(sqlc.GetItemIngredientRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemIngredient indicates an expected call of GetItemIngredient.
func (mr *MockQuerierMockRecorder) GetItemIngredient(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemIngredient", reflect.TypeOf((*MockQuerier)(nil).GetItemIngredient), ctx, arg)
}

// GetItemIngredientsForItems mocks base method.
func (m *MockQuerier) GetItemIngredientsForItems(ctx context.Context, arg sqlc.GetItemIngredientsForItemsParams) ([]sqlc.GetItemIngredientsForItemsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemIngredientsForItems", ctx, arg)
	ret0, _ := ret[0].([]sqlc.GetItemIngredientsForItemsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemIngredientsForItems indicates an expected call of GetItemIngredientsForItems.
func (mr *MockQuerierMockRecorder) GetItemIngredientsForItems(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemIngredientsForItems", reflect.TypeOf((*MockQuerier)(nil).GetItemIngredientsForItems), ctx, arg)
}

// GetItemsByIDs mocks base method.
func (m *MockQuerier) GetItemsByIDs(ctx context.Context, itemIds []int64) ([]sqlc.InventoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemsByIDs", ctx, itemIds)
	ret0, _ := ret[0].([]sqlc.InventoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemsByIDs indicates an expected call of GetItemsByIDs.
func (mr *MockQuerierMockRecorder) GetItemsByIDs(ctx, itemIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemsByIDs", reflect.TypeOf((*MockQuerier)(nil).GetItemsByIDs), ctx, itemIds)
}

// GetNutrientTypeByID mocks base method.
func (m *MockQuerier) GetNutrientTypeByID(ctx context.Context, nutrientID int64) (sqlc.InventoryNutrientType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNutrientTypeByID", ctx, nutrientID)
	ret0, _ := ret[0].(sqlc.InventoryNutrientType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNutrientTypeByID indicates an expected call of GetNutrientTypeByID.
func (mr *MockQuerierMockRecorder) GetNutrientTypeByID(ctx, nutrientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNutrientTypeByID", reflect.TypeOf((*MockQuerier)(nil).GetNutrientTypeByID), ctx, nutrientID)
}

// GetNutrientTypeByName mocks base method.
func (m *MockQuerier) GetNutrientTypeByName(ctx context.Context, lower string) (sqlc.InventoryNutrientType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNutrientTypeByName", ctx, lower)
	ret0, _ := ret[0].(sqlc.InventoryNutrientType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNutrientTypeByName indicates an expected call of GetNutrientTypeByName.
func (mr *MockQuerierMockRecorder) GetNutrientTypeByName(ctx, lower any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNutrientTypeByName", reflect.TypeOf((*MockQuerier)(nil).GetNutrientTypeByName), ctx, lower)
}

// GetUnitByID mocks base method.
func (m *MockQuerier) GetUnitByID(ctx context.Context, unitID int64) (sqlc.InventoryUnit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnitByID", ctx, unitID)
	ret0, _ := ret[0].(sqlc.InventoryUnit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnitByID indicates an expected call of GetUnitByID.
func (mr *MockQuerierMockRecorder) GetUnitByID(ctx, unitID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnitByID", reflect.TypeOf((*MockQuerier)(nil).GetUnitByID), ctx, unitID)
}

// GetUnitByName mocks base method.
func (m *MockQuerier) GetUnitByName(ctx context.Context, lower string) (sqlc.InventoryUnit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnitByName", ctx, lower)
	ret0, _ := ret[0].(sqlc.InventoryUnit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnitByName indicates an expected call of GetUnitByName.
func (mr *MockQuerierMockRecorder) GetUnitByName(ctx, lower any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnitByName", reflect.TypeOf((*MockQuerier)(nil).GetUnitByName), ctx, lower)
}

// GetUnitsByIDs mocks base method.
func (m *MockQuerier) GetUnitsByIDs(ctx context.Context, unitIds []int64) ([]sqlc.InventoryUnit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnitsByIDs", ctx, unitIds)
	ret0, _ := ret[0].([]sqlc.InventoryUnit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnitsByIDs indicates an expected call of GetUnitsByIDs.
func (mr *MockQuerierMockRecorder) GetUnitsByIDs(ctx, unitIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnitsByIDs", reflect.TypeOf((*MockQuerier)(nil).GetUnitsByIDs), ctx, unitIds)
}

// GetUsualItemForIngredient mocks base method.
func (m *MockQuerier) GetUsualItemForIngredient(ctx context.Context, arg sqlc.GetUsualItemForIngredientParams) (sqlc.UserprefsHouseholdIngredientItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsualItemForIngredient", ctx, arg)
	ret0, _ := ret[0].(sqlc.UserprefsHouseholdIngredientItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsualItemForIngredient indicates an expected call of GetUsualItemForIngredient.
func (mr *MockQuerierMockRecorder) GetUsualItemForIngredient(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsualItemForIngredient", reflect.TypeOf((*MockQuerier)(nil).GetUsualItemForIngredient), ctx, arg)
}

// ListAllergenSuggestions mocks base method.
func (m *MockQuerier) ListAllergenSuggestions(ctx context.Context, status pgtype.Text) ([]sqlc.ListAllergenSuggestionsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllergenSuggestions", ctx, status)
	ret0, _ := ret[0].([]sqlc.ListAllergenSuggestionsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllergenSuggestions indicates an expected call of ListAllergenSuggestions.
func (mr *MockQuerierMockRecorder) ListAllergenSuggestions(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllergenSuggestions", reflect.TypeOf((*MockQuerier)(nil).ListAllergenSuggestions), ctx, status)
}

// ListAllergens mocks base method.
func (m *MockQuerier) ListAllergens(ctx context.Context) ([]sqlc.InventoryAllergen, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllergens", ctx)
	ret0, _ := ret[0].([]sqlc.InventoryAllergen)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllergens indicates an expected call of ListAllergens.
func (mr *MockQuerierMockRecorder) ListAllergens(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllergens", reflect.TypeOf((*MockQuerier)(nil).ListAllergens), ctx)
}

// ListBrands mocks base method.
func (m *MockQuerier) ListBrands(ctx context.Context) ([]sqlc.InventoryBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBrands", ctx)
	ret0, _ := ret[0].([]sqlc.InventoryBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBrands indicates an expected call of ListBrands.
func (mr *MockQuerierMockRecorder) ListBrands(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBrands", reflect.TypeOf((*MockQuerier)(nil).ListBrands), ctx)
}

// ListBrandsVisible mocks base method.
func (m *MockQuerier) ListBrandsVisible(ctx context.Context, arg sqlc.ListBrandsVisibleParams) ([]sqlc.InventoryBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBrandsVisible", ctx, arg)
	ret0, _ := ret[0].([]sqlc.InventoryBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBrandsVisible indicates an expected call of ListBrandsVisible.
func (mr *MockQuerierMockRecorder) ListBrandsVisible(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBrandsVisible", reflect.TypeOf((*MockQuerier)(nil).ListBrandsVisible), ctx, arg)
}

// ListCategories mocks base method.
func (m *MockQuerier) ListCategories(ctx context.Context) ([]sqlc.InventoryCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", ctx)
	ret0, _ := ret[0].([]sqlc.InventoryCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockQuerierMockRecorder) ListCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockQuerier)(nil).ListCategories), ctx)
}

// ListFlavorProfiles mocks base method.
func (m *MockQuerier) ListFlavorProfiles(ctx context.Context) ([]sqlc.InventoryFlavorProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFlavorProfiles", ctx)
	ret0, _ := ret[0].([]sqlc.InventoryFlavorProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFlavorProfiles indicates an expected call of ListFlavorProfiles.
func (mr *MockQuerierMockRecorder) ListFlavorProfiles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFlavorProfiles", reflect.TypeOf((*MockQuerier)(nil).ListFlavorProfiles), ctx)
}

// ListFoodFlavorsByItem mocks base method.
func (m *MockQuerier) ListFoodFlavorsByItem(ctx context.Context, foodID int64) ([]sqlc.ListFoodFlavorsByItemRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFoodFlavorsByItem", ctx, foodID)
	ret0, _ := ret[0].([]sqlc.ListFoodFlavorsByItemRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFoodFlavorsByItem indicates an expected call of ListFoodFlavorsByItem.
func (mr *MockQuerierMockRecorder) ListFoodFlavorsByItem(ctx, foodID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFoodFlavorsByItem", reflect.TypeOf((*MockQuerier)(nil).ListFoodFlavorsByItem), ctx, foodID)
}

// ListFoodFlavorsByItems mocks base method.
func (m *MockQuerier) ListFoodFlavorsByItems(ctx context.Context, itemIds []int64) ([]sqlc.ListFoodFlavorsByItemsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFoodFlavorsByItems", ctx, itemIds)
	ret0, _ := ret[0].([]sqlc.ListFoodFlavorsByItemsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFoodFlavorsByItems indicates an expected call of ListFoodFlavorsByItems.
func (mr *MockQuerierMockRecorder) ListFoodFlavorsByItems(ctx, itemIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFoodFlavorsByItems", reflect.TypeOf((*MockQuerier)(nil).ListFoodFlavorsByItems), ctx, itemIds)
}

// ListFoodNutrientsByItem mocks base method.
func (m *MockQuerier) ListFoodNutrientsByItem(ctx context.Context, foodID int64) ([]sqlc.ListFoodNutrientsByItemRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFoodNutrientsByItem", ctx, foodID)
	ret0, _ := ret[0].([]sqlc.ListFoodNutrientsByItemRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFoodNutrientsByItem indicates an expected call of ListFoodNutrientsByItem.
func (mr *MockQuerierMockRecorder) ListFoodNutrientsByItem(ctx, foodID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFoodNutrientsByItem", reflect.TypeOf((*MockQuerier)(nil).ListFoodNutrientsByItem), ctx, foodID)
}

// ListFoodNutrientsByItems mocks base method.
func (m *MockQuerier) ListFoodNutrientsByItems(ctx context.Context, itemIds []int64) ([]sqlc.ListFoodNutrientsByItemsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFoodNutrientsByItems", ctx, itemIds)
	ret0, _ := ret[0].([]sqlc.ListFoodNutrientsByItemsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFoodNutrientsByItems indicates an expected call of ListFoodNutrientsByItems.
func (mr *MockQuerierMockRecorder) ListFoodNutrientsByItems(ctx, itemIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFoodNutrientsByItems", reflect.TypeOf((*MockQuerier)(nil).ListFoodNutrientsByItems), ctx, itemIds)
}

// ListIngredientAllergens mocks base method.
func (m *MockQuerier) ListIngredientAllergens(ctx context.Context, ingredientID int64) ([]sqlc.InventoryIngredientAllergen, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIngredientAllergens", ctx, ingredientID)
	ret0, _ := ret[0].([]sqlc.InventoryIngredientAllergen)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIngredientAllergens indicates an expected call of ListIngredientAllergens.
func (mr *MockQuerierMockRecorder) ListIngredientAllergens(ctx, ingredientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIngredientAllergens", reflect.TypeOf((*MockQuerier)(nil).ListIngredientAllergens), ctx, ingredientID)
}

// ListIngredientAllergensByIngredients mocks base method.
func (m *MockQuerier) ListIngredientAllergensByIngredients(ctx context.Context, ingredientIds []int64) ([]sqlc.InventoryIngredientAllergen, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIngredientAllergensByIngredients", ctx, ingredientIds)
	ret0, _ := ret[0].([]sqlc.InventoryIngredientAllergen)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIngredientAllergensByIngredients indicates an expected call of ListIngredientAllergensByIngredients.
func (mr *MockQuerierMockRecorder) ListIngredientAllergensByIngredients(ctx, ingredientIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIngredientAllergensByIngredients", reflect.TypeOf((*MockQuerier)(nil).ListIngredientAllergensByIngredients), ctx, ingredientIds)
}

// ListIngredients mocks base method.
func (m *MockQuerier) ListIngredients(ctx context.Context, arg sqlc.ListIngredientsParams) ([]sqlc.InventoryIngredient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIngredients", ctx, arg)
	ret0, _ := ret[0].([]sqlc.InventoryIngredient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIngredients indicates an expected call of ListIngredients.
func (mr *MockQuerierMockRecorder) ListIngredients(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIngredients", reflect.TypeOf((*MockQuerier)(nil).ListIngredients), ctx, arg)
}

// ListItemAllergens mocks base method.
func (m *MockQuerier) ListItemAllergens(ctx context.Context, itemID int64) ([]sqlc.InventoryItemAllergen, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItemAllergens", ctx, itemID)
	ret0, _ := ret[0].([]sqlc.InventoryItemAllergen)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItemAllergens indicates an expected call of ListItemAllergens.
func (mr *MockQuerierMockRecorder) ListItemAllergens(ctx, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItemAllergens", reflect.TypeOf((*MockQuerier)(nil).ListItemAllergens), ctx, itemID)
}

// ListItemAllergensByItems mocks base method.
func (m *MockQuerier) ListItemAllergensByItems(ctx context.Context, itemIds []int64) ([]sqlc.InventoryItemAllergen, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItemAllergensByItems", ctx, itemIds)
	ret0, _ := ret[0].([]sqlc.InventoryItemAllergen)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItemAllergensByItems indicates an expected call of ListItemAllergensByItems.
func (mr *MockQuerierMockRecorder) ListItemAllergensByItems(ctx, itemIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItemAllergensByItems", reflect.TypeOf((*MockQuerier)(nil).ListItemAllergensByItems), ctx, itemIds)
}

// ListItems mocks base method.
func (m *MockQuerier) ListItems(ctx context.Context, arg sqlc.ListItemsParams) ([]sqlc.InventoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItems", ctx, arg)
	ret0, _ := ret[0].([]sqlc.InventoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItems indicates an expected call of ListItems.
func (mr *MockQuerierMockRecorder) ListItems(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItems", reflect.TypeOf((*MockQuerier)(nil).ListItems), ctx, arg)
}

// ListItemsForIngredient mocks base method.
func (m *MockQuerier) ListItemsForIngredient(ctx context.Context, arg sqlc.ListItemsForIngredientParams) ([]sqlc.InventoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItemsForIngredient", ctx, arg)
	ret0, _ := ret[0].([]sqlc.InventoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItemsForIngredient indicates an expected call of ListItemsForIngredient.
func (mr *MockQuerierMockRecorder) ListItemsForIngredient(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItemsForIngredient", reflect.TypeOf((*MockQuerier)(nil).ListItemsForIngredient), ctx, arg)
}

// ListNutrientTypes mocks base method.
func (m *MockQuerier) ListNutrientTypes(ctx context.Context) ([]sqlc.InventoryNutrientType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNutrientTypes", ctx)
	ret0, _ := ret[0].([]sqlc.InventoryNutrientType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNutrientTypes indicates an expected call of ListNutrientTypes.
func (mr *MockQuerierMockRecorder) ListNutrientTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNutrientTypes", reflect.TypeOf((*MockQuerier)(nil).ListNutrientTypes), ctx)
}

// ListPendingBrands mocks base method.
func (m *MockQuerier) ListPendingBrands(ctx context.Context, arg sqlc.ListPendingBrandsParams) ([]sqlc.InventoryBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingBrands", ctx, arg)
	ret0, _ := ret[0].([]sqlc.InventoryBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingBrands indicates an expected call of ListPendingBrands.
func (mr *MockQuerierMockRecorder) ListPendingBrands(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingBrands", reflect.TypeOf((*MockQuerier)(nil).ListPendingBrands), ctx, arg)
}

// ListPendingItems mocks base method.
func (m *MockQuerier) ListPendingItems(ctx context.Context, arg sqlc.ListPendingItemsParams) ([]sqlc.InventoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingItems", ctx, arg)
	ret0, _ := ret[0].([]sqlc.InventoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingItems indicates an expected call of ListPendingItems.
func (mr *MockQuerierMockRecorder) ListPendingItems(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingItems", reflect.TypeOf((*MockQuerier)(nil).ListPendingItems), ctx, arg)
}

// ListUnits mocks base method.
func (m *MockQuerier) ListUnits(ctx context.Context) ([]sqlc.InventoryUnit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnits", ctx)
	ret0, _ := ret[0].([]sqlc.InventoryUnit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnits indicates an expected call of ListUnits.
func (mr *MockQuerierMockRecorder) ListUnits(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnits", reflect.TypeOf((*MockQuerier)(nil).ListUnits), ctx)
}

// ListUsualItemsForIngredients mocks base method.
func (m *MockQuerier) ListUsualItemsForIngredients(ctx context.Context, arg sqlc.ListUsualItemsForIngredientsParams) ([]sqlc.UserprefsHouseholdIngredientItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsualItemsForIngredients", ctx, arg)
	ret0, _ := ret[0].([]sqlc.UserprefsHouseholdIngredientItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsualItemsForIngredients indicates an expected call of ListUsualItemsForIngredients.
func (mr *MockQuerierMockRecorder) ListUsualItemsForIngredients(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsualItemsForIngredients", reflect.TypeOf((*MockQuerier)(nil).ListUsualItemsForIngredients), ctx, arg)
}

// MatchItemIDs mocks base method.
func (m *MockQuerier) MatchItemIDs(ctx context.Context, arg sqlc.MatchItemIDsParams) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchItemIDs", ctx, arg)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MatchItemIDs indicates an expected call of MatchItemIDs.
func (mr *MockQuerierMockRecorder) MatchItemIDs(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchItemIDs", reflect.TypeOf((*MockQuerier)(nil).MatchItemIDs), ctx, arg)
}

// MatchItemIDsByTerms mocks base method.
func (m *MockQuerier) MatchItemIDsByTerms(ctx context.Context, arg sqlc.MatchItemIDsByTermsParams) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchItemIDsByTerms", ctx, arg)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MatchItemIDsByTerms indicates an expected call of MatchItemIDsByTerms.
func (mr *MockQuerierMockRecorder) MatchItemIDsByTerms(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchItemIDsByTerms", reflect.TypeOf((*MockQuerier)(nil).MatchItemIDsByTerms), ctx, arg)
}

// MergeIngredientRefsAisle mocks base method.
func (m *MockQuerier) MergeIngredientRefsAisle(ctx context.Context, arg sqlc.MergeIngredientRefsAisleParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeIngredientRefsAisle", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeIngredientRefsAisle indicates an expected call of MergeIngredientRefsAisle.
func (mr *MockQuerierMockRecorder) MergeIngredientRefsAisle(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeIngredientRefsAisle", reflect.TypeOf((*MockQuerier)(nil).MergeIngredientRefsAisle), ctx, arg)
}

// MergeIngredientRefsEventRecipeItem mocks base method.
func (m *MockQuerier) MergeIngredientRefsEventRecipeItem(ctx context.Context, arg sqlc.MergeIngredientRefsEventRecipeItemParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeIngredientRefsEventRecipeItem", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeIngredientRefsEventRecipeItem indicates an expected call of MergeIngredientRefsEventRecipeItem.
func (mr *MockQuerierMockRecorder) MergeIngredientRefsEventRecipeItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeIngredientRefsEventRecipeItem", reflect.TypeOf((*MockQuerier)(nil).MergeIngredientRefsEventRecipeItem), ctx, arg)
}

// MergeIngredientRefsGroceryLine mocks base method.
func (m *MockQuerier) MergeIngredientRefsGroceryLine(ctx context.Context, arg sqlc.MergeIngredientRefsGroceryLineParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeIngredientRefsGroceryLine", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeIngredientRefsGroceryLine indicates an expected call of MergeIngredientRefsGroceryLine.
func (mr *MockQuerierMockRecorder) MergeIngredientRefsGroceryLine(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeIngredientRefsGroceryLine", reflect.TypeOf((*MockQuerier)(nil).MergeIngredientRefsGroceryLine), ctx, arg)
}

// MergeIngredientRefsItem mocks base method.
func (m *MockQuerier) MergeIngredientRefsItem(ctx context.Context, arg sqlc.MergeIngredientRefsItemParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeIngredientRefsItem", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeIngredientRefsItem indicates an expected call of MergeIngredientRefsItem.
func (mr *MockQuerierMockRecorder) MergeIngredientRefsItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeIngredientRefsItem", reflect.TypeOf((*MockQuerier)(nil).MergeIngredientRefsItem), ctx, arg)
}

// MergeIngredientRefsMealSlot mocks base method.
func (m *MockQuerier) MergeIngredientRefsMealSlot(ctx context.Context, arg sqlc.MergeIngredientRefsMealSlotParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeIngredientRefsMealSlot", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeIngredientRefsMealSlot indicates an expected call of MergeIngredientRefsMealSlot.
func (mr *MockQuerierMockRecorder) MergeIngredientRefsMealSlot(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeIngredientRefsMealSlot", reflect.TypeOf((*MockQuerier)(nil).MergeIngredientRefsMealSlot), ctx, arg)
}

// MergeIngredientRefsOverride mocks base method.
func (m *MockQuerier) MergeIngredientRefsOverride(ctx context.Context, arg sqlc.MergeIngredientRefsOverrideParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeIngredientRefsOverride", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeIngredientRefsOverride indicates an expected call of MergeIngredientRefsOverride.
func (mr *MockQuerierMockRecorder) MergeIngredientRefsOverride(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeIngredientRefsOverride", reflect.TypeOf((*MockQuerier)(nil).MergeIngredientRefsOverride), ctx, arg)
}

// MergeIngredientRefsRecipeItem mocks base method.
func (m *MockQuerier) MergeIngredientRefsRecipeItem(ctx context.Context, arg sqlc.MergeIngredientRefsRecipeItemParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeIngredientRefsRecipeItem", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeIngredientRefsRecipeItem indicates an expected call of MergeIngredientRefsRecipeItem.
func (mr *MockQuerierMockRecorder) MergeIngredientRefsRecipeItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeIngredientRefsRecipeItem", reflect.TypeOf((*MockQuerier)(nil).MergeIngredientRefsRecipeItem), ctx, arg)
}

// MergeIngredientRefsRoute mocks base method.
func (m *MockQuerier) MergeIngredientRefsRoute(ctx context.Context, arg sqlc.MergeIngredientRefsRouteParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeIngredientRefsRoute", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeIngredientRefsRoute indicates an expected call of MergeIngredientRefsRoute.
func (mr *MockQuerierMockRecorder) MergeIngredientRefsRoute(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeIngredientRefsRoute", reflect.TypeOf((*MockQuerier)(nil).MergeIngredientRefsRoute), ctx, arg)
}

// MergeIngredientRefsUsual mocks base method.
func (m *MockQuerier) MergeIngredientRefsUsual(ctx context.Context, arg sqlc.MergeIngredientRefsUsualParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeIngredientRefsUsual", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeIngredientRefsUsual indicates an expected call of MergeIngredientRefsUsual.
func (mr *MockQuerierMockRecorder) MergeIngredientRefsUsual(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeIngredientRefsUsual", reflect.TypeOf((*MockQuerier)(nil).MergeIngredientRefsUsual), ctx, arg)
}

// RankedItems mocks base method.
func (m *MockQuerier) RankedItems(ctx context.Context, arg sqlc.RankedItemsParams) ([]sqlc.InventoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RankedItems", ctx, arg)
	ret0, _ := ret[0].([]sqlc.InventoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RankedItems indicates an expected call of RankedItems.
func (mr *MockQuerierMockRecorder) RankedItems(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RankedItems", reflect.TypeOf((*MockQuerier)(nil).RankedItems), ctx, arg)
}

// SearchBrands mocks base method.
func (m *MockQuerier) SearchBrands(ctx context.Context, arg sqlc.SearchBrandsParams) ([]sqlc.InventoryBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchBrands", ctx, arg)
	ret0, _ := ret[0].([]sqlc.InventoryBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchBrands indicates an expected call of SearchBrands.
func (mr *MockQuerierMockRecorder) SearchBrands(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchBrands", reflect.TypeOf((*MockQuerier)(nil).SearchBrands), ctx, arg)
}

// SearchIngredients mocks base method.
func (m *MockQuerier) SearchIngredients(ctx context.Context, arg sqlc.SearchIngredientsParams) ([]sqlc.InventoryIngredient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchIngredients", ctx, arg)
	ret0, _ := ret[0].([]sqlc.InventoryIngredient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchIngredients indicates an expected call of SearchIngredients.
func (mr *MockQuerierMockRecorder) SearchIngredients(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchIngredients", reflect.TypeOf((*MockQuerier)(nil).SearchIngredients), ctx, arg)
}

// SearchItemsRemainder mocks base method.
func (m *MockQuerier) SearchItemsRemainder(ctx context.Context, arg sqlc.SearchItemsRemainderParams) ([]sqlc.InventoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchItemsRemainder", ctx, arg)
	ret0, _ := ret[0].([]sqlc.InventoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchItemsRemainder indicates an expected call of SearchItemsRemainder.
func (mr *MockQuerierMockRecorder) SearchItemsRemainder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchItemsRemainder", reflect.TypeOf((*MockQuerier)(nil).SearchItemsRemainder), ctx, arg)
}

// SetAllergenSuggestionStatus mocks base method.
func (m *MockQuerier) SetAllergenSuggestionStatus(ctx context.Context, arg sqlc.SetAllergenSuggestionStatusParams) (sqlc.InventoryAllergenSuggestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAllergenSuggestionStatus", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryAllergenSuggestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetAllergenSuggestionStatus indicates an expected call of SetAllergenSuggestionStatus.
func (mr *MockQuerierMockRecorder) SetAllergenSuggestionStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAllergenSuggestionStatus", reflect.TypeOf((*MockQuerier)(nil).SetAllergenSuggestionStatus), ctx, arg)
}

// SetBrandStatus mocks base method.
func (m *MockQuerier) SetBrandStatus(ctx context.Context, arg sqlc.SetBrandStatusParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBrandStatus", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetBrandStatus indicates an expected call of SetBrandStatus.
func (mr *MockQuerierMockRecorder) SetBrandStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBrandStatus", reflect.TypeOf((*MockQuerier)(nil).SetBrandStatus), ctx, arg)
}

// SetItemIngredient mocks base method.
func (m *MockQuerier) SetItemIngredient(ctx context.Context, arg sqlc.SetItemIngredientParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetItemIngredient", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetItemIngredient indicates an expected call of SetItemIngredient.
func (mr *MockQuerierMockRecorder) SetItemIngredient(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetItemIngredient", reflect.TypeOf((*MockQuerier)(nil).SetItemIngredient), ctx, arg)
}

// SetItemStatus mocks base method.
func (m *MockQuerier) SetItemStatus(ctx context.Context, arg sqlc.SetItemStatusParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetItemStatus", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetItemStatus indicates an expected call of SetItemStatus.
func (mr *MockQuerierMockRecorder) SetItemStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetItemStatus", reflect.TypeOf((*MockQuerier)(nil).SetItemStatus), ctx, arg)
}

// UpdateAllergen mocks base method.
func (m *MockQuerier) UpdateAllergen(ctx context.Context, arg sqlc.UpdateAllergenParams) (sqlc.InventoryAllergen, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAllergen", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryAllergen)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAllergen indicates an expected call of UpdateAllergen.
func (mr *MockQuerierMockRecorder) UpdateAllergen(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAllergen", reflect.TypeOf((*MockQuerier)(nil).UpdateAllergen), ctx, arg)
}

// UpdateBrand mocks base method.
func (m *MockQuerier) UpdateBrand(ctx context.Context, arg sqlc.UpdateBrandParams) (sqlc.InventoryBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBrand", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBrand indicates an expected call of UpdateBrand.
func (mr *MockQuerierMockRecorder) UpdateBrand(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBrand", reflect.TypeOf((*MockQuerier)(nil).UpdateBrand), ctx, arg)
}

// UpdateCategory mocks base method.
func (m *MockQuerier) UpdateCategory(ctx context.Context, arg sqlc.UpdateCategoryParams) (sqlc.InventoryCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockQuerierMockRecorder) UpdateCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockQuerier)(nil).UpdateCategory), ctx, arg)
}

// UpdateFlavorProfile mocks base method.
func (m *MockQuerier) UpdateFlavorProfile(ctx context.Context, arg sqlc.UpdateFlavorProfileParams) (sqlc.InventoryFlavorProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFlavorProfile", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryFlavorProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFlavorProfile indicates an expected call of UpdateFlavorProfile.
func (mr *MockQuerierMockRecorder) UpdateFlavorProfile(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFlavorProfile", reflect.TypeOf((*MockQuerier)(nil).UpdateFlavorProfile), ctx, arg)
}

// UpdateIngredient mocks base method.
func (m *MockQuerier) UpdateIngredient(ctx context.Context, arg sqlc.UpdateIngredientParams) (sqlc.InventoryIngredient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIngredient", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryIngredient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateIngredient indicates an expected call of UpdateIngredient.
func (mr *MockQuerierMockRecorder) UpdateIngredient(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIngredient", reflect.TypeOf((*MockQuerier)(nil).UpdateIngredient), ctx, arg)
}

// UpdateItem mocks base method.
func (m *MockQuerier) UpdateItem(ctx context.Context, arg sqlc.UpdateItemParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockQuerierMockRecorder) UpdateItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockQuerier)(nil).UpdateItem), ctx, arg)
}

// UpdateNutrientType mocks base method.
func (m *MockQuerier) UpdateNutrientType(ctx context.Context, arg sqlc.UpdateNutrientTypeParams) (sqlc.InventoryNutrientType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNutrientType", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryNutrientType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNutrientType indicates an expected call of UpdateNutrientType.
func (mr *MockQuerierMockRecorder) UpdateNutrientType(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNutrientType", reflect.TypeOf((*MockQuerier)(nil).UpdateNutrientType), ctx, arg)
}

// UpsertBrand mocks base method.
func (m *MockQuerier) UpsertBrand(ctx context.Context, arg sqlc.UpsertBrandParams) (sqlc.InventoryBrand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertBrand", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryBrand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertBrand indicates an expected call of UpsertBrand.
func (mr *MockQuerierMockRecorder) UpsertBrand(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertBrand", reflect.TypeOf((*MockQuerier)(nil).UpsertBrand), ctx, arg)
}

// UpsertIngredientAllergen mocks base method.
func (m *MockQuerier) UpsertIngredientAllergen(ctx context.Context, arg sqlc.UpsertIngredientAllergenParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertIngredientAllergen", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertIngredientAllergen indicates an expected call of UpsertIngredientAllergen.
func (mr *MockQuerierMockRecorder) UpsertIngredientAllergen(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertIngredientAllergen", reflect.TypeOf((*MockQuerier)(nil).UpsertIngredientAllergen), ctx, arg)
}

// UpsertItemAllergen mocks base method.
func (m *MockQuerier) UpsertItemAllergen(ctx context.Context, arg sqlc.UpsertItemAllergenParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertItemAllergen", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertItemAllergen indicates an expected call of UpsertItemAllergen.
func (mr *MockQuerierMockRecorder) UpsertItemAllergen(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertItemAllergen", reflect.TypeOf((*MockQuerier)(nil).UpsertItemAllergen), ctx, arg)
}

// UpsertItemIngredientOverride mocks base method.
func (m *MockQuerier) UpsertItemIngredientOverride(ctx context.Context, arg sqlc.UpsertItemIngredientOverrideParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertItemIngredientOverride", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertItemIngredientOverride indicates an expected call of UpsertItemIngredientOverride.
func (mr *MockQuerierMockRecorder) UpsertItemIngredientOverride(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertItemIngredientOverride", reflect.TypeOf((*MockQuerier)(nil).UpsertItemIngredientOverride), ctx, arg)
}

// UpsertUsualItemForIngredient mocks base method.
func (m *MockQuerier) UpsertUsualItemForIngredient(ctx context.Context, arg sqlc.UpsertUsualItemForIngredientParams) (sqlc.UserprefsHouseholdIngredientItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUsualItemForIngredient", ctx, arg)
	ret0, _ := ret[0].(sqlc.UserprefsHouseholdIngredientItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUsualItemForIngredient indicates an expected call of UpsertUsualItemForIngredient.
func (mr *MockQuerierMockRecorder) UpsertUsualItemForIngredient(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUsualItemForIngredient", reflect.TypeOf((*MockQuerier)(nil).UpsertUsualItemForIngredient), ctx, arg)
}
