// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AddMealSlot(ctx context.Context, arg AddMealSlotParams) (MealplanMealSlot, error)
	AddMealSlotItem(ctx context.Context, arg AddMealSlotItemParams) (MealplanMealSlotItem, error)
	CountMealPlans(ctx context.Context, userID int64) (int64, error)
	CreateMealPlan(ctx context.Context, arg CreateMealPlanParams) (MealplanMealPlan, error)
	DeleteMealPlan(ctx context.Context, arg DeleteMealPlanParams) error
	DeleteMealSlot(ctx context.Context, arg DeleteMealSlotParams) error
	DeleteMealSlotItem(ctx context.Context, arg DeleteMealSlotItemParams) error
	GetMealPlanByID(ctx context.Context, arg GetMealPlanByIDParams) (MealplanMealPlan, error)
	GetMealSlotByID(ctx context.Context, arg GetMealSlotByIDParams) (MealplanMealSlot, error)
	ListMealPlans(ctx context.Context, arg ListMealPlansParams) ([]MealplanMealPlan, error)
	ListMealSlotItems(ctx context.Context, arg ListMealSlotItemsParams) ([]MealplanMealSlotItem, error)
	ListMealSlotItemsByPlan(ctx context.Context, arg ListMealSlotItemsByPlanParams) ([]MealplanMealSlotItem, error)
	ListMealSlotItemsByPlans(ctx context.Context, arg ListMealSlotItemsByPlansParams) ([]MealplanMealSlotItem, error)
	ListMealSlotsByPlans(ctx context.Context, arg ListMealSlotsByPlansParams) ([]MealplanMealSlot, error)
	ListMealSlotsForPlan(ctx context.Context, arg ListMealSlotsForPlanParams) ([]MealplanMealSlot, error)
	UpdateMealPlan(ctx context.Context, arg UpdateMealPlanParams) error
	UpdateMealSlot(ctx context.Context, arg UpdateMealSlotParams) error
}

var _ Querier = (*Queries)(nil)
