// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMealSlot = `-- name: AddMealSlot :one
INSERT INTO mealplan.meal_slot (meal_plan_id, day_of_week, meal_type, recipe_id, servings, replacement_note, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING slot_id, meal_plan_id, day_of_week, meal_type, recipe_id, servings, replacement_note, created_by, created_at, updated_by, updated_at
`

type AddMealSlotParams struct {
	MealPlanID      int64       `json:"meal_plan_id"`
	DayOfWeek       int16       `json:"day_of_week"`
	MealType        string      `json:"meal_type"`
	RecipeID        pgtype.Int8 `json:"recipe_id"`
	Servings        pgtype.Int4 `json:"servings"`
	ReplacementNote pgtype.Text `json:"replacement_note"`
	CreatedBy       string      `json:"created_by"`
	UpdatedBy       pgtype.Text `json:"updated_by"`
}

func (q *Queries) AddMealSlot(ctx context.Context, arg AddMealSlotParams) (MealplanMealSlot, error) {
	row := q.db.QueryRow(ctx, addMealSlot,
		arg.MealPlanID,
		arg.DayOfWeek,
		arg.MealType,
		arg.RecipeID,
		arg.Servings,
		arg.ReplacementNote,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i MealplanMealSlot
	err := row.Scan(
		&i.SlotID,
		&i.MealPlanID,
		&i.DayOfWeek,
		&i.MealType,
		&i.RecipeID,
		&i.Servings,
		&i.ReplacementNote,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const addMealSlotItem = `-- name: AddMealSlotItem :one
INSERT INTO mealplan.meal_slot_item (slot_id, item_id, ingredient_id, quantity, unit_id, is_from_recipe, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING slot_item_id, slot_id, item_id, quantity, is_from_recipe, created_by, created_at, updated_by, updated_at, ingredient_id, unit_id
`

type AddMealSlotItemParams struct {
	SlotID       int64          `json:"slot_id"`
	ItemID       pgtype.Int8    `json:"item_id"`
	IngredientID pgtype.Int8    `json:"ingredient_id"`
	Quantity     pgtype.Numeric `json:"quantity"`
	UnitID       int64          `json:"unit_id"`
	IsFromRecipe bool           `json:"is_from_recipe"`
	CreatedBy    string         `json:"created_by"`
	UpdatedBy    pgtype.Text    `json:"updated_by"`
}

func (q *Queries) AddMealSlotItem(ctx context.Context, arg AddMealSlotItemParams) (MealplanMealSlotItem, error) {
	row := q.db.QueryRow(ctx, addMealSlotItem,
		arg.SlotID,
		arg.ItemID,
		arg.IngredientID,
		arg.Quantity,
		arg.UnitID,
		arg.IsFromRecipe,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i MealplanMealSlotItem
	err := row.Scan(
		&i.SlotItemID,
		&i.SlotID,
		&i.ItemID,
		&i.Quantity,
		&i.IsFromRecipe,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.IngredientID,
		&i.UnitID,
	)
	return i, err
}

const countMealPlans = `-- name: CountMealPlans :one
SELECT COUNT(*)
FROM mealplan.meal_plan
WHERE household_id = $1
`

func (q *Queries) CountMealPlans(ctx context.Context, householdID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMealPlans, householdID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMealPlan = `-- name: CreateMealPlan :one
INSERT INTO mealplan.meal_plan (household_id, name, week_start_date, week_start_day_of_week, is_active, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING meal_plan_id, name, week_start_date, week_start_day_of_week, is_active, created_by, created_at, updated_by, updated_at, household_id
`

type CreateMealPlanParams struct {
	HouseholdID        int64       `json:"household_id"`
	Name               string      `json:"name"`
	WeekStartDate      pgtype.Date `json:"week_start_date"`
	WeekStartDayOfWeek int16       `json:"week_start_day_of_week"`
	IsActive           bool        `json:"is_active"`
	CreatedBy          string      `json:"created_by"`
	UpdatedBy          pgtype.Text `json:"updated_by"`
}

func (q *Queries) CreateMealPlan(ctx context.Context, arg CreateMealPlanParams) (MealplanMealPlan, error) {
	row := q.db.QueryRow(ctx, createMealPlan,
		arg.HouseholdID,
		arg.Name,
		arg.WeekStartDate,
		arg.WeekStartDayOfWeek,
		arg.IsActive,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i MealplanMealPlan
	err := row.Scan(
		&i.MealPlanID,
		&i.Name,
		&i.WeekStartDate,
		&i.WeekStartDayOfWeek,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.HouseholdID,
	)
	return i, err
}

const deleteMealPlan = `-- name: DeleteMealPlan :exec
DELETE FROM mealplan.meal_plan
WHERE meal_plan_id = $1 AND household_id = $2
`

type DeleteMealPlanParams struct {
	MealPlanID  int64 `json:"meal_plan_id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) DeleteMealPlan(ctx context.Context, arg DeleteMealPlanParams) error {
	_, err := q.db.Exec(ctx, deleteMealPlan, arg.MealPlanID, arg.HouseholdID)
	return err
}

const deleteMealSlot = `-- name: DeleteMealSlot :exec
DELETE FROM mealplan.meal_slot ms
USING mealplan.meal_plan mp
WHERE ms.meal_plan_id = mp.meal_plan_id AND ms.slot_id = $1 AND mp.household_id = $2
`

type DeleteMealSlotParams struct {
	SlotID      int64 `json:"slot_id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) DeleteMealSlot(ctx context.Context, arg DeleteMealSlotParams) error {
	_, err := q.db.Exec(ctx, deleteMealSlot, arg.SlotID, arg.HouseholdID)
	return err
}

const deleteMealSlotItem = `-- name: DeleteMealSlotItem :exec
DELETE FROM mealplan.meal_slot_item msi
USING mealplan.meal_slot ms, mealplan.meal_plan mp
WHERE msi.slot_id = ms.slot_id AND ms.meal_plan_id = mp.meal_plan_id
  AND msi.slot_item_id = $1 AND mp.household_id = $2
`

type DeleteMealSlotItemParams struct {
	SlotItemID  int64 `json:"slot_item_id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) DeleteMealSlotItem(ctx context.Context, arg DeleteMealSlotItemParams) error {
	_, err := q.db.Exec(ctx, deleteMealSlotItem, arg.SlotItemID, arg.HouseholdID)
	return err
}

const getMealPlanByID = `-- name: GetMealPlanByID :one
SELECT meal_plan_id, name, week_start_date, week_start_day_of_week, is_active, created_by, created_at, updated_by, updated_at, household_id
FROM mealplan.meal_plan
WHERE meal_plan_id = $1 AND household_id = $2
`

type GetMealPlanByIDParams struct {
	MealPlanID  int64 `json:"meal_plan_id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) GetMealPlanByID(ctx context.Context, arg GetMealPlanByIDParams) (MealplanMealPlan, error) {
	row := q.db.QueryRow(ctx, getMealPlanByID, arg.MealPlanID, arg.HouseholdID)
	var i MealplanMealPlan
	err := row.Scan(
		&i.MealPlanID,
		&i.Name,
		&i.WeekStartDate,
		&i.WeekStartDayOfWeek,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.HouseholdID,
	)
	return i, err
}

const getMealSlotByID = `-- name: GetMealSlotByID :one
SELECT ms.slot_id, ms.meal_plan_id, ms.day_of_week, ms.meal_type, ms.recipe_id, ms.servings, ms.replacement_note, ms.created_by, ms.created_at, ms.updated_by, ms.updated_at
FROM mealplan.meal_slot ms
JOIN mealplan.meal_plan mp ON ms.meal_plan_id = mp.meal_plan_id
WHERE ms.slot_id = $1 AND mp.household_id = $2
`

type GetMealSlotByIDParams struct {
	SlotID      int64 `json:"slot_id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) GetMealSlotByID(ctx context.Context, arg GetMealSlotByIDParams) (MealplanMealSlot, error) {
	row := q.db.QueryRow(ctx, getMealSlotByID, arg.SlotID, arg.HouseholdID)
	var i MealplanMealSlot
	err := row.Scan(
		&i.SlotID,
		&i.MealPlanID,
		&i.DayOfWeek,
		&i.MealType,
		&i.RecipeID,
		&i.Servings,
		&i.ReplacementNote,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listLastPlannedDates = `-- name: ListLastPlannedDates :many
SELECT ms.recipe_id, MAX(mp.week_start_date)::date AS last_planned
FROM mealplan.meal_slot ms
JOIN mealplan.meal_plan mp ON mp.meal_plan_id = ms.meal_plan_id
WHERE mp.household_id = $1 AND ms.recipe_id = ANY($2::bigint[])
GROUP BY ms.recipe_id
`

type ListLastPlannedDatesParams struct {
	HouseholdID int64   `json:"household_id"`
	RecipeIds   []int64 `json:"recipe_ids"`
}

type ListLastPlannedDatesRow struct {
	RecipeID    pgtype.Int8 `json:"recipe_id"`
	LastPlanned pgtype.Date `json:"last_planned"`
}

// For one household: the most recent plan week in which each recipe
// appeared. The BFF combines this with recipe ratings for recency scoring.
func (q *Queries) ListLastPlannedDates(ctx context.Context, arg ListLastPlannedDatesParams) ([]ListLastPlannedDatesRow, error) {
	rows, err := q.db.Query(ctx, listLastPlannedDates, arg.HouseholdID, arg.RecipeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLastPlannedDatesRow{}
	for rows.Next() {
		var i ListLastPlannedDatesRow
		if err := rows.Scan(&i.RecipeID, &i.LastPlanned); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealPlans = `-- name: ListMealPlans :many
SELECT meal_plan_id, name, week_start_date, week_start_day_of_week, is_active, created_by, created_at, updated_by, updated_at, household_id
FROM mealplan.meal_plan
WHERE household_id = $1
ORDER BY week_start_date DESC
LIMIT $2 OFFSET $3
`

type ListMealPlansParams struct {
	HouseholdID int64 `json:"household_id"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

func (q *Queries) ListMealPlans(ctx context.Context, arg ListMealPlansParams) ([]MealplanMealPlan, error) {
	rows, err := q.db.Query(ctx, listMealPlans, arg.HouseholdID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealplanMealPlan{}
	for rows.Next() {
		var i MealplanMealPlan
		if err := rows.Scan(
			&i.MealPlanID,
			&i.Name,
			&i.WeekStartDate,
			&i.WeekStartDayOfWeek,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.HouseholdID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealSlotItems = `-- name: ListMealSlotItems :many
SELECT msi.slot_item_id, msi.slot_id, msi.item_id, msi.quantity, msi.is_from_recipe, msi.created_by, msi.created_at, msi.updated_by, msi.updated_at, msi.ingredient_id, msi.unit_id
FROM mealplan.meal_slot_item msi
JOIN mealplan.meal_slot ms ON msi.slot_id = ms.slot_id
JOIN mealplan.meal_plan mp ON ms.meal_plan_id = mp.meal_plan_id
WHERE msi.slot_id = $1 AND mp.household_id = $2
ORDER BY msi.slot_item_id
`

type ListMealSlotItemsParams struct {
	SlotID      int64 `json:"slot_id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) ListMealSlotItems(ctx context.Context, arg ListMealSlotItemsParams) ([]MealplanMealSlotItem, error) {
	rows, err := q.db.Query(ctx, listMealSlotItems, arg.SlotID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealplanMealSlotItem{}
	for rows.Next() {
		var i MealplanMealSlotItem
		if err := rows.Scan(
			&i.SlotItemID,
			&i.SlotID,
			&i.ItemID,
			&i.Quantity,
			&i.IsFromRecipe,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.IngredientID,
			&i.UnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealSlotItemsByPlan = `-- name: ListMealSlotItemsByPlan :many
SELECT msi.slot_item_id, msi.slot_id, msi.item_id, msi.quantity, msi.is_from_recipe, msi.created_by, msi.created_at, msi.updated_by, msi.updated_at, msi.ingredient_id, msi.unit_id
FROM mealplan.meal_slot_item msi
JOIN mealplan.meal_slot ms ON msi.slot_id = ms.slot_id
JOIN mealplan.meal_plan mp ON ms.meal_plan_id = mp.meal_plan_id
WHERE ms.meal_plan_id = $1 AND mp.household_id = $2
ORDER BY msi.slot_item_id
`

type ListMealSlotItemsByPlanParams struct {
	MealPlanID  int64 `json:"meal_plan_id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) ListMealSlotItemsByPlan(ctx context.Context, arg ListMealSlotItemsByPlanParams) ([]MealplanMealSlotItem, error) {
	rows, err := q.db.Query(ctx, listMealSlotItemsByPlan, arg.MealPlanID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealplanMealSlotItem{}
	for rows.Next() {
		var i MealplanMealSlotItem
		if err := rows.Scan(
			&i.SlotItemID,
			&i.SlotID,
			&i.ItemID,
			&i.Quantity,
			&i.IsFromRecipe,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.IngredientID,
			&i.UnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealSlotItemsByPlans = `-- name: ListMealSlotItemsByPlans :many
SELECT msi.slot_item_id, msi.slot_id, msi.item_id, msi.quantity, msi.is_from_recipe, msi.created_by, msi.created_at, msi.updated_by, msi.updated_at, msi.ingredient_id, msi.unit_id
FROM mealplan.meal_slot_item msi
JOIN mealplan.meal_slot ms ON msi.slot_id = ms.slot_id
JOIN mealplan.meal_plan mp ON ms.meal_plan_id = mp.meal_plan_id
WHERE ms.meal_plan_id = ANY($1::bigint[]) AND mp.household_id = $2
ORDER BY msi.slot_item_id
`

type ListMealSlotItemsByPlansParams struct {
	MealPlanIds []int64 `json:"meal_plan_ids"`
	HouseholdID int64   `json:"household_id"`
}

func (q *Queries) ListMealSlotItemsByPlans(ctx context.Context, arg ListMealSlotItemsByPlansParams) ([]MealplanMealSlotItem, error) {
	rows, err := q.db.Query(ctx, listMealSlotItemsByPlans, arg.MealPlanIds, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealplanMealSlotItem{}
	for rows.Next() {
		var i MealplanMealSlotItem
		if err := rows.Scan(
			&i.SlotItemID,
			&i.SlotID,
			&i.ItemID,
			&i.Quantity,
			&i.IsFromRecipe,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.IngredientID,
			&i.UnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealSlotsByPlans = `-- name: ListMealSlotsByPlans :many
SELECT ms.slot_id, ms.meal_plan_id, ms.day_of_week, ms.meal_type, ms.recipe_id, ms.servings, ms.replacement_note, ms.created_by, ms.created_at, ms.updated_by, ms.updated_at
FROM mealplan.meal_slot ms
JOIN mealplan.meal_plan mp ON ms.meal_plan_id = mp.meal_plan_id
WHERE ms.meal_plan_id = ANY($1::bigint[]) AND mp.household_id = $2
ORDER BY ms.day_of_week, ms.meal_type
`

type ListMealSlotsByPlansParams struct {
	MealPlanIds []int64 `json:"meal_plan_ids"`
	HouseholdID int64   `json:"household_id"`
}

func (q *Queries) ListMealSlotsByPlans(ctx context.Context, arg ListMealSlotsByPlansParams) ([]MealplanMealSlot, error) {
	rows, err := q.db.Query(ctx, listMealSlotsByPlans, arg.MealPlanIds, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealplanMealSlot{}
	for rows.Next() {
		var i MealplanMealSlot
		if err := rows.Scan(
			&i.SlotID,
			&i.MealPlanID,
			&i.DayOfWeek,
			&i.MealType,
			&i.RecipeID,
			&i.Servings,
			&i.ReplacementNote,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealSlotsForPlan = `-- name: ListMealSlotsForPlan :many
SELECT ms.slot_id, ms.meal_plan_id, ms.day_of_week, ms.meal_type, ms.recipe_id, ms.servings, ms.replacement_note, ms.created_by, ms.created_at, ms.updated_by, ms.updated_at
FROM mealplan.meal_slot ms
JOIN mealplan.meal_plan mp ON ms.meal_plan_id = mp.meal_plan_id
WHERE ms.meal_plan_id = $1 AND mp.household_id = $2
ORDER BY ms.day_of_week, ms.meal_type
`

type ListMealSlotsForPlanParams struct {
	MealPlanID  int64 `json:"meal_plan_id"`
	HouseholdID int64 `json:"household_id"`
}

func (q *Queries) ListMealSlotsForPlan(ctx context.Context, arg ListMealSlotsForPlanParams) ([]MealplanMealSlot, error) {
	rows, err := q.db.Query(ctx, listMealSlotsForPlan, arg.MealPlanID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealplanMealSlot{}
	for rows.Next() {
		var i MealplanMealSlot
		if err := rows.Scan(
			&i.SlotID,
			&i.MealPlanID,
			&i.DayOfWeek,
			&i.MealType,
			&i.RecipeID,
			&i.Servings,
			&i.ReplacementNote,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignMealPlansToHousehold = `-- name: ReassignMealPlansToHousehold :exec
UPDATE mealplan.meal_plan
SET household_id = $1,
    updated_by   = $2::varchar,
    updated_at   = now()
WHERE household_id = $3
`

type ReassignMealPlansToHouseholdParams struct {
	ToHouseholdID   int64  `json:"to_household_id"`
	UpdatedBy       string `json:"updated_by"`
	FromHouseholdID int64  `json:"from_household_id"`
}

// Invite-accept merge: repoint all of the source household's plans. Zero
// rows is not an error (the source may have had none).
func (q *Queries) ReassignMealPlansToHousehold(ctx context.Context, arg ReassignMealPlansToHouseholdParams) error {
	_, err := q.db.Exec(ctx, reassignMealPlansToHousehold, arg.ToHouseholdID, arg.UpdatedBy, arg.FromHouseholdID)
	return err
}

const updateMealPlan = `-- name: UpdateMealPlan :exec
UPDATE mealplan.meal_plan
SET name                = $3,
    week_start_date     = $4,
    week_start_day_of_week = $5,
    is_active           = $6,
    updated_by          = $7,
    updated_at          = now()
WHERE meal_plan_id = $1 AND household_id = $2
`

type UpdateMealPlanParams struct {
	MealPlanID         int64       `json:"meal_plan_id"`
	HouseholdID        int64       `json:"household_id"`
	Name               string      `json:"name"`
	WeekStartDate      pgtype.Date `json:"week_start_date"`
	WeekStartDayOfWeek int16       `json:"week_start_day_of_week"`
	IsActive           bool        `json:"is_active"`
	UpdatedBy          pgtype.Text `json:"updated_by"`
}

func (q *Queries) UpdateMealPlan(ctx context.Context, arg UpdateMealPlanParams) error {
	_, err := q.db.Exec(ctx, updateMealPlan,
		arg.MealPlanID,
		arg.HouseholdID,
		arg.Name,
		arg.WeekStartDate,
		arg.WeekStartDayOfWeek,
		arg.IsActive,
		arg.UpdatedBy,
	)
	return err
}

const updateMealSlot = `-- name: UpdateMealSlot :exec
UPDATE mealplan.meal_slot ms
SET day_of_week      = $3,
    meal_type        = $4,
    recipe_id        = $5,
    servings         = $6,
    replacement_note = $7,
    updated_by       = $8,
    updated_at       = now()
FROM mealplan.meal_plan mp
WHERE ms.meal_plan_id = mp.meal_plan_id AND ms.slot_id = $1 AND mp.household_id = $2
`

type UpdateMealSlotParams struct {
	SlotID          int64       `json:"slot_id"`
	HouseholdID     int64       `json:"household_id"`
	DayOfWeek       int16       `json:"day_of_week"`
	MealType        string      `json:"meal_type"`
	RecipeID        pgtype.Int8 `json:"recipe_id"`
	Servings        pgtype.Int4 `json:"servings"`
	ReplacementNote pgtype.Text `json:"replacement_note"`
	UpdatedBy       pgtype.Text `json:"updated_by"`
}

func (q *Queries) UpdateMealSlot(ctx context.Context, arg UpdateMealSlotParams) error {
	_, err := q.db.Exec(ctx, updateMealSlot,
		arg.SlotID,
		arg.HouseholdID,
		arg.DayOfWeek,
		arg.MealType,
		arg.RecipeID,
		arg.Servings,
		arg.ReplacementNote,
		arg.UpdatedBy,
	)
	return err
}
