// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMealSlot = `-- name: AddMealSlot :one
INSERT INTO mealplan.meal_slot (meal_plan_id, day_of_week, meal_type, recipe_id, servings, replacement_note, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING slot_id, meal_plan_id, day_of_week, meal_type, recipe_id, servings, replacement_note, created_by, created_at, updated_by, updated_at
`

type AddMealSlotParams struct {
	MealPlanID      int64       `json:"meal_plan_id"`
	DayOfWeek       int16       `json:"day_of_week"`
	MealType        string      `json:"meal_type"`
	RecipeID        pgtype.Int8 `json:"recipe_id"`
	Servings        pgtype.Int4 `json:"servings"`
	ReplacementNote pgtype.Text `json:"replacement_note"`
	CreatedBy       string      `json:"created_by"`
	UpdatedBy       pgtype.Text `json:"updated_by"`
}

func (q *Queries) AddMealSlot(ctx context.Context, arg AddMealSlotParams) (MealplanMealSlot, error) {
	row := q.db.QueryRow(ctx, addMealSlot,
		arg.MealPlanID,
		arg.DayOfWeek,
		arg.MealType,
		arg.RecipeID,
		arg.Servings,
		arg.ReplacementNote,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i MealplanMealSlot
	err := row.Scan(
		&i.SlotID,
		&i.MealPlanID,
		&i.DayOfWeek,
		&i.MealType,
		&i.RecipeID,
		&i.Servings,
		&i.ReplacementNote,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const addMealSlotItem = `-- name: AddMealSlotItem :one
INSERT INTO mealplan.meal_slot_item (slot_id, item_id, quantity, unit, is_from_recipe, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING slot_item_id, slot_id, item_id, quantity, unit, is_from_recipe, created_by, created_at, updated_by, updated_at
`

type AddMealSlotItemParams struct {
	SlotID       int64          `json:"slot_id"`
	ItemID       pgtype.Int8    `json:"item_id"`
	Quantity     pgtype.Numeric `json:"quantity"`
	Unit         string         `json:"unit"`
	IsFromRecipe bool           `json:"is_from_recipe"`
	CreatedBy    string         `json:"created_by"`
	UpdatedBy    pgtype.Text    `json:"updated_by"`
}

func (q *Queries) AddMealSlotItem(ctx context.Context, arg AddMealSlotItemParams) (MealplanMealSlotItem, error) {
	row := q.db.QueryRow(ctx, addMealSlotItem,
		arg.SlotID,
		arg.ItemID,
		arg.Quantity,
		arg.Unit,
		arg.IsFromRecipe,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i MealplanMealSlotItem
	err := row.Scan(
		&i.SlotItemID,
		&i.SlotID,
		&i.ItemID,
		&i.Quantity,
		&i.Unit,
		&i.IsFromRecipe,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const countMealPlans = `-- name: CountMealPlans :one
SELECT COUNT(*)
FROM mealplan.meal_plan
WHERE user_id = $1
`

func (q *Queries) CountMealPlans(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMealPlans, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMealPlan = `-- name: CreateMealPlan :one
INSERT INTO mealplan.meal_plan (user_id, name, week_start_date, week_start_day_of_week, is_active, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING meal_plan_id, user_id, name, week_start_date, week_start_day_of_week, is_active, created_by, created_at, updated_by, updated_at
`

type CreateMealPlanParams struct {
	UserID             int64       `json:"user_id"`
	Name               string      `json:"name"`
	WeekStartDate      pgtype.Date `json:"week_start_date"`
	WeekStartDayOfWeek int16       `json:"week_start_day_of_week"`
	IsActive           bool        `json:"is_active"`
	CreatedBy          string      `json:"created_by"`
	UpdatedBy          pgtype.Text `json:"updated_by"`
}

func (q *Queries) CreateMealPlan(ctx context.Context, arg CreateMealPlanParams) (MealplanMealPlan, error) {
	row := q.db.QueryRow(ctx, createMealPlan,
		arg.UserID,
		arg.Name,
		arg.WeekStartDate,
		arg.WeekStartDayOfWeek,
		arg.IsActive,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i MealplanMealPlan
	err := row.Scan(
		&i.MealPlanID,
		&i.UserID,
		&i.Name,
		&i.WeekStartDate,
		&i.WeekStartDayOfWeek,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMealPlan = `-- name: DeleteMealPlan :exec
DELETE FROM mealplan.meal_plan
WHERE meal_plan_id = $1 AND user_id = $2
`

type DeleteMealPlanParams struct {
	MealPlanID int64 `json:"meal_plan_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) DeleteMealPlan(ctx context.Context, arg DeleteMealPlanParams) error {
	_, err := q.db.Exec(ctx, deleteMealPlan, arg.MealPlanID, arg.UserID)
	return err
}

const deleteMealSlot = `-- name: DeleteMealSlot :exec
DELETE FROM mealplan.meal_slot
WHERE slot_id = $1
`

func (q *Queries) DeleteMealSlot(ctx context.Context, slotID int64) error {
	_, err := q.db.Exec(ctx, deleteMealSlot, slotID)
	return err
}

const deleteMealSlotItem = `-- name: DeleteMealSlotItem :exec
DELETE FROM mealplan.meal_slot_item
WHERE slot_item_id = $1
`

func (q *Queries) DeleteMealSlotItem(ctx context.Context, slotItemID int64) error {
	_, err := q.db.Exec(ctx, deleteMealSlotItem, slotItemID)
	return err
}

const getMealPlanByID = `-- name: GetMealPlanByID :one
SELECT meal_plan_id, user_id, name, week_start_date, week_start_day_of_week, is_active, created_by, created_at, updated_by, updated_at
FROM mealplan.meal_plan
WHERE meal_plan_id = $1 AND user_id = $2
`

type GetMealPlanByIDParams struct {
	MealPlanID int64 `json:"meal_plan_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) GetMealPlanByID(ctx context.Context, arg GetMealPlanByIDParams) (MealplanMealPlan, error) {
	row := q.db.QueryRow(ctx, getMealPlanByID, arg.MealPlanID, arg.UserID)
	var i MealplanMealPlan
	err := row.Scan(
		&i.MealPlanID,
		&i.UserID,
		&i.Name,
		&i.WeekStartDate,
		&i.WeekStartDayOfWeek,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getMealSlotByID = `-- name: GetMealSlotByID :one
SELECT slot_id, meal_plan_id, day_of_week, meal_type, recipe_id, servings, replacement_note, created_by, created_at, updated_by, updated_at
FROM mealplan.meal_slot
WHERE slot_id = $1
`

func (q *Queries) GetMealSlotByID(ctx context.Context, slotID int64) (MealplanMealSlot, error) {
	row := q.db.QueryRow(ctx, getMealSlotByID, slotID)
	var i MealplanMealSlot
	err := row.Scan(
		&i.SlotID,
		&i.MealPlanID,
		&i.DayOfWeek,
		&i.MealType,
		&i.RecipeID,
		&i.Servings,
		&i.ReplacementNote,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listMealPlans = `-- name: ListMealPlans :many
SELECT meal_plan_id, user_id, name, week_start_date, week_start_day_of_week, is_active, created_by, created_at, updated_by, updated_at
FROM mealplan.meal_plan
WHERE user_id = $1
ORDER BY week_start_date DESC
LIMIT $2 OFFSET $3
`

type ListMealPlansParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMealPlans(ctx context.Context, arg ListMealPlansParams) ([]MealplanMealPlan, error) {
	rows, err := q.db.Query(ctx, listMealPlans, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealplanMealPlan{}
	for rows.Next() {
		var i MealplanMealPlan
		if err := rows.Scan(
			&i.MealPlanID,
			&i.UserID,
			&i.Name,
			&i.WeekStartDate,
			&i.WeekStartDayOfWeek,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealSlotItems = `-- name: ListMealSlotItems :many
SELECT slot_item_id, slot_id, item_id, quantity, unit, is_from_recipe, created_by, created_at, updated_by, updated_at
FROM mealplan.meal_slot_item
WHERE slot_id = $1
ORDER BY slot_item_id
`

func (q *Queries) ListMealSlotItems(ctx context.Context, slotID int64) ([]MealplanMealSlotItem, error) {
	rows, err := q.db.Query(ctx, listMealSlotItems, slotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealplanMealSlotItem{}
	for rows.Next() {
		var i MealplanMealSlotItem
		if err := rows.Scan(
			&i.SlotItemID,
			&i.SlotID,
			&i.ItemID,
			&i.Quantity,
			&i.Unit,
			&i.IsFromRecipe,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealSlotItemsByPlan = `-- name: ListMealSlotItemsByPlan :many
SELECT msi.slot_item_id, msi.slot_id, msi.item_id, msi.quantity, msi.unit, msi.is_from_recipe, msi.created_by, msi.created_at, msi.updated_by, msi.updated_at
FROM mealplan.meal_slot_item msi
JOIN mealplan.meal_slot ms ON msi.slot_id = ms.slot_id
WHERE ms.meal_plan_id = $1
ORDER BY msi.slot_item_id
`

func (q *Queries) ListMealSlotItemsByPlan(ctx context.Context, mealPlanID int64) ([]MealplanMealSlotItem, error) {
	rows, err := q.db.Query(ctx, listMealSlotItemsByPlan, mealPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealplanMealSlotItem{}
	for rows.Next() {
		var i MealplanMealSlotItem
		if err := rows.Scan(
			&i.SlotItemID,
			&i.SlotID,
			&i.ItemID,
			&i.Quantity,
			&i.Unit,
			&i.IsFromRecipe,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealSlotItemsByPlans = `-- name: ListMealSlotItemsByPlans :many
SELECT msi.slot_item_id, msi.slot_id, msi.item_id, msi.quantity, msi.unit, msi.is_from_recipe, msi.created_by, msi.created_at, msi.updated_by, msi.updated_at
FROM mealplan.meal_slot_item msi
JOIN mealplan.meal_slot ms ON msi.slot_id = ms.slot_id
WHERE ms.meal_plan_id = ANY($1::bigint[])
ORDER BY msi.slot_item_id
`

func (q *Queries) ListMealSlotItemsByPlans(ctx context.Context, mealPlanIds []int64) ([]MealplanMealSlotItem, error) {
	rows, err := q.db.Query(ctx, listMealSlotItemsByPlans, mealPlanIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealplanMealSlotItem{}
	for rows.Next() {
		var i MealplanMealSlotItem
		if err := rows.Scan(
			&i.SlotItemID,
			&i.SlotID,
			&i.ItemID,
			&i.Quantity,
			&i.Unit,
			&i.IsFromRecipe,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealSlotsByPlans = `-- name: ListMealSlotsByPlans :many
SELECT slot_id, meal_plan_id, day_of_week, meal_type, recipe_id, servings, replacement_note, created_by, created_at, updated_by, updated_at
FROM mealplan.meal_slot
WHERE meal_plan_id = ANY($1::bigint[])
ORDER BY day_of_week, meal_type
`

func (q *Queries) ListMealSlotsByPlans(ctx context.Context, mealPlanIds []int64) ([]MealplanMealSlot, error) {
	rows, err := q.db.Query(ctx, listMealSlotsByPlans, mealPlanIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealplanMealSlot{}
	for rows.Next() {
		var i MealplanMealSlot
		if err := rows.Scan(
			&i.SlotID,
			&i.MealPlanID,
			&i.DayOfWeek,
			&i.MealType,
			&i.RecipeID,
			&i.Servings,
			&i.ReplacementNote,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealSlotsForPlan = `-- name: ListMealSlotsForPlan :many
SELECT slot_id, meal_plan_id, day_of_week, meal_type, recipe_id, servings, replacement_note, created_by, created_at, updated_by, updated_at
FROM mealplan.meal_slot
WHERE meal_plan_id = $1
ORDER BY day_of_week, meal_type
`

func (q *Queries) ListMealSlotsForPlan(ctx context.Context, mealPlanID int64) ([]MealplanMealSlot, error) {
	rows, err := q.db.Query(ctx, listMealSlotsForPlan, mealPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealplanMealSlot{}
	for rows.Next() {
		var i MealplanMealSlot
		if err := rows.Scan(
			&i.SlotID,
			&i.MealPlanID,
			&i.DayOfWeek,
			&i.MealType,
			&i.RecipeID,
			&i.Servings,
			&i.ReplacementNote,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMealPlan = `-- name: UpdateMealPlan :exec
UPDATE mealplan.meal_plan
SET name                = $3,
    week_start_date     = $4,
    week_start_day_of_week = $5,
    is_active           = $6,
    updated_by          = $7,
    updated_at          = now()
WHERE meal_plan_id = $1 AND user_id = $2
`

type UpdateMealPlanParams struct {
	MealPlanID         int64       `json:"meal_plan_id"`
	UserID             int64       `json:"user_id"`
	Name               string      `json:"name"`
	WeekStartDate      pgtype.Date `json:"week_start_date"`
	WeekStartDayOfWeek int16       `json:"week_start_day_of_week"`
	IsActive           bool        `json:"is_active"`
	UpdatedBy          pgtype.Text `json:"updated_by"`
}

func (q *Queries) UpdateMealPlan(ctx context.Context, arg UpdateMealPlanParams) error {
	_, err := q.db.Exec(ctx, updateMealPlan,
		arg.MealPlanID,
		arg.UserID,
		arg.Name,
		arg.WeekStartDate,
		arg.WeekStartDayOfWeek,
		arg.IsActive,
		arg.UpdatedBy,
	)
	return err
}

const updateMealSlot = `-- name: UpdateMealSlot :exec
UPDATE mealplan.meal_slot
SET day_of_week      = $2,
    meal_type        = $3,
    recipe_id        = $4,
    servings         = $5,
    replacement_note = $6,
    updated_by       = $7,
    updated_at       = now()
WHERE slot_id = $1
`

type UpdateMealSlotParams struct {
	SlotID          int64       `json:"slot_id"`
	DayOfWeek       int16       `json:"day_of_week"`
	MealType        string      `json:"meal_type"`
	RecipeID        pgtype.Int8 `json:"recipe_id"`
	Servings        pgtype.Int4 `json:"servings"`
	ReplacementNote pgtype.Text `json:"replacement_note"`
	UpdatedBy       pgtype.Text `json:"updated_by"`
}

func (q *Queries) UpdateMealSlot(ctx context.Context, arg UpdateMealSlotParams) error {
	_, err := q.db.Exec(ctx, updateMealSlot,
		arg.SlotID,
		arg.DayOfWeek,
		arg.MealType,
		arg.RecipeID,
		arg.Servings,
		arg.ReplacementNote,
		arg.UpdatedBy,
	)
	return err
}
