// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CountUserBottles(ctx context.Context, userID int64) (int64, error)
	CountUserItems(ctx context.Context, userID int64) (int64, error)
	DeleteRecipeFavorite(ctx context.Context, arg DeleteRecipeFavoriteParams) error
	DeleteUserBottle(ctx context.Context, arg DeleteUserBottleParams) error
	DeleteUserItem(ctx context.Context, arg DeleteUserItemParams) error
	GetRecipeFavorite(ctx context.Context, arg GetRecipeFavoriteParams) (RecipeUserRecipePreference, error)
	GetUserBottleByID(ctx context.Context, arg GetUserBottleByIDParams) (WineUserBottle, error)
	GetUserItemByID(ctx context.Context, arg GetUserItemByIDParams) (InventoryUserItem, error)
	ListRecipeFavorites(ctx context.Context, arg ListRecipeFavoritesParams) ([]RecipeUserRecipePreference, error)
	ListUserBottles(ctx context.Context, arg ListUserBottlesParams) ([]WineUserBottle, error)
	ListUserItems(ctx context.Context, arg ListUserItemsParams) ([]InventoryUserItem, error)
	UpsertRecipeFavorite(ctx context.Context, arg UpsertRecipeFavoriteParams) (RecipeUserRecipePreference, error)
	UpsertUserBottle(ctx context.Context, arg UpsertUserBottleParams) (WineUserBottle, error)
	UpsertUserItem(ctx context.Context, arg UpsertUserItemParams) (InventoryUserItem, error)
}

var _ Querier = (*Queries)(nil)
