// Code generated by MockGen. DO NOT EDIT.
// Source: querier.go
//
// Generated by this command:
//
//	mockgen -source=querier.go -package=mock -destination=mock/querier.go Querier
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/JRAdams472/LENA2/internal/event/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// AddEventRecipe mocks base method.
func (m *MockQuerier) AddEventRecipe(ctx context.Context, arg sqlc.AddEventRecipeParams) (sqlc.EventEventRecipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEventRecipe", ctx, arg)
	ret0, _ := ret[0].(sqlc.EventEventRecipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddEventRecipe indicates an expected call of AddEventRecipe.
func (mr *MockQuerierMockRecorder) AddEventRecipe(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEventRecipe", reflect.TypeOf((*MockQuerier)(nil).AddEventRecipe), ctx, arg)
}

// CountFoodEvents mocks base method.
func (m *MockQuerier) CountFoodEvents(ctx context.Context, householdID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFoodEvents", ctx, householdID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFoodEvents indicates an expected call of CountFoodEvents.
func (mr *MockQuerierMockRecorder) CountFoodEvents(ctx, householdID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFoodEvents", reflect.TypeOf((*MockQuerier)(nil).CountFoodEvents), ctx, householdID)
}

// CreateFoodEvent mocks base method.
func (m *MockQuerier) CreateFoodEvent(ctx context.Context, arg sqlc.CreateFoodEventParams) (sqlc.EventFoodEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFoodEvent", ctx, arg)
	ret0, _ := ret[0].(sqlc.EventFoodEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFoodEvent indicates an expected call of CreateFoodEvent.
func (mr *MockQuerierMockRecorder) CreateFoodEvent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFoodEvent", reflect.TypeOf((*MockQuerier)(nil).CreateFoodEvent), ctx, arg)
}

// DeleteEventRecipe mocks base method.
func (m *MockQuerier) DeleteEventRecipe(ctx context.Context, arg sqlc.DeleteEventRecipeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEventRecipe", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEventRecipe indicates an expected call of DeleteEventRecipe.
func (mr *MockQuerierMockRecorder) DeleteEventRecipe(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEventRecipe", reflect.TypeOf((*MockQuerier)(nil).DeleteEventRecipe), ctx, arg)
}

// DeleteFoodEvent mocks base method.
func (m *MockQuerier) DeleteFoodEvent(ctx context.Context, arg sqlc.DeleteFoodEventParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFoodEvent", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFoodEvent indicates an expected call of DeleteFoodEvent.
func (mr *MockQuerierMockRecorder) DeleteFoodEvent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFoodEvent", reflect.TypeOf((*MockQuerier)(nil).DeleteFoodEvent), ctx, arg)
}

// GetEventRecipeByID mocks base method.
func (m *MockQuerier) GetEventRecipeByID(ctx context.Context, arg sqlc.GetEventRecipeByIDParams) (sqlc.EventEventRecipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventRecipeByID", ctx, arg)
	ret0, _ := ret[0].(sqlc.EventEventRecipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventRecipeByID indicates an expected call of GetEventRecipeByID.
func (mr *MockQuerierMockRecorder) GetEventRecipeByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventRecipeByID", reflect.TypeOf((*MockQuerier)(nil).GetEventRecipeByID), ctx, arg)
}

// GetFoodEventByID mocks base method.
func (m *MockQuerier) GetFoodEventByID(ctx context.Context, arg sqlc.GetFoodEventByIDParams) (sqlc.EventFoodEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFoodEventByID", ctx, arg)
	ret0, _ := ret[0].(sqlc.EventFoodEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFoodEventByID indicates an expected call of GetFoodEventByID.
func (mr *MockQuerierMockRecorder) GetFoodEventByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFoodEventByID", reflect.TypeOf((*MockQuerier)(nil).GetFoodEventByID), ctx, arg)
}

// ListEventRecipesByEvents mocks base method.
func (m *MockQuerier) ListEventRecipesByEvents(ctx context.Context, arg sqlc.ListEventRecipesByEventsParams) ([]sqlc.EventEventRecipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEventRecipesByEvents", ctx, arg)
	ret0, _ := ret[0].([]sqlc.EventEventRecipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEventRecipesByEvents indicates an expected call of ListEventRecipesByEvents.
func (mr *MockQuerierMockRecorder) ListEventRecipesByEvents(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEventRecipesByEvents", reflect.TypeOf((*MockQuerier)(nil).ListEventRecipesByEvents), ctx, arg)
}

// ListEventRecipesForEvent mocks base method.
func (m *MockQuerier) ListEventRecipesForEvent(ctx context.Context, arg sqlc.ListEventRecipesForEventParams) ([]sqlc.EventEventRecipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEventRecipesForEvent", ctx, arg)
	ret0, _ := ret[0].([]sqlc.EventEventRecipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEventRecipesForEvent indicates an expected call of ListEventRecipesForEvent.
func (mr *MockQuerierMockRecorder) ListEventRecipesForEvent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEventRecipesForEvent", reflect.TypeOf((*MockQuerier)(nil).ListEventRecipesForEvent), ctx, arg)
}

// ListFoodEvents mocks base method.
func (m *MockQuerier) ListFoodEvents(ctx context.Context, arg sqlc.ListFoodEventsParams) ([]sqlc.EventFoodEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFoodEvents", ctx, arg)
	ret0, _ := ret[0].([]sqlc.EventFoodEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFoodEvents indicates an expected call of ListFoodEvents.
func (mr *MockQuerierMockRecorder) ListFoodEvents(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFoodEvents", reflect.TypeOf((*MockQuerier)(nil).ListFoodEvents), ctx, arg)
}

// ReassignFoodEventsToHousehold mocks base method.
func (m *MockQuerier) ReassignFoodEventsToHousehold(ctx context.Context, arg sqlc.ReassignFoodEventsToHouseholdParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignFoodEventsToHousehold", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReassignFoodEventsToHousehold indicates an expected call of ReassignFoodEventsToHousehold.
func (mr *MockQuerierMockRecorder) ReassignFoodEventsToHousehold(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignFoodEventsToHousehold", reflect.TypeOf((*MockQuerier)(nil).ReassignFoodEventsToHousehold), ctx, arg)
}

// UpdateEventRecipe mocks base method.
func (m *MockQuerier) UpdateEventRecipe(ctx context.Context, arg sqlc.UpdateEventRecipeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEventRecipe", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEventRecipe indicates an expected call of UpdateEventRecipe.
func (mr *MockQuerierMockRecorder) UpdateEventRecipe(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEventRecipe", reflect.TypeOf((*MockQuerier)(nil).UpdateEventRecipe), ctx, arg)
}

// UpdateFoodEvent mocks base method.
func (m *MockQuerier) UpdateFoodEvent(ctx context.Context, arg sqlc.UpdateFoodEventParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFoodEvent", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFoodEvent indicates an expected call of UpdateFoodEvent.
func (mr *MockQuerierMockRecorder) UpdateFoodEvent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFoodEvent", reflect.TypeOf((*MockQuerier)(nil).UpdateFoodEvent), ctx, arg)
}
