// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBrand = `-- name: CreateBrand :one
INSERT INTO inventory.brand (name)
VALUES ($1)
RETURNING brand_id, name, created_at
`

func (q *Queries) CreateBrand(ctx context.Context, name string) (InventoryBrand, error) {
	row := q.db.QueryRow(ctx, createBrand, name)
	var i InventoryBrand
	err := row.Scan(&i.BrandID, &i.Name, &i.CreatedAt)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO inventory.category (name, description, is_active, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING category_id, name, description, is_active, created_by, created_at, updated_by, updated_at
`

type CreateCategoryParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	CreatedBy   string      `json:"created_by"`
	UpdatedBy   pgtype.Text `json:"updated_by"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (InventoryCategory, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i InventoryCategory
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createFlavorProfile = `-- name: CreateFlavorProfile :one
INSERT INTO inventory.flavor_profile (name, is_active, created_by, updated_by)
VALUES ($1, $2, $3, $4)
RETURNING flavor_id, name, is_active, created_by, created_at, updated_by, updated_at
`

type CreateFlavorProfileParams struct {
	Name      string      `json:"name"`
	IsActive  bool        `json:"is_active"`
	CreatedBy string      `json:"created_by"`
	UpdatedBy pgtype.Text `json:"updated_by"`
}

func (q *Queries) CreateFlavorProfile(ctx context.Context, arg CreateFlavorProfileParams) (InventoryFlavorProfile, error) {
	row := q.db.QueryRow(ctx, createFlavorProfile,
		arg.Name,
		arg.IsActive,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i InventoryFlavorProfile
	err := row.Scan(
		&i.FlavorID,
		&i.Name,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO inventory.item (name, brand_id, upc12, upc14, category_id, unit, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING item_id, name, brand_id, upc12, upc14, category_id, unit, created_by, created_at, updated_by, updated_at
`

type CreateItemParams struct {
	Name       string      `json:"name"`
	BrandID    pgtype.Int8 `json:"brand_id"`
	Upc12      pgtype.Text `json:"upc12"`
	Upc14      pgtype.Text `json:"upc14"`
	CategoryID int64       `json:"category_id"`
	Unit       string      `json:"unit"`
	CreatedBy  string      `json:"created_by"`
	UpdatedBy  pgtype.Text `json:"updated_by"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.Name,
		arg.BrandID,
		arg.Upc12,
		arg.Upc14,
		arg.CategoryID,
		arg.Unit,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ItemID,
		&i.Name,
		&i.BrandID,
		&i.Upc12,
		&i.Upc14,
		&i.CategoryID,
		&i.Unit,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createNutrientType = `-- name: CreateNutrientType :one
INSERT INTO inventory.nutrient_type (name, unit)
VALUES ($1, $2)
RETURNING nutrient_id, name, unit, created_at
`

type CreateNutrientTypeParams struct {
	Name string      `json:"name"`
	Unit pgtype.Text `json:"unit"`
}

func (q *Queries) CreateNutrientType(ctx context.Context, arg CreateNutrientTypeParams) (InventoryNutrientType, error) {
	row := q.db.QueryRow(ctx, createNutrientType, arg.Name, arg.Unit)
	var i InventoryNutrientType
	err := row.Scan(
		&i.NutrientID,
		&i.Name,
		&i.Unit,
		&i.CreatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM inventory.item
WHERE item_id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, itemID int64) error {
	_, err := q.db.Exec(ctx, deleteItem, itemID)
	return err
}

const getBrandByID = `-- name: GetBrandByID :one
SELECT brand_id, name, created_at
FROM inventory.brand
WHERE brand_id = $1
`

func (q *Queries) GetBrandByID(ctx context.Context, brandID int64) (InventoryBrand, error) {
	row := q.db.QueryRow(ctx, getBrandByID, brandID)
	var i InventoryBrand
	err := row.Scan(&i.BrandID, &i.Name, &i.CreatedAt)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT category_id, name, description, is_active, created_by, created_at, updated_by, updated_at
FROM inventory.category
WHERE category_id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, categoryID int64) (InventoryCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, categoryID)
	var i InventoryCategory
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemByID = `-- name: GetItemByID :one
SELECT item_id, name, brand_id, upc12, upc14, category_id, unit, created_by, created_at, updated_by, updated_at
FROM inventory.item
WHERE item_id = $1
`

func (q *Queries) GetItemByID(ctx context.Context, itemID int64) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, getItemByID, itemID)
	var i InventoryItem
	err := row.Scan(
		&i.ItemID,
		&i.Name,
		&i.BrandID,
		&i.Upc12,
		&i.Upc14,
		&i.CategoryID,
		&i.Unit,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listBrands = `-- name: ListBrands :many
SELECT brand_id, name, created_at
FROM inventory.brand
ORDER BY name
`

func (q *Queries) ListBrands(ctx context.Context) ([]InventoryBrand, error) {
	rows, err := q.db.Query(ctx, listBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryBrand{}
	for rows.Next() {
		var i InventoryBrand
		if err := rows.Scan(&i.BrandID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT category_id, name, description, is_active, created_by, created_at, updated_by, updated_at
FROM inventory.category
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]InventoryCategory, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryCategory{}
	for rows.Next() {
		var i InventoryCategory
		if err := rows.Scan(
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlavorProfiles = `-- name: ListFlavorProfiles :many
SELECT flavor_id, name, is_active, created_by, created_at, updated_by, updated_at
FROM inventory.flavor_profile
ORDER BY name
`

func (q *Queries) ListFlavorProfiles(ctx context.Context) ([]InventoryFlavorProfile, error) {
	rows, err := q.db.Query(ctx, listFlavorProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryFlavorProfile{}
	for rows.Next() {
		var i InventoryFlavorProfile
		if err := rows.Scan(
			&i.FlavorID,
			&i.Name,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoodNutrientsByItem = `-- name: ListFoodNutrientsByItem :many
SELECT nt.nutrient_id, nt.name, nt.unit, fn.amount
FROM inventory.food_nutrient fn
JOIN inventory.nutrient_type nt ON fn.nutrient_id = nt.nutrient_id
WHERE fn.food_id = $1
ORDER BY nt.name
`

type ListFoodNutrientsByItemRow struct {
	NutrientID int64          `json:"nutrient_id"`
	Name       string         `json:"name"`
	Unit       pgtype.Text    `json:"unit"`
	Amount     pgtype.Numeric `json:"amount"`
}

func (q *Queries) ListFoodNutrientsByItem(ctx context.Context, foodID int64) ([]ListFoodNutrientsByItemRow, error) {
	rows, err := q.db.Query(ctx, listFoodNutrientsByItem, foodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFoodNutrientsByItemRow{}
	for rows.Next() {
		var i ListFoodNutrientsByItemRow
		if err := rows.Scan(
			&i.NutrientID,
			&i.Name,
			&i.Unit,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT item_id, name, brand_id, upc12, upc14, category_id, unit, created_by, created_at, updated_by, updated_at
FROM inventory.item
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListItemsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]InventoryItem, error) {
	rows, err := q.db.Query(ctx, listItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryItem{}
	for rows.Next() {
		var i InventoryItem
		if err := rows.Scan(
			&i.ItemID,
			&i.Name,
			&i.BrandID,
			&i.Upc12,
			&i.Upc14,
			&i.CategoryID,
			&i.Unit,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNutrientTypes = `-- name: ListNutrientTypes :many
SELECT nutrient_id, name, unit, created_at
FROM inventory.nutrient_type
ORDER BY name
`

func (q *Queries) ListNutrientTypes(ctx context.Context) ([]InventoryNutrientType, error) {
	rows, err := q.db.Query(ctx, listNutrientTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryNutrientType{}
	for rows.Next() {
		var i InventoryNutrientType
		if err := rows.Scan(
			&i.NutrientID,
			&i.Name,
			&i.Unit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :exec
UPDATE inventory.item
SET name        = $2,
    brand_id    = $3,
    upc12       = $4,
    upc14       = $5,
    category_id = $6,
    unit        = $7,
    updated_by  = $8,
    updated_at  = now()
WHERE item_id = $1
`

type UpdateItemParams struct {
	ItemID     int64       `json:"item_id"`
	Name       string      `json:"name"`
	BrandID    pgtype.Int8 `json:"brand_id"`
	Upc12      pgtype.Text `json:"upc12"`
	Upc14      pgtype.Text `json:"upc14"`
	CategoryID int64       `json:"category_id"`
	Unit       string      `json:"unit"`
	UpdatedBy  pgtype.Text `json:"updated_by"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) error {
	_, err := q.db.Exec(ctx, updateItem,
		arg.ItemID,
		arg.Name,
		arg.BrandID,
		arg.Upc12,
		arg.Upc14,
		arg.CategoryID,
		arg.Unit,
		arg.UpdatedBy,
	)
	return err
}
