// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIngredients = `-- name: CountIngredients :one
SELECT COUNT(*)
FROM inventory.ingredient
`

func (q *Queries) CountIngredients(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countIngredients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countItems = `-- name: CountItems :one
SELECT COUNT(*)
FROM inventory.item
`

func (q *Queries) CountItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBrand = `-- name: CreateBrand :one
INSERT INTO inventory.brand (name)
VALUES ($1)
RETURNING brand_id, name, created_at
`

func (q *Queries) CreateBrand(ctx context.Context, name string) (InventoryBrand, error) {
	row := q.db.QueryRow(ctx, createBrand, name)
	var i InventoryBrand
	err := row.Scan(&i.BrandID, &i.Name, &i.CreatedAt)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO inventory.category (name, description, is_active, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING category_id, name, description, is_active, created_by, created_at, updated_by, updated_at
`

type CreateCategoryParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	CreatedBy   string      `json:"created_by"`
	UpdatedBy   pgtype.Text `json:"updated_by"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (InventoryCategory, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i InventoryCategory
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createFlavorProfile = `-- name: CreateFlavorProfile :one
INSERT INTO inventory.flavor_profile (name, is_active, created_by, updated_by)
VALUES ($1, $2, $3, $4)
RETURNING flavor_id, name, is_active, created_by, created_at, updated_by, updated_at
`

type CreateFlavorProfileParams struct {
	Name      string      `json:"name"`
	IsActive  bool        `json:"is_active"`
	CreatedBy string      `json:"created_by"`
	UpdatedBy pgtype.Text `json:"updated_by"`
}

func (q *Queries) CreateFlavorProfile(ctx context.Context, arg CreateFlavorProfileParams) (InventoryFlavorProfile, error) {
	row := q.db.QueryRow(ctx, createFlavorProfile,
		arg.Name,
		arg.IsActive,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i InventoryFlavorProfile
	err := row.Scan(
		&i.FlavorID,
		&i.Name,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createFoodFlavor = `-- name: CreateFoodFlavor :one
INSERT INTO inventory.food_flavor (food_id, flavor_id, intensity, created_by)
VALUES ($1, $2, $3, $4)
RETURNING food_id, flavor_id, intensity, created_by, created_at
`

type CreateFoodFlavorParams struct {
	FoodID    int64  `json:"food_id"`
	FlavorID  int64  `json:"flavor_id"`
	Intensity int16  `json:"intensity"`
	CreatedBy string `json:"created_by"`
}

func (q *Queries) CreateFoodFlavor(ctx context.Context, arg CreateFoodFlavorParams) (InventoryFoodFlavor, error) {
	row := q.db.QueryRow(ctx, createFoodFlavor,
		arg.FoodID,
		arg.FlavorID,
		arg.Intensity,
		arg.CreatedBy,
	)
	var i InventoryFoodFlavor
	err := row.Scan(
		&i.FoodID,
		&i.FlavorID,
		&i.Intensity,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createFoodNutrient = `-- name: CreateFoodNutrient :one
INSERT INTO inventory.food_nutrient (food_id, nutrient_id, amount, created_by)
VALUES ($1, $2, $3, $4)
RETURNING food_id, nutrient_id, amount, created_by, created_at
`

type CreateFoodNutrientParams struct {
	FoodID     int64          `json:"food_id"`
	NutrientID int64          `json:"nutrient_id"`
	Amount     pgtype.Numeric `json:"amount"`
	CreatedBy  string         `json:"created_by"`
}

func (q *Queries) CreateFoodNutrient(ctx context.Context, arg CreateFoodNutrientParams) (InventoryFoodNutrient, error) {
	row := q.db.QueryRow(ctx, createFoodNutrient,
		arg.FoodID,
		arg.NutrientID,
		arg.Amount,
		arg.CreatedBy,
	)
	var i InventoryFoodNutrient
	err := row.Scan(
		&i.FoodID,
		&i.NutrientID,
		&i.Amount,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO inventory.ingredient (name, category_id, default_unit_id, is_active, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING ingredient_id, name, category_id, is_active, created_by, created_at, updated_by, updated_at, default_unit_id
`

type CreateIngredientParams struct {
	Name          string      `json:"name"`
	CategoryID    pgtype.Int8 `json:"category_id"`
	DefaultUnitID pgtype.Int8 `json:"default_unit_id"`
	IsActive      bool        `json:"is_active"`
	CreatedBy     string      `json:"created_by"`
	UpdatedBy     pgtype.Text `json:"updated_by"`
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (InventoryIngredient, error) {
	row := q.db.QueryRow(ctx, createIngredient,
		arg.Name,
		arg.CategoryID,
		arg.DefaultUnitID,
		arg.IsActive,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i InventoryIngredient
	err := row.Scan(
		&i.IngredientID,
		&i.Name,
		&i.CategoryID,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DefaultUnitID,
	)
	return i, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO inventory.item (name, brand_id, upc12, upc14, category_id, unit_id, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING item_id, name, brand_id, upc12, upc14, category_id, created_by, created_at, updated_by, updated_at, unit_id
`

type CreateItemParams struct {
	Name       string      `json:"name"`
	BrandID    pgtype.Int8 `json:"brand_id"`
	Upc12      pgtype.Text `json:"upc12"`
	Upc14      pgtype.Text `json:"upc14"`
	CategoryID int64       `json:"category_id"`
	UnitID     int64       `json:"unit_id"`
	CreatedBy  string      `json:"created_by"`
	UpdatedBy  pgtype.Text `json:"updated_by"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.Name,
		arg.BrandID,
		arg.Upc12,
		arg.Upc14,
		arg.CategoryID,
		arg.UnitID,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ItemID,
		&i.Name,
		&i.BrandID,
		&i.Upc12,
		&i.Upc14,
		&i.CategoryID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.UnitID,
	)
	return i, err
}

const createNutrientType = `-- name: CreateNutrientType :one
INSERT INTO inventory.nutrient_type (name, unit)
VALUES ($1, $2)
RETURNING nutrient_id, name, unit, created_at
`

type CreateNutrientTypeParams struct {
	Name string      `json:"name"`
	Unit pgtype.Text `json:"unit"`
}

func (q *Queries) CreateNutrientType(ctx context.Context, arg CreateNutrientTypeParams) (InventoryNutrientType, error) {
	row := q.db.QueryRow(ctx, createNutrientType, arg.Name, arg.Unit)
	var i InventoryNutrientType
	err := row.Scan(
		&i.NutrientID,
		&i.Name,
		&i.Unit,
		&i.CreatedAt,
	)
	return i, err
}

const createUnit = `-- name: CreateUnit :one
INSERT INTO inventory.unit (name, abbreviation, kind, is_active, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING unit_id, name, abbreviation, kind, is_active, created_by, created_at, updated_by, updated_at
`

type CreateUnitParams struct {
	Name         string      `json:"name"`
	Abbreviation pgtype.Text `json:"abbreviation"`
	Kind         string      `json:"kind"`
	IsActive     bool        `json:"is_active"`
	CreatedBy    string      `json:"created_by"`
	UpdatedBy    pgtype.Text `json:"updated_by"`
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (InventoryUnit, error) {
	row := q.db.QueryRow(ctx, createUnit,
		arg.Name,
		arg.Abbreviation,
		arg.Kind,
		arg.IsActive,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i InventoryUnit
	err := row.Scan(
		&i.UnitID,
		&i.Name,
		&i.Abbreviation,
		&i.Kind,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBrand = `-- name: DeleteBrand :exec
DELETE FROM inventory.brand
WHERE brand_id = $1
`

func (q *Queries) DeleteBrand(ctx context.Context, brandID int64) error {
	_, err := q.db.Exec(ctx, deleteBrand, brandID)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM inventory.category
WHERE category_id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, categoryID int64) error {
	_, err := q.db.Exec(ctx, deleteCategory, categoryID)
	return err
}

const deleteFlavorProfile = `-- name: DeleteFlavorProfile :exec
DELETE FROM inventory.flavor_profile
WHERE flavor_id = $1
`

func (q *Queries) DeleteFlavorProfile(ctx context.Context, flavorID int64) error {
	_, err := q.db.Exec(ctx, deleteFlavorProfile, flavorID)
	return err
}

const deleteFoodFlavor = `-- name: DeleteFoodFlavor :exec
DELETE FROM inventory.food_flavor
WHERE food_id = $1 AND flavor_id = $2
`

type DeleteFoodFlavorParams struct {
	FoodID   int64 `json:"food_id"`
	FlavorID int64 `json:"flavor_id"`
}

func (q *Queries) DeleteFoodFlavor(ctx context.Context, arg DeleteFoodFlavorParams) error {
	_, err := q.db.Exec(ctx, deleteFoodFlavor, arg.FoodID, arg.FlavorID)
	return err
}

const deleteFoodNutrient = `-- name: DeleteFoodNutrient :exec
DELETE FROM inventory.food_nutrient
WHERE food_id = $1 AND nutrient_id = $2
`

type DeleteFoodNutrientParams struct {
	FoodID     int64 `json:"food_id"`
	NutrientID int64 `json:"nutrient_id"`
}

func (q *Queries) DeleteFoodNutrient(ctx context.Context, arg DeleteFoodNutrientParams) error {
	_, err := q.db.Exec(ctx, deleteFoodNutrient, arg.FoodID, arg.NutrientID)
	return err
}

const deleteIngredient = `-- name: DeleteIngredient :exec
DELETE FROM inventory.ingredient
WHERE ingredient_id = $1
`

func (q *Queries) DeleteIngredient(ctx context.Context, ingredientID int64) error {
	_, err := q.db.Exec(ctx, deleteIngredient, ingredientID)
	return err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM inventory.item
WHERE item_id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, itemID int64) error {
	_, err := q.db.Exec(ctx, deleteItem, itemID)
	return err
}

const deleteNutrientType = `-- name: DeleteNutrientType :exec
DELETE FROM inventory.nutrient_type
WHERE nutrient_id = $1
`

func (q *Queries) DeleteNutrientType(ctx context.Context, nutrientID int64) error {
	_, err := q.db.Exec(ctx, deleteNutrientType, nutrientID)
	return err
}

const getBrandByID = `-- name: GetBrandByID :one
SELECT brand_id, name, created_at
FROM inventory.brand
WHERE brand_id = $1
`

func (q *Queries) GetBrandByID(ctx context.Context, brandID int64) (InventoryBrand, error) {
	row := q.db.QueryRow(ctx, getBrandByID, brandID)
	var i InventoryBrand
	err := row.Scan(&i.BrandID, &i.Name, &i.CreatedAt)
	return i, err
}

const getBrandsByIDs = `-- name: GetBrandsByIDs :many
SELECT brand_id, name, created_at
FROM inventory.brand
WHERE brand_id = ANY($1::bigint[])
`

func (q *Queries) GetBrandsByIDs(ctx context.Context, brandIds []int64) ([]InventoryBrand, error) {
	rows, err := q.db.Query(ctx, getBrandsByIDs, brandIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryBrand{}
	for rows.Next() {
		var i InventoryBrand
		if err := rows.Scan(&i.BrandID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesByIDs = `-- name: GetCategoriesByIDs :many
SELECT category_id, name, description, is_active, created_by, created_at, updated_by, updated_at
FROM inventory.category
WHERE category_id = ANY($1::bigint[])
`

func (q *Queries) GetCategoriesByIDs(ctx context.Context, categoryIds []int64) ([]InventoryCategory, error) {
	rows, err := q.db.Query(ctx, getCategoriesByIDs, categoryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryCategory{}
	for rows.Next() {
		var i InventoryCategory
		if err := rows.Scan(
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT category_id, name, description, is_active, created_by, created_at, updated_by, updated_at
FROM inventory.category
WHERE category_id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, categoryID int64) (InventoryCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, categoryID)
	var i InventoryCategory
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlavorProfileByID = `-- name: GetFlavorProfileByID :one
SELECT flavor_id, name, is_active, created_by, created_at, updated_by, updated_at
FROM inventory.flavor_profile
WHERE flavor_id = $1
`

func (q *Queries) GetFlavorProfileByID(ctx context.Context, flavorID int64) (InventoryFlavorProfile, error) {
	row := q.db.QueryRow(ctx, getFlavorProfileByID, flavorID)
	var i InventoryFlavorProfile
	err := row.Scan(
		&i.FlavorID,
		&i.Name,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getIngredientByID = `-- name: GetIngredientByID :one
SELECT ingredient_id, name, category_id, is_active, created_by, created_at, updated_by, updated_at, default_unit_id
FROM inventory.ingredient
WHERE ingredient_id = $1
`

func (q *Queries) GetIngredientByID(ctx context.Context, ingredientID int64) (InventoryIngredient, error) {
	row := q.db.QueryRow(ctx, getIngredientByID, ingredientID)
	var i InventoryIngredient
	err := row.Scan(
		&i.IngredientID,
		&i.Name,
		&i.CategoryID,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DefaultUnitID,
	)
	return i, err
}

const getIngredientsByIDs = `-- name: GetIngredientsByIDs :many
SELECT ingredient_id, name, category_id, is_active, created_by, created_at, updated_by, updated_at, default_unit_id
FROM inventory.ingredient
WHERE ingredient_id = ANY($1::bigint[])
`

func (q *Queries) GetIngredientsByIDs(ctx context.Context, ingredientIds []int64) ([]InventoryIngredient, error) {
	rows, err := q.db.Query(ctx, getIngredientsByIDs, ingredientIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryIngredient{}
	for rows.Next() {
		var i InventoryIngredient
		if err := rows.Scan(
			&i.IngredientID,
			&i.Name,
			&i.CategoryID,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DefaultUnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemByID = `-- name: GetItemByID :one
SELECT item_id, name, brand_id, upc12, upc14, category_id, created_by, created_at, updated_by, updated_at, unit_id
FROM inventory.item
WHERE item_id = $1
`

func (q *Queries) GetItemByID(ctx context.Context, itemID int64) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, getItemByID, itemID)
	var i InventoryItem
	err := row.Scan(
		&i.ItemID,
		&i.Name,
		&i.BrandID,
		&i.Upc12,
		&i.Upc14,
		&i.CategoryID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.UnitID,
	)
	return i, err
}

const getItemsByIDs = `-- name: GetItemsByIDs :many
SELECT item_id, name, brand_id, upc12, upc14, category_id, created_by, created_at, updated_by, updated_at, unit_id
FROM inventory.item
WHERE item_id = ANY($1::bigint[])
`

func (q *Queries) GetItemsByIDs(ctx context.Context, itemIds []int64) ([]InventoryItem, error) {
	rows, err := q.db.Query(ctx, getItemsByIDs, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryItem{}
	for rows.Next() {
		var i InventoryItem
		if err := rows.Scan(
			&i.ItemID,
			&i.Name,
			&i.BrandID,
			&i.Upc12,
			&i.Upc14,
			&i.CategoryID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.UnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNutrientTypeByID = `-- name: GetNutrientTypeByID :one
SELECT nutrient_id, name, unit, created_at
FROM inventory.nutrient_type
WHERE nutrient_id = $1
`

func (q *Queries) GetNutrientTypeByID(ctx context.Context, nutrientID int64) (InventoryNutrientType, error) {
	row := q.db.QueryRow(ctx, getNutrientTypeByID, nutrientID)
	var i InventoryNutrientType
	err := row.Scan(
		&i.NutrientID,
		&i.Name,
		&i.Unit,
		&i.CreatedAt,
	)
	return i, err
}

const getUnitByID = `-- name: GetUnitByID :one
SELECT unit_id, name, abbreviation, kind, is_active, created_by, created_at, updated_by, updated_at
FROM inventory.unit
WHERE unit_id = $1
`

func (q *Queries) GetUnitByID(ctx context.Context, unitID int64) (InventoryUnit, error) {
	row := q.db.QueryRow(ctx, getUnitByID, unitID)
	var i InventoryUnit
	err := row.Scan(
		&i.UnitID,
		&i.Name,
		&i.Abbreviation,
		&i.Kind,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnitByName = `-- name: GetUnitByName :one
SELECT unit_id, name, abbreviation, kind, is_active, created_by, created_at, updated_by, updated_at
FROM inventory.unit
WHERE lower(name) = lower($1) OR lower(abbreviation) = lower($1)
`

func (q *Queries) GetUnitByName(ctx context.Context, lower string) (InventoryUnit, error) {
	row := q.db.QueryRow(ctx, getUnitByName, lower)
	var i InventoryUnit
	err := row.Scan(
		&i.UnitID,
		&i.Name,
		&i.Abbreviation,
		&i.Kind,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnitsByIDs = `-- name: GetUnitsByIDs :many
SELECT unit_id, name, abbreviation, kind, is_active, created_by, created_at, updated_by, updated_at
FROM inventory.unit
WHERE unit_id = ANY($1::bigint[])
`

func (q *Queries) GetUnitsByIDs(ctx context.Context, unitIds []int64) ([]InventoryUnit, error) {
	rows, err := q.db.Query(ctx, getUnitsByIDs, unitIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryUnit{}
	for rows.Next() {
		var i InventoryUnit
		if err := rows.Scan(
			&i.UnitID,
			&i.Name,
			&i.Abbreviation,
			&i.Kind,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBrands = `-- name: ListBrands :many
SELECT brand_id, name, created_at
FROM inventory.brand
ORDER BY name
`

func (q *Queries) ListBrands(ctx context.Context) ([]InventoryBrand, error) {
	rows, err := q.db.Query(ctx, listBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryBrand{}
	for rows.Next() {
		var i InventoryBrand
		if err := rows.Scan(&i.BrandID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT category_id, name, description, is_active, created_by, created_at, updated_by, updated_at
FROM inventory.category
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]InventoryCategory, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryCategory{}
	for rows.Next() {
		var i InventoryCategory
		if err := rows.Scan(
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlavorProfiles = `-- name: ListFlavorProfiles :many
SELECT flavor_id, name, is_active, created_by, created_at, updated_by, updated_at
FROM inventory.flavor_profile
ORDER BY name
`

func (q *Queries) ListFlavorProfiles(ctx context.Context) ([]InventoryFlavorProfile, error) {
	rows, err := q.db.Query(ctx, listFlavorProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryFlavorProfile{}
	for rows.Next() {
		var i InventoryFlavorProfile
		if err := rows.Scan(
			&i.FlavorID,
			&i.Name,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoodFlavorsByItem = `-- name: ListFoodFlavorsByItem :many
SELECT fp.flavor_id, fp.name, ff.intensity
FROM inventory.food_flavor ff
JOIN inventory.flavor_profile fp ON ff.flavor_id = fp.flavor_id
WHERE ff.food_id = $1
ORDER BY fp.name
`

type ListFoodFlavorsByItemRow struct {
	FlavorID  int64  `json:"flavor_id"`
	Name      string `json:"name"`
	Intensity int16  `json:"intensity"`
}

func (q *Queries) ListFoodFlavorsByItem(ctx context.Context, foodID int64) ([]ListFoodFlavorsByItemRow, error) {
	rows, err := q.db.Query(ctx, listFoodFlavorsByItem, foodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFoodFlavorsByItemRow{}
	for rows.Next() {
		var i ListFoodFlavorsByItemRow
		if err := rows.Scan(&i.FlavorID, &i.Name, &i.Intensity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoodFlavorsByItems = `-- name: ListFoodFlavorsByItems :many
SELECT ff.food_id, fp.flavor_id, fp.name, ff.intensity
FROM inventory.food_flavor ff
JOIN inventory.flavor_profile fp ON ff.flavor_id = fp.flavor_id
WHERE ff.food_id = ANY($1::bigint[])
ORDER BY fp.name
`

type ListFoodFlavorsByItemsRow struct {
	FoodID    int64  `json:"food_id"`
	FlavorID  int64  `json:"flavor_id"`
	Name      string `json:"name"`
	Intensity int16  `json:"intensity"`
}

func (q *Queries) ListFoodFlavorsByItems(ctx context.Context, itemIds []int64) ([]ListFoodFlavorsByItemsRow, error) {
	rows, err := q.db.Query(ctx, listFoodFlavorsByItems, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFoodFlavorsByItemsRow{}
	for rows.Next() {
		var i ListFoodFlavorsByItemsRow
		if err := rows.Scan(
			&i.FoodID,
			&i.FlavorID,
			&i.Name,
			&i.Intensity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoodNutrientsByItem = `-- name: ListFoodNutrientsByItem :many
SELECT nt.nutrient_id, nt.name, nt.unit, fn.amount
FROM inventory.food_nutrient fn
JOIN inventory.nutrient_type nt ON fn.nutrient_id = nt.nutrient_id
WHERE fn.food_id = $1
ORDER BY nt.name
`

type ListFoodNutrientsByItemRow struct {
	NutrientID int64          `json:"nutrient_id"`
	Name       string         `json:"name"`
	Unit       pgtype.Text    `json:"unit"`
	Amount     pgtype.Numeric `json:"amount"`
}

func (q *Queries) ListFoodNutrientsByItem(ctx context.Context, foodID int64) ([]ListFoodNutrientsByItemRow, error) {
	rows, err := q.db.Query(ctx, listFoodNutrientsByItem, foodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFoodNutrientsByItemRow{}
	for rows.Next() {
		var i ListFoodNutrientsByItemRow
		if err := rows.Scan(
			&i.NutrientID,
			&i.Name,
			&i.Unit,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoodNutrientsByItems = `-- name: ListFoodNutrientsByItems :many
SELECT fn.food_id, nt.nutrient_id, nt.name, nt.unit, fn.amount
FROM inventory.food_nutrient fn
JOIN inventory.nutrient_type nt ON fn.nutrient_id = nt.nutrient_id
WHERE fn.food_id = ANY($1::bigint[])
ORDER BY nt.name
`

type ListFoodNutrientsByItemsRow struct {
	FoodID     int64          `json:"food_id"`
	NutrientID int64          `json:"nutrient_id"`
	Name       string         `json:"name"`
	Unit       pgtype.Text    `json:"unit"`
	Amount     pgtype.Numeric `json:"amount"`
}

func (q *Queries) ListFoodNutrientsByItems(ctx context.Context, itemIds []int64) ([]ListFoodNutrientsByItemsRow, error) {
	rows, err := q.db.Query(ctx, listFoodNutrientsByItems, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFoodNutrientsByItemsRow{}
	for rows.Next() {
		var i ListFoodNutrientsByItemsRow
		if err := rows.Scan(
			&i.FoodID,
			&i.NutrientID,
			&i.Name,
			&i.Unit,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredients = `-- name: ListIngredients :many
SELECT ingredient_id, name, category_id, is_active, created_by, created_at, updated_by, updated_at, default_unit_id
FROM inventory.ingredient
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListIngredientsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListIngredients(ctx context.Context, arg ListIngredientsParams) ([]InventoryIngredient, error) {
	rows, err := q.db.Query(ctx, listIngredients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryIngredient{}
	for rows.Next() {
		var i InventoryIngredient
		if err := rows.Scan(
			&i.IngredientID,
			&i.Name,
			&i.CategoryID,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DefaultUnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT item_id, name, brand_id, upc12, upc14, category_id, created_by, created_at, updated_by, updated_at, unit_id
FROM inventory.item
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListItemsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]InventoryItem, error) {
	rows, err := q.db.Query(ctx, listItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryItem{}
	for rows.Next() {
		var i InventoryItem
		if err := rows.Scan(
			&i.ItemID,
			&i.Name,
			&i.BrandID,
			&i.Upc12,
			&i.Upc14,
			&i.CategoryID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.UnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNutrientTypes = `-- name: ListNutrientTypes :many
SELECT nutrient_id, name, unit, created_at
FROM inventory.nutrient_type
ORDER BY name
`

func (q *Queries) ListNutrientTypes(ctx context.Context) ([]InventoryNutrientType, error) {
	rows, err := q.db.Query(ctx, listNutrientTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryNutrientType{}
	for rows.Next() {
		var i InventoryNutrientType
		if err := rows.Scan(
			&i.NutrientID,
			&i.Name,
			&i.Unit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnits = `-- name: ListUnits :many
SELECT unit_id, name, abbreviation, kind, is_active, created_by, created_at, updated_by, updated_at
FROM inventory.unit
ORDER BY kind, name
`

func (q *Queries) ListUnits(ctx context.Context) ([]InventoryUnit, error) {
	rows, err := q.db.Query(ctx, listUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryUnit{}
	for rows.Next() {
		var i InventoryUnit
		if err := rows.Scan(
			&i.UnitID,
			&i.Name,
			&i.Abbreviation,
			&i.Kind,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBrand = `-- name: UpdateBrand :one
UPDATE inventory.brand
SET name = $2
WHERE brand_id = $1
RETURNING brand_id, name, created_at
`

type UpdateBrandParams struct {
	BrandID int64  `json:"brand_id"`
	Name    string `json:"name"`
}

func (q *Queries) UpdateBrand(ctx context.Context, arg UpdateBrandParams) (InventoryBrand, error) {
	row := q.db.QueryRow(ctx, updateBrand, arg.BrandID, arg.Name)
	var i InventoryBrand
	err := row.Scan(&i.BrandID, &i.Name, &i.CreatedAt)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE inventory.category
SET name        = $2,
    description = $3,
    is_active   = $4,
    updated_by  = $5,
    updated_at  = now()
WHERE category_id = $1
RETURNING category_id, name, description, is_active, created_by, created_at, updated_by, updated_at
`

type UpdateCategoryParams struct {
	CategoryID  int64       `json:"category_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	UpdatedBy   pgtype.Text `json:"updated_by"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (InventoryCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.UpdatedBy,
	)
	var i InventoryCategory
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFlavorProfile = `-- name: UpdateFlavorProfile :one
UPDATE inventory.flavor_profile
SET name       = $2,
    is_active  = $3,
    updated_by = $4,
    updated_at = now()
WHERE flavor_id = $1
RETURNING flavor_id, name, is_active, created_by, created_at, updated_by, updated_at
`

type UpdateFlavorProfileParams struct {
	FlavorID  int64       `json:"flavor_id"`
	Name      string      `json:"name"`
	IsActive  bool        `json:"is_active"`
	UpdatedBy pgtype.Text `json:"updated_by"`
}

func (q *Queries) UpdateFlavorProfile(ctx context.Context, arg UpdateFlavorProfileParams) (InventoryFlavorProfile, error) {
	row := q.db.QueryRow(ctx, updateFlavorProfile,
		arg.FlavorID,
		arg.Name,
		arg.IsActive,
		arg.UpdatedBy,
	)
	var i InventoryFlavorProfile
	err := row.Scan(
		&i.FlavorID,
		&i.Name,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIngredient = `-- name: UpdateIngredient :one
UPDATE inventory.ingredient
SET name            = $2,
    category_id     = $3,
    default_unit_id = $4,
    is_active       = $5,
    updated_by   = $6,
    updated_at   = now()
WHERE ingredient_id = $1
RETURNING ingredient_id, name, category_id, is_active, created_by, created_at, updated_by, updated_at, default_unit_id
`

type UpdateIngredientParams struct {
	IngredientID  int64       `json:"ingredient_id"`
	Name          string      `json:"name"`
	CategoryID    pgtype.Int8 `json:"category_id"`
	DefaultUnitID pgtype.Int8 `json:"default_unit_id"`
	IsActive      bool        `json:"is_active"`
	UpdatedBy     pgtype.Text `json:"updated_by"`
}

func (q *Queries) UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (InventoryIngredient, error) {
	row := q.db.QueryRow(ctx, updateIngredient,
		arg.IngredientID,
		arg.Name,
		arg.CategoryID,
		arg.DefaultUnitID,
		arg.IsActive,
		arg.UpdatedBy,
	)
	var i InventoryIngredient
	err := row.Scan(
		&i.IngredientID,
		&i.Name,
		&i.CategoryID,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DefaultUnitID,
	)
	return i, err
}

const updateItem = `-- name: UpdateItem :exec
UPDATE inventory.item
SET name        = $2,
    brand_id    = $3,
    upc12       = $4,
    upc14       = $5,
    category_id = $6,
    unit_id     = $7,
    updated_by  = $8,
    updated_at  = now()
WHERE item_id = $1
`

type UpdateItemParams struct {
	ItemID     int64       `json:"item_id"`
	Name       string      `json:"name"`
	BrandID    pgtype.Int8 `json:"brand_id"`
	Upc12      pgtype.Text `json:"upc12"`
	Upc14      pgtype.Text `json:"upc14"`
	CategoryID int64       `json:"category_id"`
	UnitID     int64       `json:"unit_id"`
	UpdatedBy  pgtype.Text `json:"updated_by"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) error {
	_, err := q.db.Exec(ctx, updateItem,
		arg.ItemID,
		arg.Name,
		arg.BrandID,
		arg.Upc12,
		arg.Upc14,
		arg.CategoryID,
		arg.UnitID,
		arg.UpdatedBy,
	)
	return err
}

const updateNutrientType = `-- name: UpdateNutrientType :one
UPDATE inventory.nutrient_type
SET name = $2,
    unit = $3
WHERE nutrient_id = $1
RETURNING nutrient_id, name, unit, created_at
`

type UpdateNutrientTypeParams struct {
	NutrientID int64       `json:"nutrient_id"`
	Name       string      `json:"name"`
	Unit       pgtype.Text `json:"unit"`
}

func (q *Queries) UpdateNutrientType(ctx context.Context, arg UpdateNutrientTypeParams) (InventoryNutrientType, error) {
	row := q.db.QueryRow(ctx, updateNutrientType, arg.NutrientID, arg.Name, arg.Unit)
	var i InventoryNutrientType
	err := row.Scan(
		&i.NutrientID,
		&i.Name,
		&i.Unit,
		&i.CreatedAt,
	)
	return i, err
}
