DROP SCHEMA IF EXISTS identity CASCADE;
DROP SCHEMA IF EXISTS inventory CASCADE;
DROP SCHEMA IF EXISTS wine CASCADE;
DROP SCHEMA IF EXISTS recipe CASCADE;
DROP SCHEMA IF EXISTS mealplan CASCADE;
DROP SCHEMA IF EXISTS grocery CASCADE;
