-- 0046_ingredient_dedupe_seed.up.sql
-- Generic-ingredient layer, phase 1 (data half):
--
-- 1. A normalized unique index guarantees free-create can never produce
--    "47 entries for carrots" — whitespace-collapsed, case-folded names
--    collide at the DB level regardless of who types them.
-- 2. The starter ingredient catalog: ~270 common generic ingredients
--    covering every category. Names are intentionally one-per-concept —
--    form/preparation ("minced", "diced", "dried") lives in recipe notes,
--    not the ingredient name. This list was LLM-curated and is reviewed
--    in the PR diff.

CREATE UNIQUE INDEX idx_ingredient_name_norm
    ON inventory.ingredient (lower(btrim(regexp_replace(name, '\s+', ' ', 'g'))));

INSERT INTO inventory.ingredient (name, category_id, default_unit_id, created_by)
SELECT v.name, c.category_id, u.unit_id, 'seed'
FROM (VALUES
    -- Produce
    ('apple', 'Produce', 'each'),
    ('arugula', 'Produce', 'bunch'),
    ('asparagus', 'Produce', 'bunch'),
    ('avocado', 'Produce', 'each'),
    ('banana', 'Produce', 'each'),
    ('basil', 'Produce', 'bunch'),
    ('beets', 'Produce', 'each'),
    ('bell pepper', 'Produce', 'each'),
    ('blackberries', 'Produce', 'each'),
    ('blueberries', 'Produce', 'each'),
    ('broccoli', 'Produce', 'each'),
    ('brussels sprouts', 'Produce', 'each'),
    ('butternut squash', 'Produce', 'each'),
    ('cabbage', 'Produce', 'each'),
    ('carrots', 'Produce', 'each'),
    ('cauliflower', 'Produce', 'each'),
    ('celery', 'Produce', 'bunch'),
    ('cherry tomatoes', 'Produce', 'each'),
    ('chives', 'Produce', 'bunch'),
    ('cilantro', 'Produce', 'bunch'),
    ('corn', 'Produce', 'each'),
    ('cucumber', 'Produce', 'each'),
    ('dill', 'Produce', 'bunch'),
    ('eggplant', 'Produce', 'each'),
    ('garlic', 'Produce', 'clove'),
    ('ginger root', 'Produce', 'each'),
    ('grapes', 'Produce', 'each'),
    ('green beans', 'Produce', 'each'),
    ('green onion', 'Produce', 'bunch'),
    ('habanero pepper', 'Produce', 'each'),
    ('iceberg lettuce', 'Produce', 'each'),
    ('jalapeno', 'Produce', 'each'),
    ('kale', 'Produce', 'bunch'),
    ('leek', 'Produce', 'each'),
    ('lemon', 'Produce', 'each'),
    ('lime', 'Produce', 'each'),
    ('mango', 'Produce', 'each'),
    ('mint', 'Produce', 'bunch'),
    ('mushrooms', 'Produce', 'each'),
    ('onion', 'Produce', 'each'),
    ('orange', 'Produce', 'each'),
    ('parsley', 'Produce', 'bunch'),
    ('peach', 'Produce', 'each'),
    ('pear', 'Produce', 'each'),
    ('pineapple', 'Produce', 'each'),
    ('plum', 'Produce', 'each'),
    ('poblano pepper', 'Produce', 'each'),
    ('potato', 'Produce', 'each'),
    ('radishes', 'Produce', 'each'),
    ('raspberries', 'Produce', 'each'),
    ('red onion', 'Produce', 'each'),
    ('romaine lettuce', 'Produce', 'each'),
    ('rosemary', 'Produce', 'bunch'),
    ('sage', 'Produce', 'bunch'),
    ('serrano pepper', 'Produce', 'each'),
    ('shallot', 'Produce', 'each'),
    ('snow peas', 'Produce', 'each'),
    ('spinach', 'Produce', 'bunch'),
    ('strawberries', 'Produce', 'each'),
    ('sugar snap peas', 'Produce', 'each'),
    ('sweet potato', 'Produce', 'each'),
    ('thyme', 'Produce', 'bunch'),
    ('tofu', 'Produce', 'package'),
    ('tomato', 'Produce', 'each'),
    ('zucchini', 'Produce', 'each'),
    -- Dairy
    ('almond milk', 'Dairy', 'cup'),
    ('american cheese', 'Dairy', 'slice'),
    ('blue cheese', 'Dairy', 'ounce'),
    ('butter', 'Dairy', 'tablespoon'),
    ('buttermilk', 'Dairy', 'cup'),
    ('cheddar cheese', 'Dairy', 'cup'),
    ('cottage cheese', 'Dairy', 'cup'),
    ('cream cheese', 'Dairy', 'ounce'),
    ('eggs', 'Dairy', 'each'),
    ('feta cheese', 'Dairy', 'ounce'),
    ('goat cheese', 'Dairy', 'ounce'),
    ('greek yogurt', 'Dairy', 'cup'),
    ('half and half', 'Dairy', 'cup'),
    ('heavy cream', 'Dairy', 'cup'),
    ('milk', 'Dairy', 'cup'),
    ('monterey jack cheese', 'Dairy', 'cup'),
    ('mozzarella cheese', 'Dairy', 'cup'),
    ('oat milk', 'Dairy', 'cup'),
    ('parmesan cheese', 'Dairy', 'cup'),
    ('pepper jack cheese', 'Dairy', 'cup'),
    ('provolone cheese', 'Dairy', 'slice'),
    ('queso fresco', 'Dairy', 'ounce'),
    ('ricotta cheese', 'Dairy', 'cup'),
    ('sour cream', 'Dairy', 'cup'),
    ('soy milk', 'Dairy', 'cup'),
    ('swiss cheese', 'Dairy', 'slice'),
    ('whipped cream', 'Dairy', 'cup'),
    ('yogurt', 'Dairy', 'cup'),
    -- Meat
    ('bacon', 'Meat', 'package'),
    ('brisket', 'Meat', 'pound'),
    ('catfish', 'Meat', 'pound'),
    ('chicken breast', 'Meat', 'pound'),
    ('chicken drumsticks', 'Meat', 'pound'),
    ('chicken thighs', 'Meat', 'pound'),
    ('chicken wings', 'Meat', 'pound'),
    ('chorizo', 'Meat', 'pound'),
    ('clams', 'Meat', 'pound'),
    ('cod', 'Meat', 'pound'),
    ('crab meat', 'Meat', 'pound'),
    ('deli ham', 'Meat', 'pound'),
    ('deli turkey', 'Meat', 'pound'),
    ('ground beef', 'Meat', 'pound'),
    ('ground chicken', 'Meat', 'pound'),
    ('ground lamb', 'Meat', 'pound'),
    ('ground pork', 'Meat', 'pound'),
    ('ground turkey', 'Meat', 'pound'),
    ('halibut', 'Meat', 'pound'),
    ('ham', 'Meat', 'pound'),
    ('hot dogs', 'Meat', 'package'),
    ('italian sausage', 'Meat', 'pound'),
    ('lamb chops', 'Meat', 'pound'),
    ('lobster', 'Meat', 'each'),
    ('mahi mahi', 'Meat', 'pound'),
    ('mussels', 'Meat', 'pound'),
    ('pepperoni', 'Meat', 'package'),
    ('pork chops', 'Meat', 'each'),
    ('pork loin', 'Meat', 'pound'),
    ('pork shoulder', 'Meat', 'pound'),
    ('ribeye steak', 'Meat', 'each'),
    ('salami', 'Meat', 'package'),
    ('salmon', 'Meat', 'pound'),
    ('sausage links', 'Meat', 'package'),
    ('scallops', 'Meat', 'pound'),
    ('shrimp', 'Meat', 'pound'),
    ('sirloin steak', 'Meat', 'each'),
    ('steak', 'Meat', 'pound'),
    ('tilapia', 'Meat', 'pound'),
    ('trout', 'Meat', 'pound'),
    ('tuna steak', 'Meat', 'pound'),
    ('turkey breast', 'Meat', 'pound'),
    ('whole chicken', 'Meat', 'each'),
    ('whole turkey', 'Meat', 'each'),
    -- Bakery
    ('bagels', 'Bakery', 'each'),
    ('baguette', 'Bakery', 'each'),
    ('cinnamon rolls', 'Bakery', 'package'),
    ('corn tortillas', 'Bakery', 'each'),
    ('croissants', 'Bakery', 'each'),
    ('dinner rolls', 'Bakery', 'package'),
    ('english muffins', 'Bakery', 'package'),
    ('flatbread', 'Bakery', 'each'),
    ('flour tortillas', 'Bakery', 'each'),
    ('hamburger buns', 'Bakery', 'package'),
    ('hot dog buns', 'Bakery', 'package'),
    ('naan', 'Bakery', 'each'),
    ('pie crust', 'Bakery', 'each'),
    ('pita bread', 'Bakery', 'each'),
    ('pizza dough', 'Bakery', 'each'),
    ('puff pastry', 'Bakery', 'package'),
    ('sandwich bread', 'Bakery', 'slice'),
    ('sourdough bread', 'Bakery', 'slice'),
    ('taco shells', 'Bakery', 'package'),
    -- Pantry: baking & sweets
    ('active dry yeast', 'Pantry', 'package'),
    ('agave nectar', 'Pantry', 'tablespoon'),
    ('all-purpose flour', 'Pantry', 'cup'),
    ('almond extract', 'Pantry', 'teaspoon'),
    ('almond flour', 'Pantry', 'cup'),
    ('baking powder', 'Pantry', 'teaspoon'),
    ('baking soda', 'Pantry', 'teaspoon'),
    ('biscuit mix', 'Pantry', 'cup'),
    ('bread flour', 'Pantry', 'cup'),
    ('brownie mix', 'Pantry', 'package'),
    ('brown sugar', 'Pantry', 'cup'),
    ('butterscotch chips', 'Pantry', 'cup'),
    ('cake flour', 'Pantry', 'cup'),
    ('cake mix', 'Pantry', 'package'),
    ('chocolate chips', 'Pantry', 'cup'),
    ('cocoa powder', 'Pantry', 'cup'),
    ('coconut flour', 'Pantry', 'cup'),
    ('cornbread mix', 'Pantry', 'package'),
    ('cornmeal', 'Pantry', 'cup'),
    ('corn syrup', 'Pantry', 'cup'),
    ('cornstarch', 'Pantry', 'tablespoon'),
    ('cream of tartar', 'Pantry', 'teaspoon'),
    ('espresso powder', 'Pantry', 'teaspoon'),
    ('food coloring', 'Pantry', 'each'),
    ('frosting', 'Pantry', 'can'),
    ('gelatin', 'Pantry', 'package'),
    ('gluten-free flour', 'Pantry', 'cup'),
    ('graham cracker crumbs', 'Pantry', 'cup'),
    ('maraschino cherries', 'Pantry', 'each'),
    ('marshmallow creme', 'Pantry', 'cup'),
    ('marshmallows', 'Pantry', 'cup'),
    ('masa harina', 'Pantry', 'cup'),
    ('molasses', 'Pantry', 'tablespoon'),
    ('muffin mix', 'Pantry', 'package'),
    ('pancake mix', 'Pantry', 'cup'),
    ('pie filling', 'Pantry', 'can'),
    ('powdered milk', 'Pantry', 'cup'),
    ('powdered sugar', 'Pantry', 'cup'),
    ('pudding mix', 'Pantry', 'package'),
    ('self-rising flour', 'Pantry', 'cup'),
    ('shredded coconut', 'Pantry', 'cup'),
    ('shortening', 'Pantry', 'cup'),
    ('sprinkles', 'Pantry', 'tablespoon'),
    ('sugar', 'Pantry', 'cup'),
    ('vanilla bean', 'Pantry', 'each'),
    ('vanilla extract', 'Pantry', 'teaspoon'),
    ('waffle mix', 'Pantry', 'cup'),
    ('white chocolate chips', 'Pantry', 'cup'),
    ('whole wheat flour', 'Pantry', 'cup'),
    -- Pantry: oils, vinegars & condiments
    ('alfredo sauce', 'Pantry', 'cup'),
    ('apple cider vinegar', 'Pantry', 'tablespoon'),
    ('avocado oil', 'Pantry', 'tablespoon'),
    ('balsamic glaze', 'Pantry', 'tablespoon'),
    ('balsamic vinegar', 'Pantry', 'tablespoon'),
    ('bbq sauce', 'Pantry', 'tablespoon'),
    ('buffalo sauce', 'Pantry', 'tablespoon'),
    ('caesar dressing', 'Pantry', 'tablespoon'),
    ('canola oil', 'Pantry', 'tablespoon'),
    ('cocktail sauce', 'Pantry', 'tablespoon'),
    ('coconut oil', 'Pantry', 'tablespoon'),
    ('cooking spray', 'Pantry', 'each'),
    ('dijon mustard', 'Pantry', 'tablespoon'),
    ('fish sauce', 'Pantry', 'teaspoon'),
    ('gravy mix', 'Pantry', 'package'),
    ('hoisin sauce', 'Pantry', 'tablespoon'),
    ('honey', 'Pantry', 'tablespoon'),
    ('honey mustard dressing', 'Pantry', 'tablespoon'),
    ('hot sauce', 'Pantry', 'teaspoon'),
    ('italian dressing', 'Pantry', 'tablespoon'),
    ('ketchup', 'Pantry', 'tablespoon'),
    ('maple syrup', 'Pantry', 'tablespoon'),
    ('marinara sauce', 'Pantry', 'cup'),
    ('mayonnaise', 'Pantry', 'tablespoon'),
    ('olive oil', 'Pantry', 'tablespoon'),
    ('oyster sauce', 'Pantry', 'tablespoon'),
    ('peanut oil', 'Pantry', 'tablespoon'),
    ('pesto', 'Pantry', 'tablespoon'),
    ('pizza sauce', 'Pantry', 'cup'),
    ('ranch dressing', 'Pantry', 'tablespoon'),
    ('red wine vinegar', 'Pantry', 'tablespoon'),
    ('rice vinegar', 'Pantry', 'tablespoon'),
    ('salsa', 'Pantry', 'cup'),
    ('sesame oil', 'Pantry', 'teaspoon'),
    ('soy sauce', 'Pantry', 'tablespoon'),
    ('sriracha', 'Pantry', 'teaspoon'),
    ('sweet chili sauce', 'Pantry', 'tablespoon'),
    ('tamari', 'Pantry', 'tablespoon'),
    ('tartar sauce', 'Pantry', 'tablespoon'),
    ('teriyaki sauce', 'Pantry', 'tablespoon'),
    ('vegetable oil', 'Pantry', 'tablespoon'),
    ('white vinegar', 'Pantry', 'tablespoon'),
    ('whole grain mustard', 'Pantry', 'tablespoon'),
    ('worcestershire sauce', 'Pantry', 'teaspoon'),
    ('yellow mustard', 'Pantry', 'tablespoon'),
    -- Pantry: canned & jarred
    ('anchovies', 'Pantry', 'can'),
    ('applesauce', 'Pantry', 'cup'),
    ('artichoke hearts', 'Pantry', 'can'),
    ('bamboo shoots', 'Pantry', 'can'),
    ('beef broth', 'Pantry', 'cup'),
    ('black beans', 'Pantry', 'can'),
    ('black olives', 'Pantry', 'can'),
    ('cannellini beans', 'Pantry', 'can'),
    ('canned chicken', 'Pantry', 'can'),
    ('canned corn', 'Pantry', 'can'),
    ('canned green beans', 'Pantry', 'can'),
    ('canned jalapenos', 'Pantry', 'each'),
    ('canned peaches', 'Pantry', 'can'),
    ('canned pears', 'Pantry', 'can'),
    ('canned salmon', 'Pantry', 'can'),
    ('capers', 'Pantry', 'tablespoon'),
    ('chicken broth', 'Pantry', 'cup'),
    ('chickpeas', 'Pantry', 'can'),
    ('chipotle peppers in adobo', 'Pantry', 'can'),
    ('coconut milk', 'Pantry', 'can'),
    ('cranberry sauce', 'Pantry', 'can'),
    ('cream of chicken soup', 'Pantry', 'can'),
    ('cream of mushroom soup', 'Pantry', 'can'),
    ('crushed tomatoes', 'Pantry', 'can'),
    ('diced tomatoes', 'Pantry', 'can'),
    ('evaporated milk', 'Pantry', 'can'),
    ('fruit cocktail', 'Pantry', 'can'),
    ('green olives', 'Pantry', 'can'),
    ('kidney beans', 'Pantry', 'can'),
    ('mandarin oranges', 'Pantry', 'can'),
    ('pickles', 'Pantry', 'each'),
    ('pimientos', 'Pantry', 'each'),
    ('pineapple chunks', 'Pantry', 'can'),
    ('pinto beans', 'Pantry', 'can'),
    ('pumpkin puree', 'Pantry', 'can'),
    ('refried beans', 'Pantry', 'can'),
    ('roasted red peppers', 'Pantry', 'each'),
    ('sauerkraut', 'Pantry', 'cup'),
    ('sun-dried tomatoes', 'Pantry', 'each'),
    ('sweetened condensed milk', 'Pantry', 'can'),
    ('tomato paste', 'Pantry', 'tablespoon'),
    ('tomato puree', 'Pantry', 'can'),
    ('tomato sauce', 'Pantry', 'can'),
    ('vegetable broth', 'Pantry', 'cup'),
    ('water chestnuts', 'Pantry', 'can'),
    -- Pantry: grains & pasta
    ('arborio rice', 'Pantry', 'cup'),
    ('barley', 'Pantry', 'cup'),
    ('basmati rice', 'Pantry', 'cup'),
    ('brown rice', 'Pantry', 'cup'),
    ('bulgur', 'Pantry', 'cup'),
    ('couscous', 'Pantry', 'cup'),
    ('egg noodles', 'Pantry', 'ounce'),
    ('elbow macaroni', 'Pantry', 'ounce'),
    ('farro', 'Pantry', 'cup'),
    ('fettuccine', 'Pantry', 'ounce'),
    ('grits', 'Pantry', 'cup'),
    ('jasmine rice', 'Pantry', 'cup'),
    ('lasagna noodles', 'Pantry', 'each'),
    ('linguine', 'Pantry', 'ounce'),
    ('orzo', 'Pantry', 'cup'),
    ('penne', 'Pantry', 'ounce'),
    ('polenta', 'Pantry', 'cup'),
    ('quinoa', 'Pantry', 'cup'),
    ('ramen noodles', 'Pantry', 'package'),
    ('rice noodles', 'Pantry', 'ounce'),
    ('rolled oats', 'Pantry', 'cup'),
    ('spaghetti', 'Pantry', 'ounce'),
    ('steel-cut oats', 'Pantry', 'cup'),
    ('white rice', 'Pantry', 'cup'),
    -- Pantry: breakfast & snacks
    ('almond butter', 'Pantry', 'tablespoon'),
    ('apple butter', 'Pantry', 'tablespoon'),
    ('breadsticks', 'Pantry', 'package'),
    ('cereal', 'Pantry', 'cup'),
    ('crackers', 'Pantry', 'package'),
    ('croutons', 'Pantry', 'cup'),
    ('graham crackers', 'Pantry', 'package'),
    ('granola', 'Pantry', 'cup'),
    ('jelly', 'Pantry', 'tablespoon'),
    ('nutella', 'Pantry', 'tablespoon'),
    ('peanut butter', 'Pantry', 'tablespoon'),
    ('popcorn kernels', 'Pantry', 'cup'),
    ('potato chips', 'Pantry', 'package'),
    ('pretzels', 'Pantry', 'package'),
    ('saltine crackers', 'Pantry', 'package'),
    ('strawberry jam', 'Pantry', 'tablespoon'),
    ('stuffing mix', 'Pantry', 'package'),
    ('tortilla chips', 'Pantry', 'package'),
    -- Pantry: nuts, seeds & dried fruit
    ('almonds', 'Pantry', 'cup'),
    ('cashews', 'Pantry', 'cup'),
    ('chia seeds', 'Pantry', 'tablespoon'),
    ('dates', 'Pantry', 'cup'),
    ('dried apricots', 'Pantry', 'cup'),
    ('dried cranberries', 'Pantry', 'cup'),
    ('dried figs', 'Pantry', 'cup'),
    ('flax seeds', 'Pantry', 'tablespoon'),
    ('hazelnuts', 'Pantry', 'cup'),
    ('mixed nuts', 'Pantry', 'cup'),
    ('peanuts', 'Pantry', 'cup'),
    ('pecans', 'Pantry', 'cup'),
    ('pine nuts', 'Pantry', 'tablespoon'),
    ('pistachios', 'Pantry', 'cup'),
    ('poppy seeds', 'Pantry', 'tablespoon'),
    ('prunes', 'Pantry', 'cup'),
    ('pumpkin seeds', 'Pantry', 'cup'),
    ('raisins', 'Pantry', 'cup'),
    ('sesame seeds', 'Pantry', 'tablespoon'),
    ('sunflower seeds', 'Pantry', 'cup'),
    ('walnuts', 'Pantry', 'cup'),
    -- Pantry: spices & seasoning
    ('allspice', 'Pantry', 'teaspoon'),
    ('bay leaves', 'Pantry', 'each'),
    ('black pepper', 'Pantry', 'teaspoon'),
    ('cajun seasoning', 'Pantry', 'teaspoon'),
    ('cardamom', 'Pantry', 'teaspoon'),
    ('cayenne pepper', 'Pantry', 'teaspoon'),
    ('celery salt', 'Pantry', 'teaspoon'),
    ('chili powder', 'Pantry', 'teaspoon'),
    ('curry powder', 'Pantry', 'teaspoon'),
    ('dried dill', 'Pantry', 'teaspoon'),
    ('dried oregano', 'Pantry', 'teaspoon'),
    ('everything bagel seasoning', 'Pantry', 'teaspoon'),
    ('fennel seeds', 'Pantry', 'teaspoon'),
    ('garlic powder', 'Pantry', 'teaspoon'),
    ('ground cinnamon', 'Pantry', 'teaspoon'),
    ('ground cloves', 'Pantry', 'teaspoon'),
    ('ground coriander', 'Pantry', 'teaspoon'),
    ('ground cumin', 'Pantry', 'teaspoon'),
    ('ground ginger', 'Pantry', 'teaspoon'),
    ('ground nutmeg', 'Pantry', 'teaspoon'),
    ('italian seasoning', 'Pantry', 'teaspoon'),
    ('kosher salt', 'Pantry', 'teaspoon'),
    ('lemon pepper', 'Pantry', 'teaspoon'),
    ('mustard powder', 'Pantry', 'teaspoon'),
    ('old bay seasoning', 'Pantry', 'teaspoon'),
    ('onion powder', 'Pantry', 'teaspoon'),
    ('paprika', 'Pantry', 'teaspoon'),
    ('poultry seasoning', 'Pantry', 'teaspoon'),
    ('pumpkin pie spice', 'Pantry', 'teaspoon'),
    ('ranch seasoning mix', 'Pantry', 'package'),
    ('red pepper flakes', 'Pantry', 'teaspoon'),
    ('salt', 'Pantry', 'teaspoon'),
    ('seasoned salt', 'Pantry', 'teaspoon'),
    ('smoked paprika', 'Pantry', 'teaspoon'),
    ('steak seasoning', 'Pantry', 'teaspoon'),
    ('taco seasoning', 'Pantry', 'package'),
    ('turmeric', 'Pantry', 'teaspoon'),
    -- Pantry: international & misc
    ('beef bouillon', 'Pantry', 'each'),
    ('bread crumbs', 'Pantry', 'cup'),
    ('chicken bouillon', 'Pantry', 'each'),
    ('coconut cream', 'Pantry', 'can'),
    ('coffee', 'Pantry', 'cup'),
    ('curry paste', 'Pantry', 'tablespoon'),
    ('gochujang', 'Pantry', 'tablespoon'),
    ('harissa', 'Pantry', 'tablespoon'),
    ('hot cocoa mix', 'Pantry', 'package'),
    ('kimchi', 'Pantry', 'cup'),
    ('miso paste', 'Pantry', 'tablespoon'),
    ('mirin', 'Pantry', 'tablespoon'),
    ('nori', 'Pantry', 'each'),
    ('panko breadcrumbs', 'Pantry', 'cup'),
    ('rice paper', 'Pantry', 'each'),
    ('tahini', 'Pantry', 'tablespoon'),
    ('tea bags', 'Pantry', 'each'),
    ('wonton wrappers', 'Pantry', 'package')
) AS v(name, category_name, unit_name)
JOIN inventory.category c ON c.name = v.category_name
LEFT JOIN inventory.unit u ON u.name = v.unit_name;
