// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AddEventRecipe(ctx context.Context, arg AddEventRecipeParams) (EventEventRecipe, error)
	CountFoodEvents(ctx context.Context, householdID int64) (int64, error)
	CreateFoodEvent(ctx context.Context, arg CreateFoodEventParams) (EventFoodEvent, error)
	DeleteEventRecipe(ctx context.Context, arg DeleteEventRecipeParams) error
	DeleteFoodEvent(ctx context.Context, arg DeleteFoodEventParams) error
	GetEventRecipeByID(ctx context.Context, arg GetEventRecipeByIDParams) (EventEventRecipe, error)
	GetFoodEventByID(ctx context.Context, arg GetFoodEventByIDParams) (EventFoodEvent, error)
	ListEventRecipesByEvents(ctx context.Context, arg ListEventRecipesByEventsParams) ([]EventEventRecipe, error)
	ListEventRecipesForEvent(ctx context.Context, arg ListEventRecipesForEventParams) ([]EventEventRecipe, error)
	ListFoodEvents(ctx context.Context, arg ListFoodEventsParams) ([]EventFoodEvent, error)
	// Invite-accept merge: repoint all of the source household's events. Zero
	// rows is not an error (the source may have had none).
	ReassignFoodEventsToHousehold(ctx context.Context, arg ReassignFoodEventsToHouseholdParams) error
	UpdateEventRecipe(ctx context.Context, arg UpdateEventRecipeParams) error
	UpdateFoodEvent(ctx context.Context, arg UpdateFoodEventParams) error
}

var _ Querier = (*Queries)(nil)
