// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	// Marks the delta as seen against the recipe's current version — clears
	// the stale flag until the next canonical edit.
	AcknowledgeRecipeDelta(ctx context.Context, arg AcknowledgeRecipeDeltaParams) (int64, error)
	AddDeltaItem(ctx context.Context, arg AddDeltaItemParams) (RecipeRecipeDeltaItem, error)
	AddDeltaStep(ctx context.Context, arg AddDeltaStepParams) (RecipeRecipeDeltaStep, error)
	AddRecipeCategories(ctx context.Context, arg AddRecipeCategoriesParams) error
	AddRecipeItem(ctx context.Context, arg AddRecipeItemParams) error
	AddRecipeStep(ctx context.Context, arg AddRecipeStepParams) (RecipeRecipeStep, error)
	ClearRecipeCategories(ctx context.Context, recipeID int64) error
	// Drops a recipe's embedding (stale-failure bookkeeping; the sweep will
	// retry on its next pass since embedding becomes NULL).
	ClearRecipeEmbedding(ctx context.Context, recipeID int64) error
	CountCategoriesInGroup(ctx context.Context, categoryGroupID int64) (int64, error)
	CountRecipes(ctx context.Context, isActive bool) (int64, error)
	CountSearchRecipes(ctx context.Context, arg CountSearchRecipesParams) (int64, error)
	// The un-paged match count for the same semantic-mode filters (no
	// engagement args — they only affect ordering).
	CountSearchRecipesSemantic(ctx context.Context, arg CountSearchRecipesSemanticParams) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (RecipeCategory, error)
	// ---------- recipe categories (0035) ----------
	CreateCategoryGroup(ctx context.Context, arg CreateCategoryGroupParams) (RecipeCategoryGroup, error)
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (RecipeRecipe, error)
	DeleteCategory(ctx context.Context, categoryID int64) error
	DeleteCategoryGroup(ctx context.Context, categoryGroupID int64) error
	DeleteRecipe(ctx context.Context, recipeID int64) error
	DeleteRecipeDelta(ctx context.Context, arg DeleteRecipeDeltaParams) (int64, error)
	DeleteRecipeItems(ctx context.Context, recipeID int64) error
	DeleteRecipeStep(ctx context.Context, stepID int64) error
	DeleteRecipeSteps(ctx context.Context, recipeID int64) error
	GetCategoryByID(ctx context.Context, categoryID int64) (RecipeCategory, error)
	GetCategoryGroupByID(ctx context.Context, categoryGroupID int64) (RecipeCategoryGroup, error)
	GetRecipeByID(ctx context.Context, recipeID int64) (RecipeRecipe, error)
	// The household's delta for a recipe, or no row.
	GetRecipeDelta(ctx context.Context, arg GetRecipeDeltaParams) (RecipeRecipeDeltum, error)
	GetRecipeRating(ctx context.Context, arg GetRecipeRatingParams) (RecipeRecipeRating, error)
	GetRecipesByIDs(ctx context.Context, recipeIds []int64) ([]RecipeRecipe, error)
	ListCategoriesByGroup(ctx context.Context, categoryGroupID int64) ([]RecipeCategory, error)
	// Categories with their group's exclusivity/name, for assignment-time
	// validation (a recipe may hold at most one category per exclusive group).
	ListCategoriesByIDs(ctx context.Context, categoryIds []int64) ([]ListCategoriesByIDsRow, error)
	// Batch child preload: every category each recipe carries, with group
	// metadata so resolvers never query per-row.
	ListCategoriesForRecipes(ctx context.Context, recipeIds []int64) ([]ListCategoriesForRecipesRow, error)
	ListCategoryGroups(ctx context.Context) ([]RecipeCategoryGroup, error)
	ListDeltaItemsByDeltas(ctx context.Context, dollar_1 []int64) ([]RecipeRecipeDeltaItem, error)
	ListDeltaStepsByDeltas(ctx context.Context, dollar_1 []int64) ([]RecipeRecipeDeltaStep, error)
	// Active recipes whose embedding is missing or was built by another model —
	// the backfill sweep's work set.
	ListEmbeddingCandidates(ctx context.Context, arg ListEmbeddingCandidatesParams) ([]int64, error)
	// The household's deltas across a set of recipes — the batch load behind
	// loadRecipeChildren/planRecipes.
	ListRecipeDeltas(ctx context.Context, arg ListRecipeDeltasParams) ([]RecipeRecipeDeltum, error)
	ListRecipeItems(ctx context.Context, recipeID int64) ([]RecipeRecipeItem, error)
	ListRecipeItemsByRecipes(ctx context.Context, recipeIds []int64) ([]RecipeRecipeItem, error)
	ListRecipeRatingSummaries(ctx context.Context, recipeIds []int64) ([]ListRecipeRatingSummariesRow, error)
	ListRecipeRatings(ctx context.Context, arg ListRecipeRatingsParams) ([]RecipeRecipeRating, error)
	// One user's recipe ratings at or above a threshold. Recency scoring joins
	// this to mealplan data in the BFF; SQL never crosses schemas.
	ListRecipeRatingsAtLeast(ctx context.Context, arg ListRecipeRatingsAtLeastParams) ([]ListRecipeRatingsAtLeastRow, error)
	ListRecipeSteps(ctx context.Context, recipeID int64) ([]RecipeRecipeStep, error)
	ListRecipeStepsByRecipes(ctx context.Context, recipeIds []int64) ([]RecipeRecipeStep, error)
	ListRecipes(ctx context.Context, arg ListRecipesParams) ([]RecipeRecipe, error)
	RemoveRecipeItem(ctx context.Context, recipeItemID int64) error
	// Whole-delta replace: clears the delta's item rows before the caller
	// re-inserts the desired set in the same transaction.
	ReplaceDeltaItems(ctx context.Context, recipeDeltaID int64) error
	ReplaceDeltaSteps(ctx context.Context, recipeDeltaID int64) error
	// Filtered + engagement-ranked recipe listing. Ranking tiers come from
	// engagement ID arrays computed by the BFF (analytics/userprefs live in
	// other schemas — SQL never crosses schemas):
	//   0 favorite, 1 course-boost (meal-type match), 2 used (household
	//   menus), 3 viewed, 4 searched, 5 rest.
	// The used/viewed arrays arrive pre-sorted by signal strength so
	// array_position doubles as the in-tier tiebreaker.
	SearchRecipes(ctx context.Context, arg SearchRecipesParams) ([]RecipeRecipe, error)
	// Vector-similarity recipe listing. Only embedded rows participate (the
	// backfill sweep fills the rest). Ranking blends cosine distance with a
	// small additive engagement bump — favorites 1.0, household-used 0.6,
	// viewed 0.3, scaled by semanticEngagementBoost — so a mediocre-vector
	// favorite can't swamp a strong match. The same category/include/exclude
	// filters as SearchRecipes apply; there is no name-LIKE filter since the
	// query text becomes the vector.
	SearchRecipesSemantic(ctx context.Context, arg SearchRecipesSemanticParams) ([]SearchRecipesSemanticRow, error)
	// Stores an embedding for semantic search. The vector arrives as a text
	// literal and is cast server-side so generated code stays dependency-free.
	SetRecipeEmbedding(ctx context.Context, arg SetRecipeEmbeddingParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (RecipeCategory, error)
	UpdateCategoryGroup(ctx context.Context, arg UpdateCategoryGroupParams) (RecipeCategoryGroup, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (int64, error)
	// Timing columns are written only by the create/replace-children path
	// (AddRecipeStep); this partial update preserves them.
	UpdateRecipeStep(ctx context.Context, arg UpdateRecipeStepParams) (int64, error)
	// Creates the delta row on first change or touches updated_* on later
	// writes. base_updated_at snapshots the canonical recipe's current
	// updated_at (created_at when never edited) so stale detection compares
	// against a real version marker.
	UpsertRecipeDelta(ctx context.Context, arg UpsertRecipeDeltaParams) (RecipeRecipeDeltum, error)
	UpsertRecipeRating(ctx context.Context, arg UpsertRecipeRatingParams) (RecipeRecipeRating, error)
}

var _ Querier = (*Queries)(nil)
