// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRecipeCategories = `-- name: AddRecipeCategories :exec
INSERT INTO recipe.recipe_category (recipe_id, category_id, assigned_by)
SELECT $1, unnest($2::bigint[]), $3
ON CONFLICT DO NOTHING
`

type AddRecipeCategoriesParams struct {
	RecipeID   int64   `json:"recipe_id"`
	Column2    []int64 `json:"column_2"`
	AssignedBy string  `json:"assigned_by"`
}

func (q *Queries) AddRecipeCategories(ctx context.Context, arg AddRecipeCategoriesParams) error {
	_, err := q.db.Exec(ctx, addRecipeCategories, arg.RecipeID, arg.Column2, arg.AssignedBy)
	return err
}

const addRecipeItem = `-- name: AddRecipeItem :exec
INSERT INTO recipe.recipe_item (recipe_id, item_id, ingredient_id, quantity, unit_id, section_name, display_order, notes, is_optional)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type AddRecipeItemParams struct {
	RecipeID     int64          `json:"recipe_id"`
	ItemID       int64          `json:"item_id"`
	IngredientID pgtype.Int8    `json:"ingredient_id"`
	Quantity     pgtype.Numeric `json:"quantity"`
	UnitID       int64          `json:"unit_id"`
	SectionName  pgtype.Text    `json:"section_name"`
	DisplayOrder int32          `json:"display_order"`
	Notes        pgtype.Text    `json:"notes"`
	IsOptional   bool           `json:"is_optional"`
}

func (q *Queries) AddRecipeItem(ctx context.Context, arg AddRecipeItemParams) error {
	_, err := q.db.Exec(ctx, addRecipeItem,
		arg.RecipeID,
		arg.ItemID,
		arg.IngredientID,
		arg.Quantity,
		arg.UnitID,
		arg.SectionName,
		arg.DisplayOrder,
		arg.Notes,
		arg.IsOptional,
	)
	return err
}

const addRecipeStep = `-- name: AddRecipeStep :one
INSERT INTO recipe.recipe_step (recipe_id, step_number, instruction, duration_minutes, step_type, is_passive, depends_on_step_number, appliance, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING step_id, recipe_id, step_number, instruction, created_by, created_at, updated_by, updated_at, duration_minutes, step_type, is_passive, depends_on_step_number, appliance
`

type AddRecipeStepParams struct {
	RecipeID            int64       `json:"recipe_id"`
	StepNumber          int32       `json:"step_number"`
	Instruction         string      `json:"instruction"`
	DurationMinutes     pgtype.Int4 `json:"duration_minutes"`
	StepType            pgtype.Text `json:"step_type"`
	IsPassive           bool        `json:"is_passive"`
	DependsOnStepNumber pgtype.Int4 `json:"depends_on_step_number"`
	Appliance           pgtype.Text `json:"appliance"`
	CreatedBy           string      `json:"created_by"`
	UpdatedBy           pgtype.Text `json:"updated_by"`
}

func (q *Queries) AddRecipeStep(ctx context.Context, arg AddRecipeStepParams) (RecipeRecipeStep, error) {
	row := q.db.QueryRow(ctx, addRecipeStep,
		arg.RecipeID,
		arg.StepNumber,
		arg.Instruction,
		arg.DurationMinutes,
		arg.StepType,
		arg.IsPassive,
		arg.DependsOnStepNumber,
		arg.Appliance,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i RecipeRecipeStep
	err := row.Scan(
		&i.StepID,
		&i.RecipeID,
		&i.StepNumber,
		&i.Instruction,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DurationMinutes,
		&i.StepType,
		&i.IsPassive,
		&i.DependsOnStepNumber,
		&i.Appliance,
	)
	return i, err
}

const clearRecipeCategories = `-- name: ClearRecipeCategories :exec
DELETE FROM recipe.recipe_category
WHERE recipe_id = $1
`

func (q *Queries) ClearRecipeCategories(ctx context.Context, recipeID int64) error {
	_, err := q.db.Exec(ctx, clearRecipeCategories, recipeID)
	return err
}

const countCategoriesInGroup = `-- name: CountCategoriesInGroup :one
SELECT COUNT(*)
FROM recipe.category
WHERE category_group_id = $1
`

func (q *Queries) CountCategoriesInGroup(ctx context.Context, categoryGroupID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoriesInGroup, categoryGroupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecipes = `-- name: CountRecipes :one
SELECT COUNT(*)
FROM recipe.recipe
WHERE is_active = $1
`

func (q *Queries) CountRecipes(ctx context.Context, isActive bool) (int64, error) {
	row := q.db.QueryRow(ctx, countRecipes, isActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchRecipes = `-- name: CountSearchRecipes :one
SELECT COUNT(*)
FROM recipe.recipe r
WHERE r.is_active = $1
  AND ($2::text IS NULL OR lower(r.name) LIKE '%' || lower($2) || '%')
  AND (
    $3::bigint[] IS NULL
    OR (
      SELECT COUNT(DISTINCT c.category_group_id)
      FROM recipe.recipe_category rc
      JOIN recipe.category c ON c.category_id = rc.category_id
      WHERE rc.recipe_id = r.recipe_id AND c.category_id = ANY($3::bigint[])
    ) = (
      SELECT COUNT(DISTINCT category_group_id)
      FROM recipe.category
      WHERE category_id = ANY($3::bigint[])
    )
  )
  AND ($4::bigint[] IS NULL OR r.recipe_id = ANY($4::bigint[]))
  AND ($5::bigint[] IS NULL OR NOT (r.recipe_id = ANY($5::bigint[])))
`

type CountSearchRecipesParams struct {
	IsActive    bool    `json:"is_active"`
	Search      string  `json:"search"`
	CategoryIds []int64 `json:"category_ids"`
	IncludeIds  []int64 `json:"include_ids"`
	ExcludeIds  []int64 `json:"exclude_ids"`
}

func (q *Queries) CountSearchRecipes(ctx context.Context, arg CountSearchRecipesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchRecipes,
		arg.IsActive,
		arg.Search,
		arg.CategoryIds,
		arg.IncludeIds,
		arg.ExcludeIds,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO recipe.category (category_group_id, name, created_by, updated_by)
VALUES ($1, $2, $3, $4)
RETURNING category_id, category_group_id, name, created_by, created_at, updated_by, updated_at
`

type CreateCategoryParams struct {
	CategoryGroupID int64       `json:"category_group_id"`
	Name            string      `json:"name"`
	CreatedBy       string      `json:"created_by"`
	UpdatedBy       pgtype.Text `json:"updated_by"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (RecipeCategory, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.CategoryGroupID,
		arg.Name,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i RecipeCategory
	err := row.Scan(
		&i.CategoryID,
		&i.CategoryGroupID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createCategoryGroup = `-- name: CreateCategoryGroup :one

INSERT INTO recipe.category_group (name, exclusive, display_order, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING category_group_id, name, exclusive, display_order, created_by, created_at, updated_by, updated_at
`

type CreateCategoryGroupParams struct {
	Name         string      `json:"name"`
	Exclusive    bool        `json:"exclusive"`
	DisplayOrder int32       `json:"display_order"`
	CreatedBy    string      `json:"created_by"`
	UpdatedBy    pgtype.Text `json:"updated_by"`
}

// ---------- recipe categories (0035) ----------
func (q *Queries) CreateCategoryGroup(ctx context.Context, arg CreateCategoryGroupParams) (RecipeCategoryGroup, error) {
	row := q.db.QueryRow(ctx, createCategoryGroup,
		arg.Name,
		arg.Exclusive,
		arg.DisplayOrder,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i RecipeCategoryGroup
	err := row.Scan(
		&i.CategoryGroupID,
		&i.Name,
		&i.Exclusive,
		&i.DisplayOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipe.recipe (name, description, servings, prep_time_minutes, cook_time_minutes, is_active, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING recipe_id, name, description, servings, prep_time_minutes, cook_time_minutes, is_active, created_by, created_at, updated_by, updated_at
`

type CreateRecipeParams struct {
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	Servings        pgtype.Int4 `json:"servings"`
	PrepTimeMinutes pgtype.Int4 `json:"prep_time_minutes"`
	CookTimeMinutes pgtype.Int4 `json:"cook_time_minutes"`
	IsActive        bool        `json:"is_active"`
	CreatedBy       string      `json:"created_by"`
	UpdatedBy       pgtype.Text `json:"updated_by"`
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (RecipeRecipe, error) {
	row := q.db.QueryRow(ctx, createRecipe,
		arg.Name,
		arg.Description,
		arg.Servings,
		arg.PrepTimeMinutes,
		arg.CookTimeMinutes,
		arg.IsActive,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i RecipeRecipe
	err := row.Scan(
		&i.RecipeID,
		&i.Name,
		&i.Description,
		&i.Servings,
		&i.PrepTimeMinutes,
		&i.CookTimeMinutes,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM recipe.category
WHERE category_id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, categoryID int64) error {
	_, err := q.db.Exec(ctx, deleteCategory, categoryID)
	return err
}

const deleteCategoryGroup = `-- name: DeleteCategoryGroup :exec
DELETE FROM recipe.category_group
WHERE category_group_id = $1
`

func (q *Queries) DeleteCategoryGroup(ctx context.Context, categoryGroupID int64) error {
	_, err := q.db.Exec(ctx, deleteCategoryGroup, categoryGroupID)
	return err
}

const deleteRecipe = `-- name: DeleteRecipe :exec
DELETE FROM recipe.recipe
WHERE recipe_id = $1
`

func (q *Queries) DeleteRecipe(ctx context.Context, recipeID int64) error {
	_, err := q.db.Exec(ctx, deleteRecipe, recipeID)
	return err
}

const deleteRecipeItems = `-- name: DeleteRecipeItems :exec
DELETE FROM recipe.recipe_item
WHERE recipe_id = $1
`

func (q *Queries) DeleteRecipeItems(ctx context.Context, recipeID int64) error {
	_, err := q.db.Exec(ctx, deleteRecipeItems, recipeID)
	return err
}

const deleteRecipeStep = `-- name: DeleteRecipeStep :exec
DELETE FROM recipe.recipe_step
WHERE step_id = $1
`

func (q *Queries) DeleteRecipeStep(ctx context.Context, stepID int64) error {
	_, err := q.db.Exec(ctx, deleteRecipeStep, stepID)
	return err
}

const deleteRecipeSteps = `-- name: DeleteRecipeSteps :exec
DELETE FROM recipe.recipe_step
WHERE recipe_id = $1
`

func (q *Queries) DeleteRecipeSteps(ctx context.Context, recipeID int64) error {
	_, err := q.db.Exec(ctx, deleteRecipeSteps, recipeID)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT category_id, category_group_id, name, created_by, created_at, updated_by, updated_at
FROM recipe.category
WHERE category_id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, categoryID int64) (RecipeCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, categoryID)
	var i RecipeCategory
	err := row.Scan(
		&i.CategoryID,
		&i.CategoryGroupID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryGroupByID = `-- name: GetCategoryGroupByID :one
SELECT category_group_id, name, exclusive, display_order, created_by, created_at, updated_by, updated_at
FROM recipe.category_group
WHERE category_group_id = $1
`

func (q *Queries) GetCategoryGroupByID(ctx context.Context, categoryGroupID int64) (RecipeCategoryGroup, error) {
	row := q.db.QueryRow(ctx, getCategoryGroupByID, categoryGroupID)
	var i RecipeCategoryGroup
	err := row.Scan(
		&i.CategoryGroupID,
		&i.Name,
		&i.Exclusive,
		&i.DisplayOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeByID = `-- name: GetRecipeByID :one
SELECT recipe_id, name, description, servings, prep_time_minutes, cook_time_minutes, is_active, created_by, created_at, updated_by, updated_at
FROM recipe.recipe
WHERE recipe_id = $1
`

func (q *Queries) GetRecipeByID(ctx context.Context, recipeID int64) (RecipeRecipe, error) {
	row := q.db.QueryRow(ctx, getRecipeByID, recipeID)
	var i RecipeRecipe
	err := row.Scan(
		&i.RecipeID,
		&i.Name,
		&i.Description,
		&i.Servings,
		&i.PrepTimeMinutes,
		&i.CookTimeMinutes,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeRating = `-- name: GetRecipeRating :one
SELECT user_id, recipe_id, rating, created_by, created_at, updated_by, updated_at
FROM recipe.recipe_rating
WHERE user_id = $1 AND recipe_id = $2
`

type GetRecipeRatingParams struct {
	UserID   int64 `json:"user_id"`
	RecipeID int64 `json:"recipe_id"`
}

func (q *Queries) GetRecipeRating(ctx context.Context, arg GetRecipeRatingParams) (RecipeRecipeRating, error) {
	row := q.db.QueryRow(ctx, getRecipeRating, arg.UserID, arg.RecipeID)
	var i RecipeRecipeRating
	err := row.Scan(
		&i.UserID,
		&i.RecipeID,
		&i.Rating,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipesByIDs = `-- name: GetRecipesByIDs :many
SELECT recipe_id, name, description, servings, prep_time_minutes, cook_time_minutes, is_active, created_by, created_at, updated_by, updated_at
FROM recipe.recipe
WHERE recipe_id = ANY($1::bigint[])
`

func (q *Queries) GetRecipesByIDs(ctx context.Context, recipeIds []int64) ([]RecipeRecipe, error) {
	rows, err := q.db.Query(ctx, getRecipesByIDs, recipeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeRecipe{}
	for rows.Next() {
		var i RecipeRecipe
		if err := rows.Scan(
			&i.RecipeID,
			&i.Name,
			&i.Description,
			&i.Servings,
			&i.PrepTimeMinutes,
			&i.CookTimeMinutes,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByGroup = `-- name: ListCategoriesByGroup :many
SELECT category_id, category_group_id, name, created_by, created_at, updated_by, updated_at
FROM recipe.category
WHERE category_group_id = $1
ORDER BY name
`

func (q *Queries) ListCategoriesByGroup(ctx context.Context, categoryGroupID int64) ([]RecipeCategory, error) {
	rows, err := q.db.Query(ctx, listCategoriesByGroup, categoryGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeCategory{}
	for rows.Next() {
		var i RecipeCategory
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryGroupID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByIDs = `-- name: ListCategoriesByIDs :many
SELECT c.category_id, c.category_group_id, c.name, c.created_by, c.created_at, c.updated_by, c.updated_at, g.name AS group_name, g.exclusive AS group_exclusive, g.display_order AS group_display_order
FROM recipe.category c
JOIN recipe.category_group g ON g.category_group_id = c.category_group_id
WHERE c.category_id = ANY($1::bigint[])
`

type ListCategoriesByIDsRow struct {
	CategoryID        int64              `json:"category_id"`
	CategoryGroupID   int64              `json:"category_group_id"`
	Name              string             `json:"name"`
	CreatedBy         string             `json:"created_by"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedBy         pgtype.Text        `json:"updated_by"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	GroupName         string             `json:"group_name"`
	GroupExclusive    bool               `json:"group_exclusive"`
	GroupDisplayOrder int32              `json:"group_display_order"`
}

// Categories with their group's exclusivity/name, for assignment-time
// validation (a recipe may hold at most one category per exclusive group).
func (q *Queries) ListCategoriesByIDs(ctx context.Context, categoryIds []int64) ([]ListCategoriesByIDsRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesByIDs, categoryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesByIDsRow{}
	for rows.Next() {
		var i ListCategoriesByIDsRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryGroupID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.GroupName,
			&i.GroupExclusive,
			&i.GroupDisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesForRecipes = `-- name: ListCategoriesForRecipes :many
SELECT rc.recipe_id, c.category_id, c.name, c.category_group_id,
       g.name AS group_name, g.exclusive AS group_exclusive, g.display_order AS group_display_order
FROM recipe.recipe_category rc
JOIN recipe.category c ON c.category_id = rc.category_id
JOIN recipe.category_group g ON g.category_group_id = c.category_group_id
WHERE rc.recipe_id = ANY($1::bigint[])
ORDER BY g.display_order, c.name
`

type ListCategoriesForRecipesRow struct {
	RecipeID          int64  `json:"recipe_id"`
	CategoryID        int64  `json:"category_id"`
	Name              string `json:"name"`
	CategoryGroupID   int64  `json:"category_group_id"`
	GroupName         string `json:"group_name"`
	GroupExclusive    bool   `json:"group_exclusive"`
	GroupDisplayOrder int32  `json:"group_display_order"`
}

// Batch child preload: every category each recipe carries, with group
// metadata so resolvers never query per-row.
func (q *Queries) ListCategoriesForRecipes(ctx context.Context, recipeIds []int64) ([]ListCategoriesForRecipesRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesForRecipes, recipeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesForRecipesRow{}
	for rows.Next() {
		var i ListCategoriesForRecipesRow
		if err := rows.Scan(
			&i.RecipeID,
			&i.CategoryID,
			&i.Name,
			&i.CategoryGroupID,
			&i.GroupName,
			&i.GroupExclusive,
			&i.GroupDisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryGroups = `-- name: ListCategoryGroups :many
SELECT category_group_id, name, exclusive, display_order, created_by, created_at, updated_by, updated_at
FROM recipe.category_group
ORDER BY display_order, name
`

func (q *Queries) ListCategoryGroups(ctx context.Context) ([]RecipeCategoryGroup, error) {
	rows, err := q.db.Query(ctx, listCategoryGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeCategoryGroup{}
	for rows.Next() {
		var i RecipeCategoryGroup
		if err := rows.Scan(
			&i.CategoryGroupID,
			&i.Name,
			&i.Exclusive,
			&i.DisplayOrder,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeItems = `-- name: ListRecipeItems :many
SELECT recipe_id, item_id, quantity, notes, is_optional, ingredient_id, unit_id, recipe_item_id, section_name, display_order
FROM recipe.recipe_item
WHERE recipe_id = $1
ORDER BY display_order, recipe_item_id
`

func (q *Queries) ListRecipeItems(ctx context.Context, recipeID int64) ([]RecipeRecipeItem, error) {
	rows, err := q.db.Query(ctx, listRecipeItems, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeRecipeItem{}
	for rows.Next() {
		var i RecipeRecipeItem
		if err := rows.Scan(
			&i.RecipeID,
			&i.ItemID,
			&i.Quantity,
			&i.Notes,
			&i.IsOptional,
			&i.IngredientID,
			&i.UnitID,
			&i.RecipeItemID,
			&i.SectionName,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeItemsByRecipes = `-- name: ListRecipeItemsByRecipes :many
SELECT recipe_id, item_id, quantity, notes, is_optional, ingredient_id, unit_id, recipe_item_id, section_name, display_order
FROM recipe.recipe_item
WHERE recipe_id = ANY($1::bigint[])
ORDER BY recipe_id, display_order, recipe_item_id
`

func (q *Queries) ListRecipeItemsByRecipes(ctx context.Context, recipeIds []int64) ([]RecipeRecipeItem, error) {
	rows, err := q.db.Query(ctx, listRecipeItemsByRecipes, recipeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeRecipeItem{}
	for rows.Next() {
		var i RecipeRecipeItem
		if err := rows.Scan(
			&i.RecipeID,
			&i.ItemID,
			&i.Quantity,
			&i.Notes,
			&i.IsOptional,
			&i.IngredientID,
			&i.UnitID,
			&i.RecipeItemID,
			&i.SectionName,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeRatingSummaries = `-- name: ListRecipeRatingSummaries :many
SELECT recipe_id,
       AVG(rating)::float8 AS average_rating,
       COUNT(*)            AS rating_count
FROM recipe.recipe_rating
WHERE recipe_id = ANY($1::bigint[])
GROUP BY recipe_id
`

type ListRecipeRatingSummariesRow struct {
	RecipeID      int64   `json:"recipe_id"`
	AverageRating float64 `json:"average_rating"`
	RatingCount   int64   `json:"rating_count"`
}

func (q *Queries) ListRecipeRatingSummaries(ctx context.Context, recipeIds []int64) ([]ListRecipeRatingSummariesRow, error) {
	rows, err := q.db.Query(ctx, listRecipeRatingSummaries, recipeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecipeRatingSummariesRow{}
	for rows.Next() {
		var i ListRecipeRatingSummariesRow
		if err := rows.Scan(&i.RecipeID, &i.AverageRating, &i.RatingCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeRatings = `-- name: ListRecipeRatings :many
SELECT user_id, recipe_id, rating, created_by, created_at, updated_by, updated_at
FROM recipe.recipe_rating
WHERE user_id = $1 AND recipe_id = ANY($2::bigint[])
`

type ListRecipeRatingsParams struct {
	UserID    int64   `json:"user_id"`
	RecipeIds []int64 `json:"recipe_ids"`
}

func (q *Queries) ListRecipeRatings(ctx context.Context, arg ListRecipeRatingsParams) ([]RecipeRecipeRating, error) {
	rows, err := q.db.Query(ctx, listRecipeRatings, arg.UserID, arg.RecipeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeRecipeRating{}
	for rows.Next() {
		var i RecipeRecipeRating
		if err := rows.Scan(
			&i.UserID,
			&i.RecipeID,
			&i.Rating,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeRatingsAtLeast = `-- name: ListRecipeRatingsAtLeast :many
SELECT recipe_id, rating
FROM recipe.recipe_rating
WHERE user_id = $1 AND rating >= $2
`

type ListRecipeRatingsAtLeastParams struct {
	UserID int64 `json:"user_id"`
	Rating int16 `json:"rating"`
}

type ListRecipeRatingsAtLeastRow struct {
	RecipeID int64 `json:"recipe_id"`
	Rating   int16 `json:"rating"`
}

// One user's recipe ratings at or above a threshold. Recency scoring joins
// this to mealplan data in the BFF; SQL never crosses schemas.
func (q *Queries) ListRecipeRatingsAtLeast(ctx context.Context, arg ListRecipeRatingsAtLeastParams) ([]ListRecipeRatingsAtLeastRow, error) {
	rows, err := q.db.Query(ctx, listRecipeRatingsAtLeast, arg.UserID, arg.Rating)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecipeRatingsAtLeastRow{}
	for rows.Next() {
		var i ListRecipeRatingsAtLeastRow
		if err := rows.Scan(&i.RecipeID, &i.Rating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeSteps = `-- name: ListRecipeSteps :many
SELECT step_id, recipe_id, step_number, instruction, created_by, created_at, updated_by, updated_at, duration_minutes, step_type, is_passive, depends_on_step_number, appliance
FROM recipe.recipe_step
WHERE recipe_id = $1
ORDER BY step_number
`

func (q *Queries) ListRecipeSteps(ctx context.Context, recipeID int64) ([]RecipeRecipeStep, error) {
	rows, err := q.db.Query(ctx, listRecipeSteps, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeRecipeStep{}
	for rows.Next() {
		var i RecipeRecipeStep
		if err := rows.Scan(
			&i.StepID,
			&i.RecipeID,
			&i.StepNumber,
			&i.Instruction,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DurationMinutes,
			&i.StepType,
			&i.IsPassive,
			&i.DependsOnStepNumber,
			&i.Appliance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeStepsByRecipes = `-- name: ListRecipeStepsByRecipes :many
SELECT step_id, recipe_id, step_number, instruction, created_by, created_at, updated_by, updated_at, duration_minutes, step_type, is_passive, depends_on_step_number, appliance
FROM recipe.recipe_step
WHERE recipe_id = ANY($1::bigint[])
ORDER BY step_number
`

func (q *Queries) ListRecipeStepsByRecipes(ctx context.Context, recipeIds []int64) ([]RecipeRecipeStep, error) {
	rows, err := q.db.Query(ctx, listRecipeStepsByRecipes, recipeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeRecipeStep{}
	for rows.Next() {
		var i RecipeRecipeStep
		if err := rows.Scan(
			&i.StepID,
			&i.RecipeID,
			&i.StepNumber,
			&i.Instruction,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DurationMinutes,
			&i.StepType,
			&i.IsPassive,
			&i.DependsOnStepNumber,
			&i.Appliance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipes = `-- name: ListRecipes :many
SELECT recipe_id, name, description, servings, prep_time_minutes, cook_time_minutes, is_active, created_by, created_at, updated_by, updated_at
FROM recipe.recipe
WHERE is_active = $1
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListRecipesParams struct {
	IsActive bool  `json:"is_active"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListRecipes(ctx context.Context, arg ListRecipesParams) ([]RecipeRecipe, error) {
	rows, err := q.db.Query(ctx, listRecipes, arg.IsActive, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeRecipe{}
	for rows.Next() {
		var i RecipeRecipe
		if err := rows.Scan(
			&i.RecipeID,
			&i.Name,
			&i.Description,
			&i.Servings,
			&i.PrepTimeMinutes,
			&i.CookTimeMinutes,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRecipeItem = `-- name: RemoveRecipeItem :exec
DELETE FROM recipe.recipe_item
WHERE recipe_item_id = $1
`

func (q *Queries) RemoveRecipeItem(ctx context.Context, recipeItemID int64) error {
	_, err := q.db.Exec(ctx, removeRecipeItem, recipeItemID)
	return err
}

const searchRecipes = `-- name: SearchRecipes :many
SELECT r.recipe_id, r.name, r.description, r.servings, r.prep_time_minutes, r.cook_time_minutes, r.is_active, r.created_by, r.created_at, r.updated_by, r.updated_at
FROM recipe.recipe r
WHERE r.is_active = $1
  AND ($2::text IS NULL OR lower(r.name) LIKE '%' || lower($2) || '%')
  AND (
    $3::bigint[] IS NULL
    OR (
      SELECT COUNT(DISTINCT c.category_group_id)
      FROM recipe.recipe_category rc
      JOIN recipe.category c ON c.category_id = rc.category_id
      WHERE rc.recipe_id = r.recipe_id AND c.category_id = ANY($3::bigint[])
    ) = (
      SELECT COUNT(DISTINCT category_group_id)
      FROM recipe.category
      WHERE category_id = ANY($3::bigint[])
    )
  )
  AND ($4::bigint[] IS NULL OR r.recipe_id = ANY($4::bigint[]))
  AND ($5::bigint[] IS NULL OR NOT (r.recipe_id = ANY($5::bigint[])))
ORDER BY
  CASE
    WHEN $6::bigint[] IS NOT NULL AND r.recipe_id = ANY($6::bigint[]) THEN 0
    WHEN $7::bigint IS NOT NULL AND EXISTS (
      SELECT 1 FROM recipe.recipe_category rc
      WHERE rc.recipe_id = r.recipe_id
        AND rc.category_id = $7::bigint
    ) THEN 1
    WHEN r.recipe_id = ANY($8::bigint[]) THEN 2
    WHEN r.recipe_id = ANY($9::bigint[]) THEN 3
    WHEN EXISTS (
      SELECT 1 FROM unnest($10::text[]) t
      WHERE position(lower(t) in lower(r.name)) > 0
    ) THEN 4
    ELSE 5
  END,
  array_position($8::bigint[], r.recipe_id),
  array_position($9::bigint[], r.recipe_id),
  r.name
LIMIT $12::int OFFSET $11::int
`

type SearchRecipesParams struct {
	IsActive        bool        `json:"is_active"`
	Search          string      `json:"search"`
	CategoryIds     []int64     `json:"category_ids"`
	IncludeIds      []int64     `json:"include_ids"`
	ExcludeIds      []int64     `json:"exclude_ids"`
	FavoriteIds     []int64     `json:"favorite_ids"`
	BoostCategoryID pgtype.Int8 `json:"boost_category_id"`
	UsedIds         []int64     `json:"used_ids"`
	ViewedIds       []int64     `json:"viewed_ids"`
	SearchTerms     []string    `json:"search_terms"`
	Offset          int32       `json:"offset"`
	Limit           int32       `json:"limit"`
}

// Filtered + engagement-ranked recipe listing. Ranking tiers come from
// engagement ID arrays computed by the BFF (analytics/userprefs live in
// other schemas — SQL never crosses schemas):
//
//	0 favorite, 1 course-boost (meal-type match), 2 used (household
//	menus), 3 viewed, 4 searched, 5 rest.
//
// The used/viewed arrays arrive pre-sorted by signal strength so
// array_position doubles as the in-tier tiebreaker.
func (q *Queries) SearchRecipes(ctx context.Context, arg SearchRecipesParams) ([]RecipeRecipe, error) {
	rows, err := q.db.Query(ctx, searchRecipes,
		arg.IsActive,
		arg.Search,
		arg.CategoryIds,
		arg.IncludeIds,
		arg.ExcludeIds,
		arg.FavoriteIds,
		arg.BoostCategoryID,
		arg.UsedIds,
		arg.ViewedIds,
		arg.SearchTerms,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeRecipe{}
	for rows.Next() {
		var i RecipeRecipe
		if err := rows.Scan(
			&i.RecipeID,
			&i.Name,
			&i.Description,
			&i.Servings,
			&i.PrepTimeMinutes,
			&i.CookTimeMinutes,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE recipe.category
SET name       = $2,
    updated_by = $3,
    updated_at = now()
WHERE category_id = $1
RETURNING category_id, category_group_id, name, created_by, created_at, updated_by, updated_at
`

type UpdateCategoryParams struct {
	CategoryID int64       `json:"category_id"`
	Name       string      `json:"name"`
	UpdatedBy  pgtype.Text `json:"updated_by"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (RecipeCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.CategoryID, arg.Name, arg.UpdatedBy)
	var i RecipeCategory
	err := row.Scan(
		&i.CategoryID,
		&i.CategoryGroupID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategoryGroup = `-- name: UpdateCategoryGroup :one
UPDATE recipe.category_group
SET name          = $2,
    exclusive     = $3,
    display_order = $4,
    updated_by    = $5,
    updated_at    = now()
WHERE category_group_id = $1
RETURNING category_group_id, name, exclusive, display_order, created_by, created_at, updated_by, updated_at
`

type UpdateCategoryGroupParams struct {
	CategoryGroupID int64       `json:"category_group_id"`
	Name            string      `json:"name"`
	Exclusive       bool        `json:"exclusive"`
	DisplayOrder    int32       `json:"display_order"`
	UpdatedBy       pgtype.Text `json:"updated_by"`
}

func (q *Queries) UpdateCategoryGroup(ctx context.Context, arg UpdateCategoryGroupParams) (RecipeCategoryGroup, error) {
	row := q.db.QueryRow(ctx, updateCategoryGroup,
		arg.CategoryGroupID,
		arg.Name,
		arg.Exclusive,
		arg.DisplayOrder,
		arg.UpdatedBy,
	)
	var i RecipeCategoryGroup
	err := row.Scan(
		&i.CategoryGroupID,
		&i.Name,
		&i.Exclusive,
		&i.DisplayOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRecipe = `-- name: UpdateRecipe :execrows
UPDATE recipe.recipe
SET name              = $2,
    description       = $3,
    servings          = $4,
    prep_time_minutes = $5,
    cook_time_minutes = $6,
    is_active         = $7,
    updated_by        = $8,
    updated_at        = now()
WHERE recipe_id = $1
`

type UpdateRecipeParams struct {
	RecipeID        int64       `json:"recipe_id"`
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	Servings        pgtype.Int4 `json:"servings"`
	PrepTimeMinutes pgtype.Int4 `json:"prep_time_minutes"`
	CookTimeMinutes pgtype.Int4 `json:"cook_time_minutes"`
	IsActive        bool        `json:"is_active"`
	UpdatedBy       pgtype.Text `json:"updated_by"`
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRecipe,
		arg.RecipeID,
		arg.Name,
		arg.Description,
		arg.Servings,
		arg.PrepTimeMinutes,
		arg.CookTimeMinutes,
		arg.IsActive,
		arg.UpdatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRecipeStep = `-- name: UpdateRecipeStep :execrows
UPDATE recipe.recipe_step
SET step_number = $2,
    instruction = $3,
    updated_by  = $4,
    updated_at  = now()
WHERE step_id = $1
`

type UpdateRecipeStepParams struct {
	StepID      int64       `json:"step_id"`
	StepNumber  int32       `json:"step_number"`
	Instruction string      `json:"instruction"`
	UpdatedBy   pgtype.Text `json:"updated_by"`
}

// Timing columns are written only by the create/replace-children path
// (AddRecipeStep); this partial update preserves them.
func (q *Queries) UpdateRecipeStep(ctx context.Context, arg UpdateRecipeStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRecipeStep,
		arg.StepID,
		arg.StepNumber,
		arg.Instruction,
		arg.UpdatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertRecipeRating = `-- name: UpsertRecipeRating :one
INSERT INTO recipe.recipe_rating (user_id, recipe_id, rating, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, recipe_id)
    DO UPDATE SET
        rating     = EXCLUDED.rating,
        updated_by = EXCLUDED.updated_by,
        updated_at = now()
RETURNING user_id, recipe_id, rating, created_by, created_at, updated_by, updated_at
`

type UpsertRecipeRatingParams struct {
	UserID    int64       `json:"user_id"`
	RecipeID  int64       `json:"recipe_id"`
	Rating    int16       `json:"rating"`
	CreatedBy string      `json:"created_by"`
	UpdatedBy pgtype.Text `json:"updated_by"`
}

func (q *Queries) UpsertRecipeRating(ctx context.Context, arg UpsertRecipeRatingParams) (RecipeRecipeRating, error) {
	row := q.db.QueryRow(ctx, upsertRecipeRating,
		arg.UserID,
		arg.RecipeID,
		arg.Rating,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i RecipeRecipeRating
	err := row.Scan(
		&i.UserID,
		&i.RecipeID,
		&i.Rating,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
