// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AddRecipeItem(ctx context.Context, arg AddRecipeItemParams) error
	AddRecipeStep(ctx context.Context, arg AddRecipeStepParams) (RecipeRecipeStep, error)
	CountRecipes(ctx context.Context, isActive bool) (int64, error)
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (RecipeRecipe, error)
	DeleteRecipe(ctx context.Context, recipeID int64) error
	DeleteRecipeItems(ctx context.Context, recipeID int64) error
	DeleteRecipeStep(ctx context.Context, stepID int64) error
	DeleteRecipeSteps(ctx context.Context, recipeID int64) error
	GetRecipeByID(ctx context.Context, recipeID int64) (RecipeRecipe, error)
	GetRecipeRating(ctx context.Context, arg GetRecipeRatingParams) (RecipeRecipeRating, error)
	GetRecipesByIDs(ctx context.Context, recipeIds []int64) ([]RecipeRecipe, error)
	// For one user: every (rated recipe, meal-plan week it appeared) pair for
	// recipes rated at or above a threshold. last_used is NULL for ratings
	// with no matching slot; callers aggregate to the most recent week.
	ListRatingRecencyRows(ctx context.Context, arg ListRatingRecencyRowsParams) ([]ListRatingRecencyRowsRow, error)
	ListRecipeItems(ctx context.Context, recipeID int64) ([]RecipeRecipeItem, error)
	ListRecipeItemsByRecipes(ctx context.Context, recipeIds []int64) ([]RecipeRecipeItem, error)
	ListRecipeRatingSummaries(ctx context.Context, recipeIds []int64) ([]ListRecipeRatingSummariesRow, error)
	ListRecipeRatings(ctx context.Context, arg ListRecipeRatingsParams) ([]RecipeRecipeRating, error)
	ListRecipeSteps(ctx context.Context, recipeID int64) ([]RecipeRecipeStep, error)
	ListRecipeStepsByRecipes(ctx context.Context, recipeIds []int64) ([]RecipeRecipeStep, error)
	ListRecipes(ctx context.Context, arg ListRecipesParams) ([]RecipeRecipe, error)
	RemoveRecipeItem(ctx context.Context, recipeItemID int64) error
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) error
	UpdateRecipeStep(ctx context.Context, arg UpdateRecipeStepParams) error
	UpsertRecipeRating(ctx context.Context, arg UpsertRecipeRatingParams) (RecipeRecipeRating, error)
}

var _ Querier = (*Queries)(nil)
