// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateBottle(ctx context.Context, arg CreateBottleParams) (WineBottle, error)
	CreateBottleFlavorProfile(ctx context.Context, arg CreateBottleFlavorProfileParams) (WineBottleFlavorProfile, error)
	CreateBottleGrapeVariety(ctx context.Context, arg CreateBottleGrapeVarietyParams) (WineBottleGrapeVariety, error)
	CreateCountry(ctx context.Context, arg CreateCountryParams) (WineCountry, error)
	CreateGrapeVariety(ctx context.Context, arg CreateGrapeVarietyParams) (WineGrapeVariety, error)
	CreateRegion(ctx context.Context, arg CreateRegionParams) (WineRegion, error)
	CreateType(ctx context.Context, arg CreateTypeParams) (WineType, error)
	CreateVintage(ctx context.Context, arg CreateVintageParams) (WineVintage, error)
	DeleteBottle(ctx context.Context, bottleID int64) error
	DeleteBottleFlavorProfile(ctx context.Context, arg DeleteBottleFlavorProfileParams) error
	DeleteBottleGrapeVariety(ctx context.Context, arg DeleteBottleGrapeVarietyParams) error
	GetBottleByID(ctx context.Context, bottleID int64) (WineBottle, error)
	GetCountryByID(ctx context.Context, countryID int64) (WineCountry, error)
	GetRegionByID(ctx context.Context, regionID int64) (WineRegion, error)
	GetTypeByID(ctx context.Context, typeID int64) (WineType, error)
	ListBottleFlavorProfiles(ctx context.Context, bottleID int64) ([]ListBottleFlavorProfilesRow, error)
	ListBottleGrapeVarieties(ctx context.Context, bottleID int64) ([]ListBottleGrapeVarietiesRow, error)
	ListBottles(ctx context.Context, arg ListBottlesParams) ([]WineBottle, error)
	ListCountries(ctx context.Context) ([]WineCountry, error)
	ListGrapeVarieties(ctx context.Context) ([]WineGrapeVariety, error)
	ListRegions(ctx context.Context, countryID int64) ([]WineRegion, error)
	ListTypes(ctx context.Context) ([]WineType, error)
	ListVintages(ctx context.Context) ([]WineVintage, error)
	ListWineFlavorProfiles(ctx context.Context) ([]WineFlavorProfile, error)
	UpdateBottle(ctx context.Context, arg UpdateBottleParams) error
}

var _ Querier = (*Queries)(nil)
