// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBottle = `-- name: CreateBottle :one
INSERT INTO wine.bottle (
    type_id, country_id, region_id, vintage_year, vineyard, abv,
    acidity, tannin_level, body, sweetness, oak_integration, bottle_size,
    created_by, updated_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING bottle_id, type_id, country_id, region_id, vintage_year, vineyard, abv, acidity, tannin_level, body, sweetness, oak_integration, bottle_size, created_by, created_at, updated_by, updated_at
`

type CreateBottleParams struct {
	TypeID         int64          `json:"type_id"`
	CountryID      int64          `json:"country_id"`
	RegionID       int64          `json:"region_id"`
	VintageYear    int32          `json:"vintage_year"`
	Vineyard       pgtype.Text    `json:"vineyard"`
	Abv            pgtype.Numeric `json:"abv"`
	Acidity        pgtype.Int2    `json:"acidity"`
	TanninLevel    pgtype.Int2    `json:"tannin_level"`
	Body           pgtype.Int2    `json:"body"`
	Sweetness      pgtype.Int2    `json:"sweetness"`
	OakIntegration pgtype.Bool    `json:"oak_integration"`
	BottleSize     string         `json:"bottle_size"`
	CreatedBy      string         `json:"created_by"`
	UpdatedBy      pgtype.Text    `json:"updated_by"`
}

func (q *Queries) CreateBottle(ctx context.Context, arg CreateBottleParams) (WineBottle, error) {
	row := q.db.QueryRow(ctx, createBottle,
		arg.TypeID,
		arg.CountryID,
		arg.RegionID,
		arg.VintageYear,
		arg.Vineyard,
		arg.Abv,
		arg.Acidity,
		arg.TanninLevel,
		arg.Body,
		arg.Sweetness,
		arg.OakIntegration,
		arg.BottleSize,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i WineBottle
	err := row.Scan(
		&i.BottleID,
		&i.TypeID,
		&i.CountryID,
		&i.RegionID,
		&i.VintageYear,
		&i.Vineyard,
		&i.Abv,
		&i.Acidity,
		&i.TanninLevel,
		&i.Body,
		&i.Sweetness,
		&i.OakIntegration,
		&i.BottleSize,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createCountry = `-- name: CreateCountry :one
INSERT INTO wine.country (name, iso_code, description, is_active, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING country_id, name, iso_code, description, is_active, created_by, created_at, updated_by, updated_at
`

type CreateCountryParams struct {
	Name        string      `json:"name"`
	IsoCode     string      `json:"iso_code"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	CreatedBy   string      `json:"created_by"`
	UpdatedBy   pgtype.Text `json:"updated_by"`
}

func (q *Queries) CreateCountry(ctx context.Context, arg CreateCountryParams) (WineCountry, error) {
	row := q.db.QueryRow(ctx, createCountry,
		arg.Name,
		arg.IsoCode,
		arg.Description,
		arg.IsActive,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i WineCountry
	err := row.Scan(
		&i.CountryID,
		&i.Name,
		&i.IsoCode,
		&i.Description,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createGrapeVariety = `-- name: CreateGrapeVariety :one
INSERT INTO wine.grape_variety (name, description, is_active, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING grape_variety_id, name, description, is_active, created_by, created_at, updated_by, updated_at
`

type CreateGrapeVarietyParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	CreatedBy   string      `json:"created_by"`
	UpdatedBy   pgtype.Text `json:"updated_by"`
}

func (q *Queries) CreateGrapeVariety(ctx context.Context, arg CreateGrapeVarietyParams) (WineGrapeVariety, error) {
	row := q.db.QueryRow(ctx, createGrapeVariety,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i WineGrapeVariety
	err := row.Scan(
		&i.GrapeVarietyID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createRegion = `-- name: CreateRegion :one
INSERT INTO wine.region (country_id, name, description, is_active, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING region_id, country_id, name, description, is_active, created_by, created_at, updated_by, updated_at
`

type CreateRegionParams struct {
	CountryID   int64       `json:"country_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	CreatedBy   string      `json:"created_by"`
	UpdatedBy   pgtype.Text `json:"updated_by"`
}

func (q *Queries) CreateRegion(ctx context.Context, arg CreateRegionParams) (WineRegion, error) {
	row := q.db.QueryRow(ctx, createRegion,
		arg.CountryID,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i WineRegion
	err := row.Scan(
		&i.RegionID,
		&i.CountryID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createType = `-- name: CreateType :one
INSERT INTO wine.type (name, description, is_active, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING type_id, name, description, is_active, created_by, created_at, updated_by, updated_at
`

type CreateTypeParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	CreatedBy   string      `json:"created_by"`
	UpdatedBy   pgtype.Text `json:"updated_by"`
}

func (q *Queries) CreateType(ctx context.Context, arg CreateTypeParams) (WineType, error) {
	row := q.db.QueryRow(ctx, createType,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i WineType
	err := row.Scan(
		&i.TypeID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createVintage = `-- name: CreateVintage :one
INSERT INTO wine.vintage (year, description, is_active, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING vintage_id, year, description, is_active, created_by, created_at, updated_by, updated_at
`

type CreateVintageParams struct {
	Year        int32       `json:"year"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	CreatedBy   string      `json:"created_by"`
	UpdatedBy   pgtype.Text `json:"updated_by"`
}

func (q *Queries) CreateVintage(ctx context.Context, arg CreateVintageParams) (WineVintage, error) {
	row := q.db.QueryRow(ctx, createVintage,
		arg.Year,
		arg.Description,
		arg.IsActive,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i WineVintage
	err := row.Scan(
		&i.VintageID,
		&i.Year,
		&i.Description,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBottle = `-- name: DeleteBottle :exec
DELETE FROM wine.bottle
WHERE bottle_id = $1
`

func (q *Queries) DeleteBottle(ctx context.Context, bottleID int64) error {
	_, err := q.db.Exec(ctx, deleteBottle, bottleID)
	return err
}

const getBottleByID = `-- name: GetBottleByID :one
SELECT bottle_id, type_id, country_id, region_id, vintage_year, vineyard, abv, acidity, tannin_level, body, sweetness, oak_integration, bottle_size, created_by, created_at, updated_by, updated_at
FROM wine.bottle
WHERE bottle_id = $1
`

func (q *Queries) GetBottleByID(ctx context.Context, bottleID int64) (WineBottle, error) {
	row := q.db.QueryRow(ctx, getBottleByID, bottleID)
	var i WineBottle
	err := row.Scan(
		&i.BottleID,
		&i.TypeID,
		&i.CountryID,
		&i.RegionID,
		&i.VintageYear,
		&i.Vineyard,
		&i.Abv,
		&i.Acidity,
		&i.TanninLevel,
		&i.Body,
		&i.Sweetness,
		&i.OakIntegration,
		&i.BottleSize,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getCountryByID = `-- name: GetCountryByID :one
SELECT country_id, name, iso_code, description, is_active, created_by, created_at, updated_by, updated_at
FROM wine.country
WHERE country_id = $1
`

func (q *Queries) GetCountryByID(ctx context.Context, countryID int64) (WineCountry, error) {
	row := q.db.QueryRow(ctx, getCountryByID, countryID)
	var i WineCountry
	err := row.Scan(
		&i.CountryID,
		&i.Name,
		&i.IsoCode,
		&i.Description,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegionByID = `-- name: GetRegionByID :one
SELECT region_id, country_id, name, description, is_active, created_by, created_at, updated_by, updated_at
FROM wine.region
WHERE region_id = $1
`

func (q *Queries) GetRegionByID(ctx context.Context, regionID int64) (WineRegion, error) {
	row := q.db.QueryRow(ctx, getRegionByID, regionID)
	var i WineRegion
	err := row.Scan(
		&i.RegionID,
		&i.CountryID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getTypeByID = `-- name: GetTypeByID :one
SELECT type_id, name, description, is_active, created_by, created_at, updated_by, updated_at
FROM wine.type
WHERE type_id = $1
`

func (q *Queries) GetTypeByID(ctx context.Context, typeID int64) (WineType, error) {
	row := q.db.QueryRow(ctx, getTypeByID, typeID)
	var i WineType
	err := row.Scan(
		&i.TypeID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listBottles = `-- name: ListBottles :many
SELECT bottle_id, type_id, country_id, region_id, vintage_year, vineyard, abv, acidity, tannin_level, body, sweetness, oak_integration, bottle_size, created_by, created_at, updated_by, updated_at
FROM wine.bottle
ORDER BY bottle_id DESC
LIMIT $1 OFFSET $2
`

type ListBottlesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBottles(ctx context.Context, arg ListBottlesParams) ([]WineBottle, error) {
	rows, err := q.db.Query(ctx, listBottles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WineBottle{}
	for rows.Next() {
		var i WineBottle
		if err := rows.Scan(
			&i.BottleID,
			&i.TypeID,
			&i.CountryID,
			&i.RegionID,
			&i.VintageYear,
			&i.Vineyard,
			&i.Abv,
			&i.Acidity,
			&i.TanninLevel,
			&i.Body,
			&i.Sweetness,
			&i.OakIntegration,
			&i.BottleSize,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountries = `-- name: ListCountries :many
SELECT country_id, name, iso_code, description, is_active, created_by, created_at, updated_by, updated_at
FROM wine.country
ORDER BY name
`

func (q *Queries) ListCountries(ctx context.Context) ([]WineCountry, error) {
	rows, err := q.db.Query(ctx, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WineCountry{}
	for rows.Next() {
		var i WineCountry
		if err := rows.Scan(
			&i.CountryID,
			&i.Name,
			&i.IsoCode,
			&i.Description,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrapeVarieties = `-- name: ListGrapeVarieties :many
SELECT grape_variety_id, name, description, is_active, created_by, created_at, updated_by, updated_at
FROM wine.grape_variety
ORDER BY name
`

func (q *Queries) ListGrapeVarieties(ctx context.Context) ([]WineGrapeVariety, error) {
	rows, err := q.db.Query(ctx, listGrapeVarieties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WineGrapeVariety{}
	for rows.Next() {
		var i WineGrapeVariety
		if err := rows.Scan(
			&i.GrapeVarietyID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegions = `-- name: ListRegions :many
SELECT region_id, country_id, name, description, is_active, created_by, created_at, updated_by, updated_at
FROM wine.region
WHERE country_id = $1
ORDER BY name
`

func (q *Queries) ListRegions(ctx context.Context, countryID int64) ([]WineRegion, error) {
	rows, err := q.db.Query(ctx, listRegions, countryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WineRegion{}
	for rows.Next() {
		var i WineRegion
		if err := rows.Scan(
			&i.RegionID,
			&i.CountryID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTypes = `-- name: ListTypes :many
SELECT type_id, name, description, is_active, created_by, created_at, updated_by, updated_at
FROM wine.type
ORDER BY name
`

func (q *Queries) ListTypes(ctx context.Context) ([]WineType, error) {
	rows, err := q.db.Query(ctx, listTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WineType{}
	for rows.Next() {
		var i WineType
		if err := rows.Scan(
			&i.TypeID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVintages = `-- name: ListVintages :many
SELECT vintage_id, year, description, is_active, created_by, created_at, updated_by, updated_at
FROM wine.vintage
ORDER BY year DESC
`

func (q *Queries) ListVintages(ctx context.Context) ([]WineVintage, error) {
	rows, err := q.db.Query(ctx, listVintages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WineVintage{}
	for rows.Next() {
		var i WineVintage
		if err := rows.Scan(
			&i.VintageID,
			&i.Year,
			&i.Description,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBottle = `-- name: UpdateBottle :exec
UPDATE wine.bottle
SET type_id         = $2,
    country_id      = $3,
    region_id       = $4,
    vintage_year    = $5,
    vineyard        = $6,
    abv             = $7,
    acidity         = $8,
    tannin_level    = $9,
    body            = $10,
    sweetness       = $11,
    oak_integration = $12,
    bottle_size     = $13,
    updated_by      = $14,
    updated_at      = now()
WHERE bottle_id = $1
`

type UpdateBottleParams struct {
	BottleID       int64          `json:"bottle_id"`
	TypeID         int64          `json:"type_id"`
	CountryID      int64          `json:"country_id"`
	RegionID       int64          `json:"region_id"`
	VintageYear    int32          `json:"vintage_year"`
	Vineyard       pgtype.Text    `json:"vineyard"`
	Abv            pgtype.Numeric `json:"abv"`
	Acidity        pgtype.Int2    `json:"acidity"`
	TanninLevel    pgtype.Int2    `json:"tannin_level"`
	Body           pgtype.Int2    `json:"body"`
	Sweetness      pgtype.Int2    `json:"sweetness"`
	OakIntegration pgtype.Bool    `json:"oak_integration"`
	BottleSize     string         `json:"bottle_size"`
	UpdatedBy      pgtype.Text    `json:"updated_by"`
}

func (q *Queries) UpdateBottle(ctx context.Context, arg UpdateBottleParams) error {
	_, err := q.db.Exec(ctx, updateBottle,
		arg.BottleID,
		arg.TypeID,
		arg.CountryID,
		arg.RegionID,
		arg.VintageYear,
		arg.Vineyard,
		arg.Abv,
		arg.Acidity,
		arg.TanninLevel,
		arg.Body,
		arg.Sweetness,
		arg.OakIntegration,
		arg.BottleSize,
		arg.UpdatedBy,
	)
	return err
}
