// Code generated by MockGen. DO NOT EDIT.
// Source: querier.go
//
// Generated by this command:
//
//	mockgen -source=querier.go -package=mock -destination=mock/querier.go Querier
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/JRAdams472/LENA2/internal/userprefs/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CountUserBottles mocks base method.
func (m *MockQuerier) CountUserBottles(ctx context.Context, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUserBottles", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUserBottles indicates an expected call of CountUserBottles.
func (mr *MockQuerierMockRecorder) CountUserBottles(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUserBottles", reflect.TypeOf((*MockQuerier)(nil).CountUserBottles), ctx, userID)
}

// CountUserItems mocks base method.
func (m *MockQuerier) CountUserItems(ctx context.Context, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUserItems", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUserItems indicates an expected call of CountUserItems.
func (mr *MockQuerierMockRecorder) CountUserItems(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUserItems", reflect.TypeOf((*MockQuerier)(nil).CountUserItems), ctx, userID)
}

// DeleteRecipeFavorite mocks base method.
func (m *MockQuerier) DeleteRecipeFavorite(ctx context.Context, arg sqlc.DeleteRecipeFavoriteParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecipeFavorite", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecipeFavorite indicates an expected call of DeleteRecipeFavorite.
func (mr *MockQuerierMockRecorder) DeleteRecipeFavorite(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecipeFavorite", reflect.TypeOf((*MockQuerier)(nil).DeleteRecipeFavorite), ctx, arg)
}

// DeleteUserBottle mocks base method.
func (m *MockQuerier) DeleteUserBottle(ctx context.Context, arg sqlc.DeleteUserBottleParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserBottle", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserBottle indicates an expected call of DeleteUserBottle.
func (mr *MockQuerierMockRecorder) DeleteUserBottle(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserBottle", reflect.TypeOf((*MockQuerier)(nil).DeleteUserBottle), ctx, arg)
}

// DeleteUserItem mocks base method.
func (m *MockQuerier) DeleteUserItem(ctx context.Context, arg sqlc.DeleteUserItemParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserItem", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserItem indicates an expected call of DeleteUserItem.
func (mr *MockQuerierMockRecorder) DeleteUserItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserItem", reflect.TypeOf((*MockQuerier)(nil).DeleteUserItem), ctx, arg)
}

// GetRecipeFavorite mocks base method.
func (m *MockQuerier) GetRecipeFavorite(ctx context.Context, arg sqlc.GetRecipeFavoriteParams) (sqlc.RecipeUserRecipePreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipeFavorite", ctx, arg)
	ret0, _ := ret[0].(sqlc.RecipeUserRecipePreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecipeFavorite indicates an expected call of GetRecipeFavorite.
func (mr *MockQuerierMockRecorder) GetRecipeFavorite(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipeFavorite", reflect.TypeOf((*MockQuerier)(nil).GetRecipeFavorite), ctx, arg)
}

// GetUserBottleByID mocks base method.
func (m *MockQuerier) GetUserBottleByID(ctx context.Context, arg sqlc.GetUserBottleByIDParams) (sqlc.WineUserBottle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBottleByID", ctx, arg)
	ret0, _ := ret[0].(sqlc.WineUserBottle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBottleByID indicates an expected call of GetUserBottleByID.
func (mr *MockQuerierMockRecorder) GetUserBottleByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBottleByID", reflect.TypeOf((*MockQuerier)(nil).GetUserBottleByID), ctx, arg)
}

// GetUserItemByID mocks base method.
func (m *MockQuerier) GetUserItemByID(ctx context.Context, arg sqlc.GetUserItemByIDParams) (sqlc.InventoryUserItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserItemByID", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryUserItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserItemByID indicates an expected call of GetUserItemByID.
func (mr *MockQuerierMockRecorder) GetUserItemByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserItemByID", reflect.TypeOf((*MockQuerier)(nil).GetUserItemByID), ctx, arg)
}

// ListRecipeFavorites mocks base method.
func (m *MockQuerier) ListRecipeFavorites(ctx context.Context, arg sqlc.ListRecipeFavoritesParams) ([]sqlc.RecipeUserRecipePreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecipeFavorites", ctx, arg)
	ret0, _ := ret[0].([]sqlc.RecipeUserRecipePreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecipeFavorites indicates an expected call of ListRecipeFavorites.
func (mr *MockQuerierMockRecorder) ListRecipeFavorites(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecipeFavorites", reflect.TypeOf((*MockQuerier)(nil).ListRecipeFavorites), ctx, arg)
}

// ListUserBottles mocks base method.
func (m *MockQuerier) ListUserBottles(ctx context.Context, arg sqlc.ListUserBottlesParams) ([]sqlc.WineUserBottle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserBottles", ctx, arg)
	ret0, _ := ret[0].([]sqlc.WineUserBottle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserBottles indicates an expected call of ListUserBottles.
func (mr *MockQuerierMockRecorder) ListUserBottles(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserBottles", reflect.TypeOf((*MockQuerier)(nil).ListUserBottles), ctx, arg)
}

// ListUserItems mocks base method.
func (m *MockQuerier) ListUserItems(ctx context.Context, arg sqlc.ListUserItemsParams) ([]sqlc.InventoryUserItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserItems", ctx, arg)
	ret0, _ := ret[0].([]sqlc.InventoryUserItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserItems indicates an expected call of ListUserItems.
func (mr *MockQuerierMockRecorder) ListUserItems(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserItems", reflect.TypeOf((*MockQuerier)(nil).ListUserItems), ctx, arg)
}

// UpsertRecipeFavorite mocks base method.
func (m *MockQuerier) UpsertRecipeFavorite(ctx context.Context, arg sqlc.UpsertRecipeFavoriteParams) (sqlc.RecipeUserRecipePreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRecipeFavorite", ctx, arg)
	ret0, _ := ret[0].(sqlc.RecipeUserRecipePreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertRecipeFavorite indicates an expected call of UpsertRecipeFavorite.
func (mr *MockQuerierMockRecorder) UpsertRecipeFavorite(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRecipeFavorite", reflect.TypeOf((*MockQuerier)(nil).UpsertRecipeFavorite), ctx, arg)
}

// UpsertUserBottle mocks base method.
func (m *MockQuerier) UpsertUserBottle(ctx context.Context, arg sqlc.UpsertUserBottleParams) (sqlc.WineUserBottle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserBottle", ctx, arg)
	ret0, _ := ret[0].(sqlc.WineUserBottle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUserBottle indicates an expected call of UpsertUserBottle.
func (mr *MockQuerierMockRecorder) UpsertUserBottle(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserBottle", reflect.TypeOf((*MockQuerier)(nil).UpsertUserBottle), ctx, arg)
}

// UpsertUserItem mocks base method.
func (m *MockQuerier) UpsertUserItem(ctx context.Context, arg sqlc.UpsertUserItemParams) (sqlc.InventoryUserItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserItem", ctx, arg)
	ret0, _ := ret[0].(sqlc.InventoryUserItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUserItem indicates an expected call of UpsertUserItem.
func (mr *MockQuerierMockRecorder) UpsertUserItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserItem", reflect.TypeOf((*MockQuerier)(nil).UpsertUserItem), ctx, arg)
}
