import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:lena_mobile/main.dart' as app;

/// LEN-48 audit: captures every reachable screen on a seeded e2e stack.
///
/// Run against the lena2shots compose project (see docs/wiki-screenshots.md):
///   flutter drive \
///     --driver=test_driver/integration_test.dart \
///     --target=integration_test/screenshot_test.dart \
///     -d emulator-5554 \
///     --dart-define=LENA_API_URL=http://10.0.2.2/graphql \
///     --dart-define=LENA_DEBUG_ID_TOKEN=<test-issuer token>
///
/// The debug token signs the app in at startup; every shot lands as
/// mobile-shots/<name>.png on the host.
// Unselected nav labels are hidden (8 fixed tabs) — tap by icon.
const _navIcons = <String, IconData>{
  'Home': Icons.dashboard,
  'Grocery': Icons.shopping_cart,
  'Events': Icons.event,
  'Scan': Icons.qr_code_scanner,
  'Pantry': Icons.kitchen,
  'People': Icons.group,
  'Ask Dot': Icons.auto_awesome,
  'More': Icons.more_horiz,
};

void main() {
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  /// Waits while pumping frames so route transitions and async data
  /// settle — a bare Future.delayed freezes animations mid-flight.
  Future<void> settle(WidgetTester tester,
      [Duration wait = const Duration(seconds: 4)]) async {
    final end = DateTime.now().add(wait);
    while (DateTime.now().isBefore(end)) {
      await tester.pump(const Duration(milliseconds: 100));
    }
  }

  Future<void> shot(WidgetTester tester, String name,
      [Duration wait = const Duration(seconds: 4)]) async {
    await settle(tester, wait);
    await binding.takeScreenshot(name);
    debugPrint('shot: $name');
  }

  Future<void> nav(WidgetTester tester, String label) async {
    final icon = _navIcons[label];
    if (icon == null) {
      debugPrint('nav target missing: $label');
      return;
    }
    final tab = find.descendant(
      of: find.byType(BottomNavigationBar),
      matching: find.byIcon(icon),
    );
    if (tab.evaluate().isNotEmpty) {
      await tester.tap(tab);
      // Bounded settle — pumpAndSettle hangs on infinite animations
      // (spinners on still-loading screens).
      for (var i = 0; i < 20; i++) {
        await tester.pump(const Duration(milliseconds: 100));
      }
      // Diagnostics: log what title the AppBar shows after the tap.
      final titles = find
          .descendant(of: find.byType(AppBar), matching: find.byType(Text))
          .evaluate()
          .map((e) => (e.widget as Text).data)
          .toList();
      debugPrint('nav $label -> AppBar titles: $titles');
    } else {
      debugPrint('nav target missing: $label');
    }
  }

  bool exists(Finder f) => f.evaluate().isNotEmpty;

  /// System-back pop â€” works regardless of whether the AppBar renders a
  /// BackButton, which `tester.pageBack` requires.
  Future<void> back(WidgetTester tester) async {
    await tester.binding.handlePopRoute();
    await tester.pump();
    await Future<void>.delayed(const Duration(milliseconds: 500));
    await tester.pump();
  }

  /// Pops a modal route (dialog/bottom sheet) — system-back works on
  /// any route, unlike a barrier tap that can land on sheet content.
  Future<void> dismissModal(WidgetTester tester) => back(tester);

  Future<bool> tapIfExists(WidgetTester tester, Finder f, String label) async {
    if (exists(f)) {
      await tester.tap(f);
      return true;
    }
    debugPrint('tap target missing: $label');
    return false;
  }

  /// `.first` on an empty finder throws before `exists()` can check;
  /// evaluate the plain finder first, then tap the first match.
  Future<bool> tapFirst(WidgetTester tester, Finder f, String label) async {
    if (exists(f)) {
      await tester.tap(f.first);
      return true;
    }
    debugPrint('tap target missing: $label');
    return false;
  }

  testWidgets('capture all screens', (WidgetTester tester) async {
    app.main();
    await binding.convertFlutterSurfaceToImage();
    await shot(tester, '00-boot', const Duration(seconds: 1));
    await shot(tester, '01-dashboard', const Duration(seconds: 10));

    // â”€â”€ Bottom-nav tabs â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    await nav(tester, 'Grocery');
    await shot(tester, '02-grocery-lists');

    final openedGenerate = await tapIfExists(
        tester, find.byType(FloatingActionButton), 'generate dialog FAB');
    await shot(
        tester, '03-generate-grocery-dialog', const Duration(seconds: 2));
    if (openedGenerate) await dismissModal(tester);

    // Lists sort newest-first — the oldest tile is the seeded list
    // (newest lists generated by earlier runs are often empty).
    final listTiles = find.byType(ListTile);
    var openedList = false;
    if (exists(listTiles)) {
      await tester.tap(listTiles.last);
      openedList = true;
    } else {
      debugPrint('tap target missing: grocery list tile');
    }
    await shot(tester, '04-grocery-list', const Duration(seconds: 6));
    if (openedList) await back(tester);

    await nav(tester, 'Events');
    await shot(tester, '05-events');

    final openedEvent =
        await tapFirst(tester, find.byType(ListTile), 'first event card');
    await shot(tester, '06-event-detail', const Duration(seconds: 6));
    if (openedEvent) {
      final openedTimeline = await tapIfExists(
          tester, find.text('View cooking timeline'), 'timeline button');
      await shot(tester, '07-event-timeline', const Duration(seconds: 6));
      if (openedTimeline) await back(tester);

      final openedEdit =
          await tapIfExists(tester, find.byTooltip('Edit event'), 'edit event');
      await shot(tester, '08-edit-event');
      if (openedEdit) await back(tester);
      await back(tester);
    }

    await nav(tester, 'Pantry');
    await shot(tester, '09-pantry');

    await nav(tester, 'People');
    await shot(tester, '10-household');

    final openedNotif = await tapIfExists(tester,
        find.byTooltip('Notification settings'), 'notification settings gear');
    await shot(tester, '11-notification-settings');
    if (openedNotif) await back(tester);

    await nav(tester, 'Ask Dot');
    await shot(tester, '12-assistant');

    // â”€â”€ More tab destinations â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    await nav(tester, 'More');
    await shot(tester, '13-more');

    final openedRecipes =
        await tapIfExists(tester, find.text('Recipes'), 'recipes tile');
    await shot(tester, '14-recipes', const Duration(seconds: 6));
    if (openedRecipes) {
      final openedFilter = await tapIfExists(
          tester, find.byTooltip('Filter by category'), 'recipe filter');
      await shot(tester, '15-recipe-filter-sheet', const Duration(seconds: 2));
      if (openedFilter) await dismissModal(tester);

      final openedRecipe =
          await tapFirst(tester, find.byType(ListTile), 'first recipe card');
      await shot(tester, '16-edit-recipe', const Duration(seconds: 6));
      if (openedRecipe) await back(tester);

      // LEN-59 — recipe tweaks walk on the seeded "Garlic Butter Pasta"
      // household delta: stale banner + acknowledge, household/original
      // toggle, delta badges, tweaks card, and a tweak sheet.
      final recipeSearch =
          find.widgetWithText(TextField, 'Search recipes');
      if (exists(recipeSearch)) {
        await tester.enterText(recipeSearch, 'pasta');
        await settle(tester);
        final pasta = find.text('Garlic Butter Pasta');
        if (exists(pasta) &&
            await tapFirst(tester, pasta, 'garlic butter pasta tile')) {
          await settle(tester);
          final segments = find.byType(SegmentedButton<String>);
          if (exists(segments)) {
            // Stale banner over the household view with delta badges.
            await shot(tester, '27-recipe-tweaks-stale');
            if (exists(find.text('Mark reviewed'))) {
              await tapFirst(
                  tester, find.text('Mark reviewed'), 'mark reviewed');
              await settle(tester);
              await shot(tester, '28-recipe-tweaks-reviewed');
            }
            // Original view for comparison, then back to household.
            await tapIfExists(
                tester,
                find.descendant(
                    of: segments, matching: find.text('Original')),
                'original segment');
            await settle(tester);
            await shot(tester, '29-recipe-tweaks-original');
            await tapIfExists(
                tester,
                find.descendant(
                    of: segments, matching: find.text('Household')),
                'household segment');
            await settle(tester);
            // Item tweak sheet via a row's Tweak action — while the
            // contents rows are still on screen (the lazy list drops
            // them once the tweaks card scrolls into view).
            if (exists(find.text('Tweak'))) {
              await tapFirst(tester, find.text('Tweak'), 'tweak action');
              await settle(tester);
              await shot(tester, '30-recipe-tweak-sheet');
              await dismissModal(tester);
            }
            // Household tweaks card below the contents list.
            await tester.scrollUntilVisible(
              find.text('Household tweaks'),
              200,
              scrollable: find.byType(Scrollable).first,
            );
            await shot(tester, '31-recipe-tweaks-card');
          }
          await back(tester);
        }
      }

      final openedNew = await tapIfExists(
          tester, find.byType(FloatingActionButton), 'new recipe FAB');
      await shot(tester, '17-new-recipe');
      if (openedNew) await back(tester);

      await back(tester); // back to More
    }

    await nav(tester, 'More');
    final openedMealPlans =
        await tapIfExists(tester, find.text('Meal plans'), 'meal plans tile');
    await shot(tester, '18-meal-plans');
    if (openedMealPlans) {
      final openedPlan =
          await tapFirst(tester, find.byType(ListTile), 'first meal plan card');
      await shot(tester, '19-edit-meal-plan', const Duration(seconds: 6));
      if (openedPlan) await back(tester);
      await back(tester);
    }

    await nav(tester, 'More');
    final openedWine =
        await tapIfExists(tester, find.text('Wine cellar'), 'wine tile');
    await shot(tester, '20-wine', const Duration(seconds: 6));
    if (openedWine) {
      final openedAdjust = await tapIfExists(
          tester,
          find.byWidgetPredicate(
              (w) => w is FloatingActionButton && w.heroTag == 'adjust'),
          'adjust bottle FAB');
      await shot(tester, '21-adjust-bottle');
      if (openedAdjust) await back(tester);

      final openedCatalog = await tapIfExists(
          tester, find.byTooltip('Bottle catalog'), 'bottles button');
      await shot(tester, '22-bottles', const Duration(seconds: 6));
      if (openedCatalog) {
        final openedBottle =
            await tapFirst(tester, find.byType(ListTile), 'first bottle card');
        await shot(tester, '23-edit-bottle', const Duration(seconds: 6));
        if (openedBottle) await back(tester);
        await back(tester);
      }
      await back(tester); // back to More
    }

    await nav(tester, 'More');
    final openedItems =
        await tapIfExists(tester, find.text('Items'), 'items tile');
    await shot(tester, '24-items', const Duration(seconds: 6));
    if (openedItems) {
      final openedItem =
          await tapFirst(tester, find.byType(ListTile), 'first item card');
      await shot(tester, '25-edit-item', const Duration(seconds: 6));
      if (openedItem) await back(tester);
      await back(tester);
    }

    // â”€â”€ Scan last: camera behavior on emulator is itself a finding â”€â”€â”€
    await nav(tester, 'Scan');
    await shot(tester, '26-scan', const Duration(seconds: 6));

    debugPrint('done');
  }, timeout: const Timeout(Duration(minutes: 15)));
}
