// Code generated by MockGen. DO NOT EDIT.
// Source: querier.go
//
// Generated by this command:
//
//	mockgen -source=querier.go -package=mock -destination=mock/querier.go Querier
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/JRAdams472/LENA2/internal/analytics/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// GetGlobalSelectionCounts mocks base method.
func (m *MockQuerier) GetGlobalSelectionCounts(ctx context.Context, arg sqlc.GetGlobalSelectionCountsParams) ([]sqlc.AnalyticsGlobalSelectionCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGlobalSelectionCounts", ctx, arg)
	ret0, _ := ret[0].([]sqlc.AnalyticsGlobalSelectionCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGlobalSelectionCounts indicates an expected call of GetGlobalSelectionCounts.
func (mr *MockQuerierMockRecorder) GetGlobalSelectionCounts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobalSelectionCounts", reflect.TypeOf((*MockQuerier)(nil).GetGlobalSelectionCounts), ctx, arg)
}

// GetUserSelectionCounts mocks base method.
func (m *MockQuerier) GetUserSelectionCounts(ctx context.Context, arg sqlc.GetUserSelectionCountsParams) ([]sqlc.AnalyticsUserSelectionCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSelectionCounts", ctx, arg)
	ret0, _ := ret[0].([]sqlc.AnalyticsUserSelectionCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSelectionCounts indicates an expected call of GetUserSelectionCounts.
func (mr *MockQuerierMockRecorder) GetUserSelectionCounts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSelectionCounts", reflect.TypeOf((*MockQuerier)(nil).GetUserSelectionCounts), ctx, arg)
}

// IngredientOverlapScores mocks base method.
func (m *MockQuerier) IngredientOverlapScores(ctx context.Context, arg sqlc.IngredientOverlapScoresParams) ([]sqlc.IngredientOverlapScoresRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngredientOverlapScores", ctx, arg)
	ret0, _ := ret[0].([]sqlc.IngredientOverlapScoresRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IngredientOverlapScores indicates an expected call of IngredientOverlapScores.
func (mr *MockQuerierMockRecorder) IngredientOverlapScores(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngredientOverlapScores", reflect.TypeOf((*MockQuerier)(nil).IngredientOverlapScores), ctx, arg)
}

// InsertInteractionEvent mocks base method.
func (m *MockQuerier) InsertInteractionEvent(ctx context.Context, arg sqlc.InsertInteractionEventParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertInteractionEvent", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertInteractionEvent indicates an expected call of InsertInteractionEvent.
func (mr *MockQuerierMockRecorder) InsertInteractionEvent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertInteractionEvent", reflect.TypeOf((*MockQuerier)(nil).InsertInteractionEvent), ctx, arg)
}

// ListRecipeRecommendations mocks base method.
func (m *MockQuerier) ListRecipeRecommendations(ctx context.Context, arg sqlc.ListRecipeRecommendationsParams) ([]sqlc.AnalyticsRecipeRecommendation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecipeRecommendations", ctx, arg)
	ret0, _ := ret[0].([]sqlc.AnalyticsRecipeRecommendation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecipeRecommendations indicates an expected call of ListRecipeRecommendations.
func (mr *MockQuerierMockRecorder) ListRecipeRecommendations(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecipeRecommendations", reflect.TypeOf((*MockQuerier)(nil).ListRecipeRecommendations), ctx, arg)
}

// TopGlobalSelections mocks base method.
func (m *MockQuerier) TopGlobalSelections(ctx context.Context, arg sqlc.TopGlobalSelectionsParams) ([]sqlc.AnalyticsGlobalSelectionCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopGlobalSelections", ctx, arg)
	ret0, _ := ret[0].([]sqlc.AnalyticsGlobalSelectionCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TopGlobalSelections indicates an expected call of TopGlobalSelections.
func (mr *MockQuerierMockRecorder) TopGlobalSelections(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopGlobalSelections", reflect.TypeOf((*MockQuerier)(nil).TopGlobalSelections), ctx, arg)
}

// TopUserSelections mocks base method.
func (m *MockQuerier) TopUserSelections(ctx context.Context, arg sqlc.TopUserSelectionsParams) ([]sqlc.AnalyticsUserSelectionCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopUserSelections", ctx, arg)
	ret0, _ := ret[0].([]sqlc.AnalyticsUserSelectionCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TopUserSelections indicates an expected call of TopUserSelections.
func (mr *MockQuerierMockRecorder) TopUserSelections(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopUserSelections", reflect.TypeOf((*MockQuerier)(nil).TopUserSelections), ctx, arg)
}

// UpsertGlobalSelectionCount mocks base method.
func (m *MockQuerier) UpsertGlobalSelectionCount(ctx context.Context, arg sqlc.UpsertGlobalSelectionCountParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertGlobalSelectionCount", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertGlobalSelectionCount indicates an expected call of UpsertGlobalSelectionCount.
func (mr *MockQuerierMockRecorder) UpsertGlobalSelectionCount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertGlobalSelectionCount", reflect.TypeOf((*MockQuerier)(nil).UpsertGlobalSelectionCount), ctx, arg)
}

// UpsertRecipeRecommendation mocks base method.
func (m *MockQuerier) UpsertRecipeRecommendation(ctx context.Context, arg sqlc.UpsertRecipeRecommendationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRecipeRecommendation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertRecipeRecommendation indicates an expected call of UpsertRecipeRecommendation.
func (mr *MockQuerierMockRecorder) UpsertRecipeRecommendation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRecipeRecommendation", reflect.TypeOf((*MockQuerier)(nil).UpsertRecipeRecommendation), ctx, arg)
}

// UpsertUserSelectionCount mocks base method.
func (m *MockQuerier) UpsertUserSelectionCount(ctx context.Context, arg sqlc.UpsertUserSelectionCountParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserSelectionCount", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUserSelectionCount indicates an expected call of UpsertUserSelectionCount.
func (mr *MockQuerierMockRecorder) UpsertUserSelectionCount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserSelectionCount", reflect.TypeOf((*MockQuerier)(nil).UpsertUserSelectionCount), ctx, arg)
}
