// Code generated by MockGen. DO NOT EDIT.
// Source: internal/session/sqlc/querier.go
//
// Generated by this command:
//
//	mockgen -source=internal/session/sqlc/querier.go -package=mock -destination=internal/session/sqlc/mock/querier.go Querier
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/JRAdams472/LENA2/internal/session/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockQuerier) CreateSession(ctx context.Context, arg sqlc.CreateSessionParams) (sqlc.IdentitySession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, arg)
	ret0, _ := ret[0].(sqlc.IdentitySession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockQuerierMockRecorder) CreateSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockQuerier)(nil).CreateSession), ctx, arg)
}

// DeleteExpiredSessions mocks base method.
func (m *MockQuerier) DeleteExpiredSessions(ctx context.Context, arg sqlc.DeleteExpiredSessionsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredSessions", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredSessions indicates an expected call of DeleteExpiredSessions.
func (mr *MockQuerierMockRecorder) DeleteExpiredSessions(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredSessions", reflect.TypeOf((*MockQuerier)(nil).DeleteExpiredSessions), ctx, arg)
}

// GetSessionByIDForUpdate mocks base method.
func (m *MockQuerier) GetSessionByIDForUpdate(ctx context.Context, sessionID int64) (sqlc.IdentitySession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByIDForUpdate", ctx, sessionID)
	ret0, _ := ret[0].(sqlc.IdentitySession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByIDForUpdate indicates an expected call of GetSessionByIDForUpdate.
func (mr *MockQuerierMockRecorder) GetSessionByIDForUpdate(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByIDForUpdate", reflect.TypeOf((*MockQuerier)(nil).GetSessionByIDForUpdate), ctx, sessionID)
}

// GetSessionByRefreshHash mocks base method.
func (m *MockQuerier) GetSessionByRefreshHash(ctx context.Context, refreshHash []byte) (sqlc.IdentitySession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByRefreshHash", ctx, refreshHash)
	ret0, _ := ret[0].(sqlc.IdentitySession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByRefreshHash indicates an expected call of GetSessionByRefreshHash.
func (mr *MockQuerierMockRecorder) GetSessionByRefreshHash(ctx, refreshHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByRefreshHash", reflect.TypeOf((*MockQuerier)(nil).GetSessionByRefreshHash), ctx, refreshHash)
}

// InsertRotatedSession mocks base method.
func (m *MockQuerier) InsertRotatedSession(ctx context.Context, arg sqlc.InsertRotatedSessionParams) (sqlc.IdentitySession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRotatedSession", ctx, arg)
	ret0, _ := ret[0].(sqlc.IdentitySession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertRotatedSession indicates an expected call of InsertRotatedSession.
func (mr *MockQuerierMockRecorder) InsertRotatedSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRotatedSession", reflect.TypeOf((*MockQuerier)(nil).InsertRotatedSession), ctx, arg)
}

// MarkSessionReplaced mocks base method.
func (m *MockQuerier) MarkSessionReplaced(ctx context.Context, arg sqlc.MarkSessionReplacedParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSessionReplaced", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkSessionReplaced indicates an expected call of MarkSessionReplaced.
func (mr *MockQuerierMockRecorder) MarkSessionReplaced(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSessionReplaced", reflect.TypeOf((*MockQuerier)(nil).MarkSessionReplaced), ctx, arg)
}

// RevokeSession mocks base method.
func (m *MockQuerier) RevokeSession(ctx context.Context, sessionID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSession", ctx, sessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeSession indicates an expected call of RevokeSession.
func (mr *MockQuerierMockRecorder) RevokeSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSession", reflect.TypeOf((*MockQuerier)(nil).RevokeSession), ctx, sessionID)
}

// RevokeSessionFamily mocks base method.
func (m *MockQuerier) RevokeSessionFamily(ctx context.Context, familyID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSessionFamily", ctx, familyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSessionFamily indicates an expected call of RevokeSessionFamily.
func (mr *MockQuerierMockRecorder) RevokeSessionFamily(ctx, familyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessionFamily", reflect.TypeOf((*MockQuerier)(nil).RevokeSessionFamily), ctx, familyID)
}
