// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPendingInvitesFrom = `-- name: CancelPendingInvitesFrom :many
UPDATE household.invites
SET status     = 'cancelled',
    updated_by = $3,
    updated_at = now()
WHERE from_user_id = $1
  AND household_id = $2
  AND status = 'pending'
RETURNING invite_id, from_user_id, to_user_id, household_id, status, created_by, created_at, updated_by, updated_at
`

type CancelPendingInvitesFromParams struct {
	FromUserID  int64       `json:"from_user_id"`
	HouseholdID int64       `json:"household_id"`
	UpdatedBy   pgtype.Text `json:"updated_by"`
}

// Leave/remove cleanup: pending invites a departing member sent for that
// household are cancelled so they can no longer be accepted against a
// household the sender no longer belongs to.
func (q *Queries) CancelPendingInvitesFrom(ctx context.Context, arg CancelPendingInvitesFromParams) ([]HouseholdInvite, error) {
	rows, err := q.db.Query(ctx, cancelPendingInvitesFrom, arg.FromUserID, arg.HouseholdID, arg.UpdatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HouseholdInvite{}
	for rows.Next() {
		var i HouseholdInvite
		if err := rows.Scan(
			&i.InviteID,
			&i.FromUserID,
			&i.ToUserID,
			&i.HouseholdID,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMembers = `-- name: CountMembers :one
SELECT count(*)
FROM household.household_member
WHERE household_id = $1
`

func (q *Queries) CountMembers(ctx context.Context, householdID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMembers, householdID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)
FROM household.notifications
WHERE user_id = $1
  AND read_at IS NULL
  AND (household_id IS NULL OR household_id = $2)
`

type CountUnreadNotificationsParams struct {
	UserID      int64       `json:"user_id"`
	HouseholdID pgtype.Int8 `json:"household_id"`
}

func (q *Queries) CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, arg.UserID, arg.HouseholdID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO household.households (created_by)
VALUES ($1)
RETURNING household_id, created_by, created_at, updated_at, name, updated_by
`

func (q *Queries) CreateHousehold(ctx context.Context, createdBy string) (HouseholdHousehold, error) {
	row := q.db.QueryRow(ctx, createHousehold, createdBy)
	var i HouseholdHousehold
	err := row.Scan(
		&i.HouseholdID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.UpdatedBy,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO household.invites (from_user_id, to_user_id, household_id, created_by)
VALUES ($1, $2, $3, $4)
RETURNING invite_id, from_user_id, to_user_id, household_id, status, created_by, created_at, updated_by, updated_at
`

type CreateInviteParams struct {
	FromUserID  int64  `json:"from_user_id"`
	ToUserID    int64  `json:"to_user_id"`
	HouseholdID int64  `json:"household_id"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (HouseholdInvite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.FromUserID,
		arg.ToUserID,
		arg.HouseholdID,
		arg.CreatedBy,
	)
	var i HouseholdInvite
	err := row.Scan(
		&i.InviteID,
		&i.FromUserID,
		&i.ToUserID,
		&i.HouseholdID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO household.notifications
    (user_id, household_id, kind, actor_user_id, invite_id, food_event_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING notification_id, user_id, household_id, kind, actor_user_id, invite_id, read_at, created_at, food_event_id, title, body, recipe_id, item_id, dedup_key
`

type CreateNotificationParams struct {
	UserID      int64       `json:"user_id"`
	HouseholdID pgtype.Int8 `json:"household_id"`
	Kind        string      `json:"kind"`
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	InviteID    pgtype.Int8 `json:"invite_id"`
	FoodEventID pgtype.Int8 `json:"food_event_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (HouseholdNotification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.HouseholdID,
		arg.Kind,
		arg.ActorUserID,
		arg.InviteID,
		arg.FoodEventID,
	)
	var i HouseholdNotification
	err := row.Scan(
		&i.NotificationID,
		&i.UserID,
		&i.HouseholdID,
		&i.Kind,
		&i.ActorUserID,
		&i.InviteID,
		&i.ReadAt,
		&i.CreatedAt,
		&i.FoodEventID,
		&i.Title,
		&i.Body,
		&i.RecipeID,
		&i.ItemID,
		&i.DedupKey,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :execrows
DELETE FROM household.household_member
WHERE household_id = $1
  AND user_id = $2
`

type DeleteMembershipParams struct {
	HouseholdID int64 `json:"household_id"`
	UserID      int64 `json:"user_id"`
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMembership, arg.HouseholdID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getHouseholdByID = `-- name: GetHouseholdByID :one
SELECT household_id, created_by, created_at, updated_at, name, updated_by
FROM household.households
WHERE household_id = $1
`

func (q *Queries) GetHouseholdByID(ctx context.Context, householdID int64) (HouseholdHousehold, error) {
	row := q.db.QueryRow(ctx, getHouseholdByID, householdID)
	var i HouseholdHousehold
	err := row.Scan(
		&i.HouseholdID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.UpdatedBy,
	)
	return i, err
}

const getHouseholdByIDForUpdate = `-- name: GetHouseholdByIDForUpdate :one
SELECT household_id, created_by, created_at, updated_at, name, updated_by
FROM household.households
WHERE household_id = $1
FOR UPDATE
`

// Row lock: serialize member-count checks and membership transitions for
// concurrent accept/leave/remove operations against the same household.
func (q *Queries) GetHouseholdByIDForUpdate(ctx context.Context, householdID int64) (HouseholdHousehold, error) {
	row := q.db.QueryRow(ctx, getHouseholdByIDForUpdate, householdID)
	var i HouseholdHousehold
	err := row.Scan(
		&i.HouseholdID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.UpdatedBy,
	)
	return i, err
}

const getInviteByID = `-- name: GetInviteByID :one
SELECT invite_id, from_user_id, to_user_id, household_id, status, created_by, created_at, updated_by, updated_at
FROM household.invites
WHERE invite_id = $1
`

func (q *Queries) GetInviteByID(ctx context.Context, inviteID int64) (HouseholdInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByID, inviteID)
	var i HouseholdInvite
	err := row.Scan(
		&i.InviteID,
		&i.FromUserID,
		&i.ToUserID,
		&i.HouseholdID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one

SELECT household_id, user_id, role, created_by, created_at, updated_by, updated_at
FROM household.household_member
WHERE household_id = $1
  AND user_id = $2
`

type GetMembershipParams struct {
	HouseholdID int64 `json:"household_id"`
	UserID      int64 `json:"user_id"`
}

// ---------- membership (LEN-26) ----------
func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (HouseholdHouseholdMember, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.HouseholdID, arg.UserID)
	var i HouseholdHouseholdMember
	err := row.Scan(
		&i.HouseholdID,
		&i.UserID,
		&i.Role,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPushDelivery = `-- name: InsertPushDelivery :execresult
INSERT INTO household.push_delivery
    (user_id, kind, household_id, actor_user_id, invite_id, food_event_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPushDeliveryParams struct {
	UserID      int64       `json:"user_id"`
	Kind        string      `json:"kind"`
	HouseholdID pgtype.Int8 `json:"household_id"`
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	InviteID    pgtype.Int8 `json:"invite_id"`
	FoodEventID pgtype.Int8 `json:"food_event_id"`
}

// Outbox row for the push channel — written in the same transaction as
// the feed notification (or instead of it when push-only is enabled).
// Event-driven rows carry no dedup_key; NULLs never conflict.
func (q *Queries) InsertPushDelivery(ctx context.Context, arg InsertPushDeliveryParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, insertPushDelivery,
		arg.UserID,
		arg.Kind,
		arg.HouseholdID,
		arg.ActorUserID,
		arg.InviteID,
		arg.FoodEventID,
	)
}

const listHouseholdsByUser = `-- name: ListHouseholdsByUser :many
SELECT h.household_id, h.created_by, h.created_at, h.updated_at, h.name, h.updated_by, m.role AS member_role
FROM household.households h
JOIN household.household_member m
  ON m.household_id = h.household_id
WHERE m.user_id = $1
ORDER BY m.created_at
`

type ListHouseholdsByUserRow struct {
	HouseholdID int64              `json:"household_id"`
	CreatedBy   string             `json:"created_by"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Name        pgtype.Text        `json:"name"`
	UpdatedBy   pgtype.Text        `json:"updated_by"`
	MemberRole  string             `json:"member_role"`
}

// The user's households with their role in each — backs the switcher.
func (q *Queries) ListHouseholdsByUser(ctx context.Context, userID int64) ([]ListHouseholdsByUserRow, error) {
	rows, err := q.db.Query(ctx, listHouseholdsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHouseholdsByUserRow{}
	for rows.Next() {
		var i ListHouseholdsByUserRow
		if err := rows.Scan(
			&i.HouseholdID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.UpdatedBy,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersByHousehold = `-- name: ListMembersByHousehold :many
SELECT household_id, user_id, role, created_by, created_at, updated_by, updated_at
FROM household.household_member
WHERE household_id = $1
ORDER BY created_at
`

func (q *Queries) ListMembersByHousehold(ctx context.Context, householdID int64) ([]HouseholdHouseholdMember, error) {
	rows, err := q.db.Query(ctx, listMembersByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HouseholdHouseholdMember{}
	for rows.Next() {
		var i HouseholdHouseholdMember
		if err := rows.Scan(
			&i.HouseholdID,
			&i.UserID,
			&i.Role,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT household_id, user_id, role, created_by, created_at, updated_by, updated_at
FROM household.household_member
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListMembershipsByUser(ctx context.Context, userID int64) ([]HouseholdHouseholdMember, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HouseholdHouseholdMember{}
	for rows.Next() {
		var i HouseholdHouseholdMember
		if err := rows.Scan(
			&i.HouseholdID,
			&i.UserID,
			&i.Role,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT notification_id, user_id, household_id, kind, actor_user_id, invite_id, read_at, created_at, food_event_id, title, body, recipe_id, item_id, dedup_key
FROM household.notifications
WHERE user_id = $1
  AND (household_id IS NULL OR household_id = $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListNotificationsForUserParams struct {
	UserID      int64       `json:"user_id"`
	HouseholdID pgtype.Int8 `json:"household_id"`
	Limit       int32       `json:"limit"`
}

// Feeds scope to the active household (LEN-26); notifications without a
// household_id are user-global and still show.
func (q *Queries) ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]HouseholdNotification, error) {
	rows, err := q.db.Query(ctx, listNotificationsForUser, arg.UserID, arg.HouseholdID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HouseholdNotification{}
	for rows.Next() {
		var i HouseholdNotification
		if err := rows.Scan(
			&i.NotificationID,
			&i.UserID,
			&i.HouseholdID,
			&i.Kind,
			&i.ActorUserID,
			&i.InviteID,
			&i.ReadAt,
			&i.CreatedAt,
			&i.FoodEventID,
			&i.Title,
			&i.Body,
			&i.RecipeID,
			&i.ItemID,
			&i.DedupKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitesForUser = `-- name: ListPendingInvitesForUser :many
SELECT invite_id, from_user_id, to_user_id, household_id, status, created_by, created_at, updated_by, updated_at
FROM household.invites
WHERE to_user_id = $1
  AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvitesForUser(ctx context.Context, toUserID int64) ([]HouseholdInvite, error) {
	rows, err := q.db.Query(ctx, listPendingInvitesForUser, toUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HouseholdInvite{}
	for rows.Next() {
		var i HouseholdInvite
		if err := rows.Scan(
			&i.InviteID,
			&i.FromUserID,
			&i.ToUserID,
			&i.HouseholdID,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentInvitesForUser = `-- name: ListSentInvitesForUser :many
SELECT invite_id, from_user_id, to_user_id, household_id, status, created_by, created_at, updated_by, updated_at
FROM household.invites
WHERE from_user_id = $1
  AND household_id = $2
  AND status = 'pending'
ORDER BY created_at DESC
`

type ListSentInvitesForUserParams struct {
	FromUserID  int64 `json:"from_user_id"`
	HouseholdID int64 `json:"household_id"`
}

// Sent invites scope to a household (the caller's active one); the
// received-invite list (ListPendingInvitesForUser) stays unscoped.
func (q *Queries) ListSentInvitesForUser(ctx context.Context, arg ListSentInvitesForUserParams) ([]HouseholdInvite, error) {
	rows, err := q.db.Query(ctx, listSentInvitesForUser, arg.FromUserID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HouseholdInvite{}
	for rows.Next() {
		var i HouseholdInvite
		if err := rows.Scan(
			&i.InviteID,
			&i.FromUserID,
			&i.ToUserID,
			&i.HouseholdID,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE household.notifications
SET read_at = now()
WHERE user_id = $1
  AND read_at IS NULL
  AND (household_id IS NULL OR household_id = $2)
`

type MarkAllNotificationsReadParams struct {
	UserID      int64       `json:"user_id"`
	HouseholdID pgtype.Int8 `json:"household_id"`
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, arg.UserID, arg.HouseholdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneReadNotifications = `-- name: PruneReadNotifications :exec
DELETE FROM household.notifications n
WHERE n.user_id = $1
  AND n.read_at IS NOT NULL
  AND n.notification_id NOT IN (
      SELECT k.notification_id
      FROM household.notifications k
      WHERE k.user_id = $1
        AND k.read_at IS NOT NULL
      ORDER BY k.created_at DESC
      LIMIT 100
  )
`

// Retention: keep at most the 100 most recent read notifications per user;
// called inside the same transaction as CreateNotification.
func (q *Queries) PruneReadNotifications(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, pruneReadNotifications, userID)
	return err
}

const renameHousehold = `-- name: RenameHousehold :one
UPDATE household.households
SET name       = $2,
    updated_by = $3,
    updated_at = now()
WHERE household_id = $1
RETURNING household_id, created_by, created_at, updated_at, name, updated_by
`

type RenameHouseholdParams struct {
	HouseholdID int64       `json:"household_id"`
	Name        pgtype.Text `json:"name"`
	UpdatedBy   pgtype.Text `json:"updated_by"`
}

func (q *Queries) RenameHousehold(ctx context.Context, arg RenameHouseholdParams) (HouseholdHousehold, error) {
	row := q.db.QueryRow(ctx, renameHousehold, arg.HouseholdID, arg.Name, arg.UpdatedBy)
	var i HouseholdHousehold
	err := row.Scan(
		&i.HouseholdID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.UpdatedBy,
	)
	return i, err
}

const transitionInvite = `-- name: TransitionInvite :one
UPDATE household.invites
SET status     = $2,
    updated_by = $3,
    updated_at = now()
WHERE invite_id = $1
  AND status = 'pending'
RETURNING invite_id, from_user_id, to_user_id, household_id, status, created_by, created_at, updated_by, updated_at
`

type TransitionInviteParams struct {
	InviteID  int64       `json:"invite_id"`
	Status    string      `json:"status"`
	UpdatedBy pgtype.Text `json:"updated_by"`
}

// Status-guarded: only a pending invite can transition, so a concurrent
// accept/decline/cancel loses with zero rows instead of a lost update.
func (q *Queries) TransitionInvite(ctx context.Context, arg TransitionInviteParams) (HouseholdInvite, error) {
	row := q.db.QueryRow(ctx, transitionInvite, arg.InviteID, arg.Status, arg.UpdatedBy)
	var i HouseholdInvite
	err := row.Scan(
		&i.InviteID,
		&i.FromUserID,
		&i.ToUserID,
		&i.HouseholdID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMembership = `-- name: UpsertMembership :one
INSERT INTO household.household_member (household_id, user_id, role, created_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (household_id, user_id) DO UPDATE
SET role       = EXCLUDED.role,
    updated_by = EXCLUDED.created_by,
    updated_at = now()
RETURNING household_id, user_id, role, created_by, created_at, updated_by, updated_at
`

type UpsertMembershipParams struct {
	HouseholdID int64  `json:"household_id"`
	UserID      int64  `json:"user_id"`
	Role        string `json:"role"`
	CreatedBy   string `json:"created_by"`
}

// Joins a user to a household; on re-join the role is refreshed. The
// caller's users-row active pointer syncs separately (identity service),
// inside the same ambient transaction.
func (q *Queries) UpsertMembership(ctx context.Context, arg UpsertMembershipParams) (HouseholdHouseholdMember, error) {
	row := q.db.QueryRow(ctx, upsertMembership,
		arg.HouseholdID,
		arg.UserID,
		arg.Role,
		arg.CreatedBy,
	)
	var i HouseholdHouseholdMember
	err := row.Scan(
		&i.HouseholdID,
		&i.UserID,
		&i.Role,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
