// Code generated by MockGen. DO NOT EDIT.
// Source: internal/notifier/sqlc/querier.go
//
// Generated by this command:
//
//	mockgen -source=internal/notifier/sqlc/querier.go -package=mock -destination=internal/notifier/sqlc/mock/querier.go Querier
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/JRAdams472/LENA2/internal/notifier/sqlc"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// DeleteDeviceToken mocks base method.
func (m *MockQuerier) DeleteDeviceToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDeviceToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDeviceToken indicates an expected call of DeleteDeviceToken.
func (mr *MockQuerierMockRecorder) DeleteDeviceToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDeviceToken", reflect.TypeOf((*MockQuerier)(nil).DeleteDeviceToken), ctx, token)
}

// DeleteDeviceTokenForUser mocks base method.
func (m *MockQuerier) DeleteDeviceTokenForUser(ctx context.Context, arg sqlc.DeleteDeviceTokenForUserParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDeviceTokenForUser", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDeviceTokenForUser indicates an expected call of DeleteDeviceTokenForUser.
func (mr *MockQuerierMockRecorder) DeleteDeviceTokenForUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDeviceTokenForUser", reflect.TypeOf((*MockQuerier)(nil).DeleteDeviceTokenForUser), ctx, arg)
}

// GetNotificationTypeCategory mocks base method.
func (m *MockQuerier) GetNotificationTypeCategory(ctx context.Context, kind string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationTypeCategory", ctx, kind)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationTypeCategory indicates an expected call of GetNotificationTypeCategory.
func (mr *MockQuerierMockRecorder) GetNotificationTypeCategory(ctx, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationTypeCategory", reflect.TypeOf((*MockQuerier)(nil).GetNotificationTypeCategory), ctx, kind)
}

// InsertItemReminderNotification mocks base method.
func (m *MockQuerier) InsertItemReminderNotification(ctx context.Context, arg sqlc.InsertItemReminderNotificationParams) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertItemReminderNotification", ctx, arg)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertItemReminderNotification indicates an expected call of InsertItemReminderNotification.
func (mr *MockQuerierMockRecorder) InsertItemReminderNotification(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertItemReminderNotification", reflect.TypeOf((*MockQuerier)(nil).InsertItemReminderNotification), ctx, arg)
}

// InsertPushDelivery mocks base method.
func (m *MockQuerier) InsertPushDelivery(ctx context.Context, arg sqlc.InsertPushDeliveryParams) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPushDelivery", ctx, arg)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertPushDelivery indicates an expected call of InsertPushDelivery.
func (mr *MockQuerierMockRecorder) InsertPushDelivery(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPushDelivery", reflect.TypeOf((*MockQuerier)(nil).InsertPushDelivery), ctx, arg)
}

// InsertRecipeReminderNotification mocks base method.
func (m *MockQuerier) InsertRecipeReminderNotification(ctx context.Context, arg sqlc.InsertRecipeReminderNotificationParams) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRecipeReminderNotification", ctx, arg)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertRecipeReminderNotification indicates an expected call of InsertRecipeReminderNotification.
func (mr *MockQuerierMockRecorder) InsertRecipeReminderNotification(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRecipeReminderNotification", reflect.TypeOf((*MockQuerier)(nil).InsertRecipeReminderNotification), ctx, arg)
}

// ListActiveNotificationTypes mocks base method.
func (m *MockQuerier) ListActiveNotificationTypes(ctx context.Context) ([]sqlc.ListActiveNotificationTypesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveNotificationTypes", ctx)
	ret0, _ := ret[0].([]sqlc.ListActiveNotificationTypesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveNotificationTypes indicates an expected call of ListActiveNotificationTypes.
func (mr *MockQuerierMockRecorder) ListActiveNotificationTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveNotificationTypes", reflect.TypeOf((*MockQuerier)(nil).ListActiveNotificationTypes), ctx)
}

// ListDeviceTokensForUsers mocks base method.
func (m *MockQuerier) ListDeviceTokensForUsers(ctx context.Context, userIds []int64) ([]sqlc.IdentityDeviceToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeviceTokensForUsers", ctx, userIds)
	ret0, _ := ret[0].([]sqlc.IdentityDeviceToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeviceTokensForUsers indicates an expected call of ListDeviceTokensForUsers.
func (mr *MockQuerierMockRecorder) ListDeviceTokensForUsers(ctx, userIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeviceTokensForUsers", reflect.TypeOf((*MockQuerier)(nil).ListDeviceTokensForUsers), ctx, userIds)
}

// ListDisplayNamesForUsers mocks base method.
func (m *MockQuerier) ListDisplayNamesForUsers(ctx context.Context, userIds []int64) ([]sqlc.ListDisplayNamesForUsersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDisplayNamesForUsers", ctx, userIds)
	ret0, _ := ret[0].([]sqlc.ListDisplayNamesForUsersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDisplayNamesForUsers indicates an expected call of ListDisplayNamesForUsers.
func (mr *MockQuerierMockRecorder) ListDisplayNamesForUsers(ctx, userIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDisplayNamesForUsers", reflect.TypeOf((*MockQuerier)(nil).ListDisplayNamesForUsers), ctx, userIds)
}

// ListDuePushDeliveries mocks base method.
func (m *MockQuerier) ListDuePushDeliveries(ctx context.Context, limit int32) ([]sqlc.HouseholdPushDelivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDuePushDeliveries", ctx, limit)
	ret0, _ := ret[0].([]sqlc.HouseholdPushDelivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDuePushDeliveries indicates an expected call of ListDuePushDeliveries.
func (mr *MockQuerierMockRecorder) ListDuePushDeliveries(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDuePushDeliveries", reflect.TypeOf((*MockQuerier)(nil).ListDuePushDeliveries), ctx, limit)
}

// ListExpiringHouseholdItems mocks base method.
func (m *MockQuerier) ListExpiringHouseholdItems(ctx context.Context, arg sqlc.ListExpiringHouseholdItemsParams) ([]sqlc.ListExpiringHouseholdItemsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpiringHouseholdItems", ctx, arg)
	ret0, _ := ret[0].([]sqlc.ListExpiringHouseholdItemsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpiringHouseholdItems indicates an expected call of ListExpiringHouseholdItems.
func (mr *MockQuerierMockRecorder) ListExpiringHouseholdItems(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpiringHouseholdItems", reflect.TypeOf((*MockQuerier)(nil).ListExpiringHouseholdItems), ctx, arg)
}

// ListLongStepsForRecipes mocks base method.
func (m *MockQuerier) ListLongStepsForRecipes(ctx context.Context, recipeIds []int64) ([]sqlc.ListLongStepsForRecipesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLongStepsForRecipes", ctx, recipeIds)
	ret0, _ := ret[0].([]sqlc.ListLongStepsForRecipesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLongStepsForRecipes indicates an expected call of ListLongStepsForRecipes.
func (mr *MockQuerierMockRecorder) ListLongStepsForRecipes(ctx, recipeIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLongStepsForRecipes", reflect.TypeOf((*MockQuerier)(nil).ListLongStepsForRecipes), ctx, recipeIds)
}

// ListMealSlotsWithRecipes mocks base method.
func (m *MockQuerier) ListMealSlotsWithRecipes(ctx context.Context) ([]sqlc.ListMealSlotsWithRecipesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMealSlotsWithRecipes", ctx)
	ret0, _ := ret[0].([]sqlc.ListMealSlotsWithRecipesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMealSlotsWithRecipes indicates an expected call of ListMealSlotsWithRecipes.
func (mr *MockQuerierMockRecorder) ListMealSlotsWithRecipes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMealSlotsWithRecipes", reflect.TypeOf((*MockQuerier)(nil).ListMealSlotsWithRecipes), ctx)
}

// ListMemberIDsForHouseholds mocks base method.
func (m *MockQuerier) ListMemberIDsForHouseholds(ctx context.Context, householdIds []int64) ([]sqlc.ListMemberIDsForHouseholdsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMemberIDsForHouseholds", ctx, householdIds)
	ret0, _ := ret[0].([]sqlc.ListMemberIDsForHouseholdsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMemberIDsForHouseholds indicates an expected call of ListMemberIDsForHouseholds.
func (mr *MockQuerierMockRecorder) ListMemberIDsForHouseholds(ctx, householdIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMemberIDsForHouseholds", reflect.TypeOf((*MockQuerier)(nil).ListMemberIDsForHouseholds), ctx, householdIds)
}

// ListNotificationPrefs mocks base method.
func (m *MockQuerier) ListNotificationPrefs(ctx context.Context, userID int64) ([]sqlc.UserprefsNotificationPref, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotificationPrefs", ctx, userID)
	ret0, _ := ret[0].([]sqlc.UserprefsNotificationPref)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotificationPrefs indicates an expected call of ListNotificationPrefs.
func (mr *MockQuerierMockRecorder) ListNotificationPrefs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotificationPrefs", reflect.TypeOf((*MockQuerier)(nil).ListNotificationPrefs), ctx, userID)
}

// ListProteinItemsForRecipes mocks base method.
func (m *MockQuerier) ListProteinItemsForRecipes(ctx context.Context, recipeIds []int64) ([]sqlc.ListProteinItemsForRecipesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProteinItemsForRecipes", ctx, recipeIds)
	ret0, _ := ret[0].([]sqlc.ListProteinItemsForRecipesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProteinItemsForRecipes indicates an expected call of ListProteinItemsForRecipes.
func (mr *MockQuerierMockRecorder) ListProteinItemsForRecipes(ctx, recipeIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProteinItemsForRecipes", reflect.TypeOf((*MockQuerier)(nil).ListProteinItemsForRecipes), ctx, recipeIds)
}

// MarkPushDeliveryFailed mocks base method.
func (m *MockQuerier) MarkPushDeliveryFailed(ctx context.Context, arg sqlc.MarkPushDeliveryFailedParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPushDeliveryFailed", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPushDeliveryFailed indicates an expected call of MarkPushDeliveryFailed.
func (mr *MockQuerierMockRecorder) MarkPushDeliveryFailed(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPushDeliveryFailed", reflect.TypeOf((*MockQuerier)(nil).MarkPushDeliveryFailed), ctx, arg)
}

// MarkPushDeliveryRetry mocks base method.
func (m *MockQuerier) MarkPushDeliveryRetry(ctx context.Context, arg sqlc.MarkPushDeliveryRetryParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPushDeliveryRetry", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPushDeliveryRetry indicates an expected call of MarkPushDeliveryRetry.
func (mr *MockQuerierMockRecorder) MarkPushDeliveryRetry(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPushDeliveryRetry", reflect.TypeOf((*MockQuerier)(nil).MarkPushDeliveryRetry), ctx, arg)
}

// MarkPushDeliverySending mocks base method.
func (m *MockQuerier) MarkPushDeliverySending(ctx context.Context, pushDeliveryID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPushDeliverySending", ctx, pushDeliveryID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkPushDeliverySending indicates an expected call of MarkPushDeliverySending.
func (mr *MockQuerierMockRecorder) MarkPushDeliverySending(ctx, pushDeliveryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPushDeliverySending", reflect.TypeOf((*MockQuerier)(nil).MarkPushDeliverySending), ctx, pushDeliveryID)
}

// MarkPushDeliverySent mocks base method.
func (m *MockQuerier) MarkPushDeliverySent(ctx context.Context, pushDeliveryID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPushDeliverySent", ctx, pushDeliveryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPushDeliverySent indicates an expected call of MarkPushDeliverySent.
func (mr *MockQuerierMockRecorder) MarkPushDeliverySent(ctx, pushDeliveryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPushDeliverySent", reflect.TypeOf((*MockQuerier)(nil).MarkPushDeliverySent), ctx, pushDeliveryID)
}

// PruneReadNotifications mocks base method.
func (m *MockQuerier) PruneReadNotifications(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PruneReadNotifications", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PruneReadNotifications indicates an expected call of PruneReadNotifications.
func (mr *MockQuerierMockRecorder) PruneReadNotifications(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PruneReadNotifications", reflect.TypeOf((*MockQuerier)(nil).PruneReadNotifications), ctx, userID)
}

// UpsertDeviceToken mocks base method.
func (m *MockQuerier) UpsertDeviceToken(ctx context.Context, arg sqlc.UpsertDeviceTokenParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDeviceToken", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertDeviceToken indicates an expected call of UpsertDeviceToken.
func (mr *MockQuerierMockRecorder) UpsertDeviceToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDeviceToken", reflect.TypeOf((*MockQuerier)(nil).UpsertDeviceToken), ctx, arg)
}

// UpsertNotificationPref mocks base method.
func (m *MockQuerier) UpsertNotificationPref(ctx context.Context, arg sqlc.UpsertNotificationPrefParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertNotificationPref", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertNotificationPref indicates an expected call of UpsertNotificationPref.
func (mr *MockQuerierMockRecorder) UpsertNotificationPref(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertNotificationPref", reflect.TypeOf((*MockQuerier)(nil).UpsertNotificationPref), ctx, arg)
}

// UpsertNotificationPrefPushEnabled mocks base method.
func (m *MockQuerier) UpsertNotificationPrefPushEnabled(ctx context.Context, arg sqlc.UpsertNotificationPrefPushEnabledParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertNotificationPrefPushEnabled", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertNotificationPrefPushEnabled indicates an expected call of UpsertNotificationPrefPushEnabled.
func (mr *MockQuerierMockRecorder) UpsertNotificationPrefPushEnabled(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertNotificationPrefPushEnabled", reflect.TypeOf((*MockQuerier)(nil).UpsertNotificationPrefPushEnabled), ctx, arg)
}
