// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const conditionalSetUserActive = `-- name: ConditionalSetUserActive :execrows
UPDATE identity.users AS u
SET is_active  = $2,
    updated_by = $3,
    updated_at = now()
WHERE u.user_id = $1
  AND ($2 = true OR (
    SELECT count(*) FROM identity.users AS other
    WHERE other.role = 'admin'
      AND other.is_active
      AND other.user_id <> u.user_id
  ) >= 1)
`

type ConditionalSetUserActiveParams struct {
	UserID    int64       `json:"user_id"`
	IsActive  bool        `json:"is_active"`
	UpdatedBy pgtype.Text `json:"updated_by"`
}

func (q *Queries) ConditionalSetUserActive(ctx context.Context, arg ConditionalSetUserActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, conditionalSetUserActive, arg.UserID, arg.IsActive, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const conditionalSetUserRole = `-- name: ConditionalSetUserRole :execrows
UPDATE identity.users AS u
SET role       = $2,
    updated_at = now()
WHERE u.user_id = $1
  AND ($2 = 'admin' OR (
    SELECT count(*) FROM identity.users AS other
    WHERE other.role = 'admin'
      AND other.is_active
      AND other.user_id <> u.user_id
  ) >= 1)
`

type ConditionalSetUserRoleParams struct {
	UserID int64  `json:"user_id"`
	Role   string `json:"role"`
}

func (q *Queries) ConditionalSetUserRole(ctx context.Context, arg ConditionalSetUserRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, conditionalSetUserRole, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(*)
FROM identity.users
WHERE role = 'admin'
  AND is_active
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLoginsByUser = `-- name: CountLoginsByUser :one
SELECT count(*)
FROM identity.user_login
WHERE user_id = $1
`

func (q *Queries) CountLoginsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLoginsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*)
FROM identity.users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByHousehold = `-- name: CountUsersByHousehold :one
SELECT count(*)
FROM household.household_member
WHERE household_id = $1
`

// Membership table is the source of truth (LEN-26): a member's active
// pointer (users.household_id) may sit on a different household.
func (q *Queries) CountUsersByHousehold(ctx context.Context, householdID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByHousehold, householdID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLoginsByProvider = `-- name: DeleteLoginsByProvider :execrows
DELETE FROM identity.user_login
WHERE user_id = $1
  AND provider = $2
`

type DeleteLoginsByProviderParams struct {
	UserID   int64  `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) DeleteLoginsByProvider(ctx context.Context, arg DeleteLoginsByProviderParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLoginsByProvider, arg.UserID, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, provider, external_subject, email, display_name, is_active, last_login_at, created_by, created_at, updated_by, updated_at, role, first_name, last_name, backup_email, household_id, is_searchable, household_role, birthdate
FROM identity.users
WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID int64) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i IdentityUser
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.ExternalSubject,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.BackupEmail,
		&i.HouseholdID,
		&i.IsSearchable,
		&i.HouseholdRole,
		&i.Birthdate,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT u.user_id, u.provider, u.external_subject, u.email, u.display_name, u.is_active, u.last_login_at, u.created_by, u.created_at, u.updated_by, u.updated_at, u.role, u.first_name, u.last_name, u.backup_email, u.household_id, u.is_searchable, u.household_role, u.birthdate
FROM identity.users AS u
JOIN identity.user_login AS l ON l.user_id = u.user_id
WHERE l.provider = $1
  AND l.external_subject = $2
`

type GetUserByLoginParams struct {
	Provider        string `json:"provider"`
	ExternalSubject string `json:"external_subject"`
}

// Resolves a provider identity to its user via the login mapping table —
// covers both primary logins and explicitly linked ones.
func (q *Queries) GetUserByLogin(ctx context.Context, arg GetUserByLoginParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, arg.Provider, arg.ExternalSubject)
	var i IdentityUser
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.ExternalSubject,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.BackupEmail,
		&i.HouseholdID,
		&i.IsSearchable,
		&i.HouseholdRole,
		&i.Birthdate,
	)
	return i, err
}

const getUserByProviderSubject = `-- name: GetUserByProviderSubject :one
SELECT user_id, provider, external_subject, email, display_name, is_active, last_login_at, created_by, created_at, updated_by, updated_at, role, first_name, last_name, backup_email, household_id, is_searchable, household_role, birthdate
FROM identity.users
WHERE provider = $1
  AND external_subject = $2
`

type GetUserByProviderSubjectParams struct {
	Provider        string `json:"provider"`
	ExternalSubject string `json:"external_subject"`
}

func (q *Queries) GetUserByProviderSubject(ctx context.Context, arg GetUserByProviderSubjectParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByProviderSubject, arg.Provider, arg.ExternalSubject)
	var i IdentityUser
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.ExternalSubject,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.BackupEmail,
		&i.HouseholdID,
		&i.IsSearchable,
		&i.HouseholdRole,
		&i.Birthdate,
	)
	return i, err
}

const insertLogin = `-- name: InsertLogin :one
INSERT INTO identity.user_login (
    user_id,
    provider,
    external_subject,
    email,
    display_name,
    last_login_at
)
VALUES ($1, $2, $3, $4, $5, now())
RETURNING user_login_id, user_id, provider, external_subject, email, display_name, last_login_at, created_at
`

type InsertLoginParams struct {
	UserID          int64       `json:"user_id"`
	Provider        string      `json:"provider"`
	ExternalSubject string      `json:"external_subject"`
	Email           string      `json:"email"`
	DisplayName     pgtype.Text `json:"display_name"`
}

// Link flow: strict insert — a conflict means the provider identity is
// already bound (to this or another user) and surfaces as ErrConflict.
func (q *Queries) InsertLogin(ctx context.Context, arg InsertLoginParams) (IdentityUserLogin, error) {
	row := q.db.QueryRow(ctx, insertLogin,
		arg.UserID,
		arg.Provider,
		arg.ExternalSubject,
		arg.Email,
		arg.DisplayName,
	)
	var i IdentityUserLogin
	err := row.Scan(
		&i.UserLoginID,
		&i.UserID,
		&i.Provider,
		&i.ExternalSubject,
		&i.Email,
		&i.DisplayName,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const listLoginsByUser = `-- name: ListLoginsByUser :many
SELECT user_login_id, user_id, provider, external_subject, email, display_name, last_login_at, created_at
FROM identity.user_login
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListLoginsByUser(ctx context.Context, userID int64) ([]IdentityUserLogin, error) {
	rows, err := q.db.Query(ctx, listLoginsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityUserLogin{}
	for rows.Next() {
		var i IdentityUserLogin
		if err := rows.Scan(
			&i.UserLoginID,
			&i.UserID,
			&i.Provider,
			&i.ExternalSubject,
			&i.Email,
			&i.DisplayName,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, provider, external_subject, email, display_name, is_active, last_login_at, created_by, created_at, updated_by, updated_at, role, first_name, last_name, backup_email, household_id, is_searchable, household_role, birthdate
FROM identity.users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]IdentityUser, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityUser{}
	for rows.Next() {
		var i IdentityUser
		if err := rows.Scan(
			&i.UserID,
			&i.Provider,
			&i.ExternalSubject,
			&i.Email,
			&i.DisplayName,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.Role,
			&i.FirstName,
			&i.LastName,
			&i.BackupEmail,
			&i.HouseholdID,
			&i.IsSearchable,
			&i.HouseholdRole,
			&i.Birthdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByHousehold = `-- name: ListUsersByHousehold :many
SELECT u.user_id, u.provider, u.external_subject, u.email, u.display_name, u.is_active, u.last_login_at, u.created_by, u.created_at, u.updated_by, u.updated_at, u.role, u.first_name, u.last_name, u.backup_email, u.household_id, u.is_searchable, u.household_role, u.birthdate
FROM identity.users u
JOIN household.household_member hm
  ON hm.user_id = u.user_id
 AND hm.household_id = $1
ORDER BY u.created_at
`

// Members of a household regardless of which household their active
// pointer currently sits on. household_role on the returned rows is the
// member's ACTIVE-household role — callers needing the member's role in
// THIS household read it from household.household_member instead.
func (q *Queries) ListUsersByHousehold(ctx context.Context, householdID int64) ([]IdentityUser, error) {
	rows, err := q.db.Query(ctx, listUsersByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityUser{}
	for rows.Next() {
		var i IdentityUser
		if err := rows.Scan(
			&i.UserID,
			&i.Provider,
			&i.ExternalSubject,
			&i.Email,
			&i.DisplayName,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.Role,
			&i.FirstName,
			&i.LastName,
			&i.BackupEmail,
			&i.HouseholdID,
			&i.IsSearchable,
			&i.HouseholdRole,
			&i.Birthdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByIDs = `-- name: ListUsersByIDs :many
SELECT user_id, provider, external_subject, email, display_name, is_active, last_login_at, created_by, created_at, updated_by, updated_at, role, first_name, last_name, backup_email, household_id, is_searchable, household_role, birthdate
FROM identity.users
WHERE user_id = ANY($1::bigint[])
`

func (q *Queries) ListUsersByIDs(ctx context.Context, dollar_1 []int64) ([]IdentityUser, error) {
	rows, err := q.db.Query(ctx, listUsersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityUser{}
	for rows.Next() {
		var i IdentityUser
		if err := rows.Scan(
			&i.UserID,
			&i.Provider,
			&i.ExternalSubject,
			&i.Email,
			&i.DisplayName,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.Role,
			&i.FirstName,
			&i.LastName,
			&i.BackupEmail,
			&i.HouseholdID,
			&i.IsSearchable,
			&i.HouseholdRole,
			&i.Birthdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE identity.session
SET revoked_at = now()
WHERE user_id = $1
  AND revoked_at IS NULL
`

// Deactivation kills every live refresh-token family for the user so the
// session cookie path dies immediately (access tokens still expire on
// their own TTL).
func (q *Queries) RevokeUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const searchUsers = `-- name: SearchUsers :many
SELECT user_id, provider, external_subject, email, display_name, is_active, last_login_at, created_by, created_at, updated_by, updated_at, role, first_name, last_name, backup_email, household_id, is_searchable, household_role, birthdate
FROM identity.users u
WHERE is_active
  AND is_searchable
  AND u.user_id <> $1
  AND ($2::bigint IS NULL
       OR NOT EXISTS (
           SELECT 1
           FROM household.household_member hm
           WHERE hm.household_id = $2::bigint
             AND hm.user_id = u.user_id))
  AND (
         display_name ILIKE $3
      OR first_name   ILIKE $3
      OR last_name    ILIKE $3
      OR email        ILIKE $3
  )
ORDER BY display_name NULLS LAST, email
LIMIT $4
`

type SearchUsersParams struct {
	ExcludeUserID      int64       `json:"exclude_user_id"`
	ExcludeHouseholdID pgtype.Int8 `json:"exclude_household_id"`
	Pattern            pgtype.Text `json:"pattern"`
	RowLimit           int32       `json:"row_limit"`
}

// Household-invite candidate search: opt-in, active users only, caller and
// the caller's household members excluded. pattern is a pre-escaped LIKE
// pattern built by the service. Membership lives in household_member —
// a candidate whose active pointer sits elsewhere may still belong to
// the excluded household.
func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]IdentityUser, error) {
	rows, err := q.db.Query(ctx, searchUsers,
		arg.ExcludeUserID,
		arg.ExcludeHouseholdID,
		arg.Pattern,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityUser{}
	for rows.Next() {
		var i IdentityUser
		if err := rows.Scan(
			&i.UserID,
			&i.Provider,
			&i.ExternalSubject,
			&i.Email,
			&i.DisplayName,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.Role,
			&i.FirstName,
			&i.LastName,
			&i.BackupEmail,
			&i.HouseholdID,
			&i.IsSearchable,
			&i.HouseholdRole,
			&i.Birthdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActiveHousehold = `-- name: SetActiveHousehold :execrows
UPDATE identity.users u
SET household_id   = $1,
    household_role = (SELECT hm.role
                      FROM household.household_member hm
                      WHERE hm.household_id = $1
                        AND hm.user_id = $2),
    updated_by     = $3,
    updated_at     = now()
WHERE u.user_id = $2
  AND EXISTS (
      SELECT 1
      FROM household.household_member hm
      WHERE hm.household_id = $1
        AND hm.user_id = $2)
`

type SetActiveHouseholdParams struct {
	HouseholdID pgtype.Int8 `json:"household_id"`
	UserID      int64       `json:"user_id"`
	By          pgtype.Text `json:"by"`
}

// LEN-26: moves the user's active-household pointer (household_id +
// household_role) to a household they already belong to. The EXISTS guard
// makes "not a member" lose with zero rows; role syncs from the membership
// row in the same statement so the two columns can never diverge.
func (q *Queries) SetActiveHousehold(ctx context.Context, arg SetActiveHouseholdParams) (int64, error) {
	result, err := q.db.Exec(ctx, setActiveHousehold, arg.HouseholdID, arg.UserID, arg.By)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserActive = `-- name: SetUserActive :execrows
UPDATE identity.users
SET is_active  = $2,
    updated_by = $3,
    updated_at = now()
WHERE user_id = $1
`

type SetUserActiveParams struct {
	UserID    int64       `json:"user_id"`
	IsActive  bool        `json:"is_active"`
	UpdatedBy pgtype.Text `json:"updated_by"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserActive, arg.UserID, arg.IsActive, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserHousehold = `-- name: SetUserHousehold :execrows
UPDATE identity.users
SET household_id   = $1,
    household_role = $2,
    updated_at     = now()
WHERE user_id = $3
  AND household_id IS NOT DISTINCT FROM $4
`

type SetUserHouseholdParams struct {
	HouseholdID         pgtype.Int8 `json:"household_id"`
	HouseholdRole       string      `json:"household_role"`
	UserID              int64       `json:"user_id"`
	ExpectedHouseholdID pgtype.Int8 `json:"expected_household_id"`
}

// Conditional update: the expected-household guard turns a concurrent
// accept/leave race into a zero-row conflict instead of a lost update.
// household_role is set atomically with the move: 'owner' for fresh
// default households, 'member' when joining via invite accept.
func (q *Queries) SetUserHousehold(ctx context.Context, arg SetUserHouseholdParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserHousehold,
		arg.HouseholdID,
		arg.HouseholdRole,
		arg.UserID,
		arg.ExpectedHouseholdID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserHouseholdRole = `-- name: SetUserHouseholdRole :execrows
UPDATE identity.users
SET household_role = $1,
    updated_by     = $2,
    updated_at     = now()
WHERE user_id = $3
  AND household_id = $4
`

type SetUserHouseholdRoleParams struct {
	HouseholdRole string      `json:"household_role"`
	By            pgtype.Text `json:"by"`
	UserID        int64       `json:"user_id"`
	HouseholdID   pgtype.Int8 `json:"household_id"`
}

// Role change within the same household; the expected-household guard
// keeps a stale actor from re-adding a role after the user moved.
func (q *Queries) SetUserHouseholdRole(ctx context.Context, arg SetUserHouseholdRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserHouseholdRole,
		arg.HouseholdRole,
		arg.By,
		arg.UserID,
		arg.HouseholdID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserRole = `-- name: SetUserRole :execrows
UPDATE identity.users
SET role       = $2,
    updated_at = now()
WHERE user_id = $1
`

type SetUserRoleParams struct {
	UserID int64  `json:"user_id"`
	Role   string `json:"role"`
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserRole, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserSearchable = `-- name: SetUserSearchable :execrows
UPDATE identity.users
SET is_searchable = $2,
    updated_by    = $3,
    updated_at    = now()
WHERE user_id = $1
`

type SetUserSearchableParams struct {
	UserID       int64       `json:"user_id"`
	IsSearchable bool        `json:"is_searchable"`
	UpdatedBy    pgtype.Text `json:"updated_by"`
}

func (q *Queries) SetUserSearchable(ctx context.Context, arg SetUserSearchableParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserSearchable, arg.UserID, arg.IsSearchable, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchUserLogin = `-- name: TouchUserLogin :execrows
UPDATE identity.users
SET last_login_at = now()
WHERE user_id = $1
`

// Linked-login sign-in: bump the user row's sign-in timestamp without
// overwriting its primary email/display_name.
func (q *Queries) TouchUserLogin(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, touchUserLogin, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE identity.users
SET email        = $2,
    display_name = $3,
    is_active    = $4,
    updated_by   = $5,
    updated_at   = now()
WHERE user_id = $1
`

type UpdateUserParams struct {
	UserID      int64       `json:"user_id"`
	Email       string      `json:"email"`
	DisplayName pgtype.Text `json:"display_name"`
	IsActive    bool        `json:"is_active"`
	UpdatedBy   pgtype.Text `json:"updated_by"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUser,
		arg.UserID,
		arg.Email,
		arg.DisplayName,
		arg.IsActive,
		arg.UpdatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :execrows
UPDATE identity.users
SET first_name   = $2,
    last_name    = $3,
    backup_email = $4,
    birthdate    = $5,
    updated_by   = $6,
    updated_at   = now()
WHERE user_id = $1
`

type UpdateUserProfileParams struct {
	UserID      int64       `json:"user_id"`
	FirstName   pgtype.Text `json:"first_name"`
	LastName    pgtype.Text `json:"last_name"`
	BackupEmail pgtype.Text `json:"backup_email"`
	Birthdate   pgtype.Date `json:"birthdate"`
	UpdatedBy   pgtype.Text `json:"updated_by"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.BackupEmail,
		arg.Birthdate,
		arg.UpdatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertLogin = `-- name: UpsertLogin :one
INSERT INTO identity.user_login (
    user_id,
    provider,
    external_subject,
    email,
    display_name,
    last_login_at
)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (provider, external_subject)
    DO UPDATE SET
        email = CASE WHEN EXCLUDED.email = '' THEN identity.user_login.email ELSE EXCLUDED.email END,
        display_name = EXCLUDED.display_name,
        last_login_at = now()
RETURNING user_login_id, user_id, provider, external_subject, email, display_name, last_login_at, created_at
`

type UpsertLoginParams struct {
	UserID          int64       `json:"user_id"`
	Provider        string      `json:"provider"`
	ExternalSubject string      `json:"external_subject"`
	Email           string      `json:"email"`
	DisplayName     pgtype.Text `json:"display_name"`
}

// First sign-in creates the mapping; subsequent sign-ins refresh the
// cached provider claims and the sign-in timestamp.
func (q *Queries) UpsertLogin(ctx context.Context, arg UpsertLoginParams) (IdentityUserLogin, error) {
	row := q.db.QueryRow(ctx, upsertLogin,
		arg.UserID,
		arg.Provider,
		arg.ExternalSubject,
		arg.Email,
		arg.DisplayName,
	)
	var i IdentityUserLogin
	err := row.Scan(
		&i.UserLoginID,
		&i.UserID,
		&i.Provider,
		&i.ExternalSubject,
		&i.Email,
		&i.DisplayName,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO identity.users (
    provider,
    external_subject,
    email,
    display_name,
    last_login_at,
    created_by,
    updated_by
)
VALUES ($1, $2, $3, $4, now(), $5, $6)
ON CONFLICT (provider, external_subject)
    DO UPDATE SET
        -- An empty email claim must never blank out a stored address.
        email = CASE WHEN EXCLUDED.email = '' THEN identity.users.email ELSE EXCLUDED.email END,
        display_name = EXCLUDED.display_name,
        last_login_at = now(),
        updated_by = EXCLUDED.updated_by,
        updated_at = now()
RETURNING user_id, provider, external_subject, email, display_name, is_active, last_login_at, created_by, created_at, updated_by, updated_at, role, first_name, last_name, backup_email, household_id, is_searchable, household_role, birthdate
`

type UpsertUserParams struct {
	Provider        string      `json:"provider"`
	ExternalSubject string      `json:"external_subject"`
	Email           string      `json:"email"`
	DisplayName     pgtype.Text `json:"display_name"`
	CreatedBy       string      `json:"created_by"`
	UpdatedBy       pgtype.Text `json:"updated_by"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.Provider,
		arg.ExternalSubject,
		arg.Email,
		arg.DisplayName,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i IdentityUser
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.ExternalSubject,
		&i.Email,
		&i.DisplayName,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.BackupEmail,
		&i.HouseholdID,
		&i.IsSearchable,
		&i.HouseholdRole,
		&i.Birthdate,
	)
	return i, err
}
